### ISSUE TITLE
Using external Javascript libraries that modify the DOM

### ISSUE THREAD

**Issue by fiatjaf** [cyclejs/cyclejs#10]
Is it possible? How should one do it?

**Comment by tusharmath** [comment]
@staltz It would just be really great if you had an example of Google Maps working with CycleJS. There are multiple problems that developers face. For instance, the jsx parser starts vomiting as soon as it sees custom tags representing webcomponents.

**Comment by staltz** [comment]
@tusharmath Check out a repository I have in my github, staltz/annankatu which uses Google Maps. But not with JSX, though. In general it's not a good idea to use JSX.

**Comment by tusharmath** [comment]
@staltz Thanks! That was very helpful. In what scenario would I use a web-component instead of a widget?
