### ISSUE TITLE
Use requestAnimationFrame

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#220]
_From @staltz on August 8, 2015 16:58_

https://github.com/cyclejs/cycle-core/issues/100

_Copied from original issue: cyclejs/cycle-dom#28_

**Comment by staltz** [comment]
_From @drewdeal on August 13, 2015 16:3_

Looking forward to this being in place. :-0

**Comment by staltz** [comment]
_From @dmitriid on August 26, 2015 13:43_

This might be of relevance: https://github.com/Matt-Esch/virtual-dom/wiki  see main-loop: Batch virtual DOM changes. Update the virtual tree at most once per request animation frame.

This is probably the most important element when people talk about requestAnimationFrame. It's quite possible it would be "enough" to use main-loop in Cycle.

P.S. No doubt, you have already looked at this :)
P.P.S. No doubt, integrating this might not be simple or enough

**Comment by staltz** [comment]
_From @ckknight on September 9, 2015 2:6_

I accomplished this on my project by doing

```js
return {
    DOM: vTree$
      .sample(0, requestAnimationFrameScheduler)
};
```

Where the requestAnimationFrameScheduler schedules the next immediate event with `requestAnimationFrame`.

**Comment by staltz** [comment]
:+1:

**Comment by staltz** [comment]
_From @ryanhiebert on October 12, 2015 12:44_

@ckknight: Very interesting. Is that just this, which I gleaned from https://gist.github.com/JesterXL/66a4d42f756272dcc8d8?

```js
requestAnimationFrameScheduler = stream.observeOn(Rx.Scheduler.requestAnimationFrame)
```

**Comment by staltz** [comment]
_From @ryanhiebert on October 12, 2015 12:46_

Or I guess it's probably just

```js
requestAnimationFrameScheduler = Rx.Scheduler.requestAnimationFrame
```

**Comment by staltz** [comment]
_From @Frikki on December 3, 2015 23:50_

So we require RxJS-DOM?

**Comment by ckknight** [comment]
I had initially written my own scheduler, but later transitioned to using RxJS-DOM's implementation.

**Comment by dubiousdavid** [comment]
What's the status of this?

**Comment by staltz** [comment]
This issue is kind of vague and we're putting rAF usage into cycle/time nowadays, so lets discuss issues related to rAF there.
