### ISSUE TITLE
makeDOMDriver does not handle being called before DOM Ready

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#222]
_From @WorldMaker on October 20, 2015 16:19_

I created a test bundle of all my scripts (using `jspm bundle-sfx` if you are curious, but that shouldn't matter) and when attempting to run as a bundle I hit the case where the browser was running the `makeDOMDriver` function prior to the DOM Ready. (Interestingly the DOM in this case was just the single DIV I'm currently using as a container, so kind of amazing the browsers manage to run the scripts before evaluating the DIV...)

Does it make sense for `makeDOMDriver` to handle the case where it is being called before DOM Ready?

_Copied from original issue: cyclejs/cycle-dom#56_

**Comment by staltz** [comment]
Yeah I'll mark this as a bug because makeDOMDriver should indeed start doing its stuff after the DOM is ready, but nothing will change on the API side. You will still call makeDOMDriver whenever you want.

**Comment by chadrien** [comment]
I'll be working on this.

This is simply about adding `document.addEventListener(`DOMContentLoaded`, () => {/**/})` at the right place in `makeDOMDriver` right?

**Comment by staltz** [comment]
@chadrien I think we should wait for a major rewrite to Cycle DOM before doing this. In other words, let's pause any development on Cycle DOM master, unless it's a critical bug. Check out this branch https://github.com/cyclejs/dom/tree/diversity where we are rewriting Cycle DOM in TypeScript and Snabbdom. It'll be a breaking change because virtual-dom API differs from snabbdom just a tiny bit.

I'll remove `help wanted` from this issue for now. I'll check other issues to see if `help wanted` is for real.

**Comment by staltz** [comment]
See also comments of duplicate https://github.com/cyclejs/core/issues/301

**Comment by Cmdv** [comment]
@staltz got a fix but TypeScript doesn't like `Property 'readystate' does not exist on type 'EventTarget'`.

might be a fix [here](http://stackoverflow.com/questions/35789498/new-typescript-1-8-4-build-error-build-property-result-does-not-exist-on-t) but then I'm not sure how I can make a test that would be reasonable!! basically I've been no help!! 

But here is the [PR](https://github.com/cyclejs/dom/pull/124/files)

**Comment by artfuldev** [comment]
if this is still a bug I can work on this...

**Comment by Cmdv** [comment]
Take my PR as a reference if you like @artfuldev 😄 
I've not bothered learning TypeScript as I went towards PureScript instead! So this bug is still open

**Comment by artfuldev** [comment]
I saw the PR @Cmdv - you're almost done.

**Comment by Cmdv** [comment]
in this case it might be quicker to do that and just submit your own PR 😄  @artfuldev

**Comment by Frikki** [comment]
Did you start working on this, @artfuldev ?

**Comment by artfuldev** [comment]
I can complete this? I want to start contributing to Cycle.js somewhere, and this looked like low hanging fruit... I didn't hear from staltz, so I didn't proceed much. But this shouldn't take much time. Please, can I work on this?

**Comment by Frikki** [comment]
The dom library is undergoing some heavy refactoring which is [waiting for a merge](https://github.com/cyclejs/cyclejs/pull/444), so it might be better for you to wait until then to avoid massive merge conflicts. @artfuldev

**Comment by artfuldev** [comment]
Please point me to any other low hanging fruit then @Frikki 
As an aside, not able to contribute from a Windows machine. Should a Mac be alright?

**Comment by Frikki** [comment]
I don’t know about Windows, but any unix-like system would surely do.

You can [filter issues by size](https://github.com/cyclejs/cyclejs/issues?q=is%3Aopen+is%3Aissue+label%3A%22size+S%22) to search for small issues. You can also just wait a day or two, then the merge will surely have happened.

**Comment by artfuldev** [comment]
Has the merge happened?

**Comment by staltz** [comment]
No, you can ignore the big refactor PR for the time being. Frikki would do incremental refactors.

**Comment by staltz** [comment]
Fixed finally in the `unified` branch. Not yet released.
