### ISSUE TITLE
Passing 'cycle1' as the scope name breaks isolate

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#243]
_From @Keyamoon on January 15, 2016 22:22_

This is just a silly bug that I spotted when reading the code. Can be easily fixed by prefixing all scope names passed to `isolate` to prevent conflicts with auto generated names. Here's a [test case](http://jsbin.com/levobu/edit?html,js,output).

_Copied from original issue: cyclejs/isolate#5_

**Comment by jvanbruegge** [comment]
This is now fixed in `@cycle/dom` v21 :tada:
