### ISSUE TITLE
Proper DOM cleanup while driver disposal

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#263]
This problem is actual for such use cases as hot-reload of cycle app, or then cycle apps are pereodically instantiated while runtime.

In such scenarios when don't need running app anymore we dispose all sinks and sources, then probably cleanup HTML and replace with with new instance.

The problem is that while DOM driver disposal vdom tree is not cleaned up and thus `destroy` hooks on elements (widgets) do not work, this may cause some leaks and side effects.

To address this issue I curretly use use this as a solution:
```js
const _makeDOMDriver = (contaner, options) =>
  (dom$) => {
    let empty$ = new BehaviorSubject()
    empty$.onNext(false)
    let source = makeDOMDriver(contaner, options)(
      Observable.combineLatest(dom$, empty$, (dom, empty) => {
        return empty ? div('') /* empty dom */ : dom}
      )
    )
    let _dispose = source.dispose
    source.dispose = () => {
      empty$.onNext(true)
      _dispose.apply(source)
    }
    return source
  }
```

I wonder if something like this (vdom cleanup) should be done by DOM driver by default while disposal.

**Comment by TylorS** [comment]
I think this would be more easily done, and require less work if done like:

```js
dipose: () => {
  disposeable.dispose()

  while (rootElement.firstChild) {
    myNode.removeChild(myNode.firstChild);
  }
}
```

**Comment by whitecolor** [comment]
Want to turn your attention onto this one.
Considering driver disposal supposed to clear up effects it produced/spawned. Isn't DOM it suposed to destroy DOM it created on disposal - is it correct that "dead" html (without events) is left after disposal? 

Well maybe visual clearing up the dom it is not a requirement but look at this leak:
http://www.webpackbin.com/Nkc1io14-
Look at the console, after disposal - interval set in `hook` is still working, though supposed to be cleared up on element's removal.
And then replace `makeDOMDriver` with `_makeDOMDriver` that clears up vDOM on disposal - no leak. I think this is not `maybe` but `must` be included, as it is actually can be classified as a bug.

**Comment by staltz** [comment]
Raising this from suggestion=>bug, maybe=>could.

**Comment by staltz** [comment]
Test that whitecolor wrote:

```js
  it('should clean dom up properly on disposal', function (done) {
    const number$ = Rx.Observable.range(1, 3)
      .concatMap(x => Rx.Observable.of(x).delay(50));
    let hookTick = 0
    function app() {
      var hookInterval
      var hook = {
        insert: () => {
          hookInterval = setInterval(() => hookTick++, 1)
        },
        destroy: () => {
          clearInterval(hookInterval)
        }
      }
      return {
        DOM: Rx.Observable.of(
          h3('.target', {hook: hook}, 'DOM')
        )
      };
    }

    const {sinks, sources, run} = Cycle(app, {
      DOM: makeDOMDriver(createRenderTarget('disposal'))
    });

    const dispose = run();
    setTimeout(() => {
      dispose()
      const hookTickOnDisposal = hookTick
      setTimeout(() => {
        let renderTarget = document.getElementById('disposal')
        assert.equal(renderTarget.innerHTML, '');
        assert.ok(hookTick > 0);
        assert.equal(hookTickOnDisposal, hookTick);
        done();
      }, 50)

    }, 100);
});
```

**Comment by Frikki** [comment]
You can assign this to me, and I’ll make an attempt to fix it.

**Comment by whitecolor** [comment]
@Frikki https://github.com/cyclejs/dom/pull/128 you may look in to this, it was almost implemented, but I haven't finished.

**Comment by Frikki** [comment]
@whitecolor Could you please provide your example (bug and workaround) with the latest releases?

**Comment by whitecolor** [comment]
@Frikki see PR, I believe test and fix there should work

**Comment by Frikki** [comment]
@whitecolor No, they don’t. I have been attempting to implement the suggestions with the latest releases, but to little avail. Hence, my request.
