### ISSUE TITLE
@cycle/proxy idea for circular dependecy

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#287]
After discussion with @TylorS what about such api for proxying curcular deps?
```js
import proxy from '@cycle/proxy'
//...
function MyComponent () {
  const {imitate, stream} = proxy()
  const componentFoo = ComponentFoo({stream, DOM})
  const componentBar = ComponentBar({HTTP, componentFoo.props$})
  imitate(componentBar.value$)
```

as alternative to https://github.com/cyclejs/core/issues/170

**Comment by staltz** [comment]
Can you explain it to me? Why is it better? Etc

**Comment by TylorS** [comment]
Here's a implementation in most - http://esnextb.in/?gist=8bb48396e9160c80579facff991694f7

It wasnt so much that it's better, but that we could have a consistent API across stream libraries.

**Comment by whitecolor** [comment]
> It wasnt so much that it's better, but that we could have a consistent API across stream libraries.

babel-plugin too will provider "consistent api" as it will be transparent for the user and will not require special `imports` and explicit proxying code wich still introduce kind a little bit of side effect notion to the user. 

This is just for thoughs.

**Comment by staltz** [comment]
```js
const {imitate, stream} = proxy()
```

If this `imitate` anyway refers to `stream`, why can't we attach it like `stream.imitate`? Then it would be

```js
function MyComponent () {
  const stream = proxy()
  const componentFoo = ComponentFoo({stream, DOM})
  const componentBar = ComponentBar({HTTP, componentFoo.props$})
  stream.imitate(componentBar.value$)
}
```

**Comment by staltz** [comment]
And I'm confused, what would `import proxy from '@cycle/proxy'` import? RxJS 4 Subject? RxJS 5? most?

**Comment by whitecolor** [comment]
Right, probably more perttier, requires one or two more line and special `impor` import could look like:
`import proxy from '@cycle/proxy/most'`

**Comment by axefrog** [comment]
Here's an idea. What do you guys think of this approach?

```js
function Auth({ event$, HTTP }) {
  // ...
  return {
    HTTP,
    state$
  }
}

function Page({ auth$, DOM }) {
  // ...
  return {
    DOM,
    event$
  }
}

function App(sources) {
  // Declare our components
  var auth = Component(['state$', 'HTTP'], Auth)
  var page = Component(['event$', 'DOM'], Page)

  // Wire our component shells together into whatever complex
  // dependency structure we require
  var composite = connect({
    auth: {
      event$: page.event$.filter(e => e.type === 'login'),
      HTTP: sources.HTTP
    },
    page: {
      auth$: auth.state$,
      DOM: sources.DOM
    }
  });

  // Run the composite just like a normal component, which
  // now calls the actual component functions with internally-
  // proxied stream sources and sinks.
  var sinks = composite(sources)
  return sinks
}
```

**Comment by whitecolor** [comment]
@axefrog what does this give you beside of proxying (and circular deps)? kinda sources/sinks mapping/merging?

**Comment by axefrog** [comment]
@whitecolor It's just a clean way to wrap up circular dependencies. By getting the sinks before they're available, you can easily build your sources for each component then supply them after the fact. I'm in the process of implementing the idea and have noticed my API isn't quite right (I'll update the example once I've straightened it out)... but the concept is close enough to at least be indicative.

**Comment by whitecolor** [comment]
@axefrog I've published the plugin you may test it if you want (it would be nice if you did), the only thing you need to have `import {Subject} from 'rx'` or `import Rx from 'rx'` in the module.

**Comment by axefrog** [comment]
I would except I'm actually not using Cycle, but rather @TylorS 's [MotorCycle](https://github.com/motorcyclejs/core)... so my rxjs skills have atrophied a little... my implementation is in terms of [Most.js](https://github.com/cujojs/most).

**Comment by whitecolor** [comment]
Oh ok we where discussing `most` with @TylorS, so I will probably add it soon to the plugin.

**Comment by axefrog** [comment]
Updated example:

```js
function App(sources) {
  const makeSources = ({auth, page}) => ({
    auth: {
      event$: page.event$.filter(e => e.type === 'login'),
      HTTP: sources.HTTP
    },
    page: {
      auth$: auth.state$,
      DOM: sources.DOM
    }
  });

  // `auth` and `page` are the sinks from each component
  const {auth, page} = makeSinks(makeSources, {
    auth: [Auth, ['state$', 'HTTP']],
    page: [Page, ['event$', 'DOM']],
  });

  return { /* merge sinks so they can be returned*/ }
}

Somewhat simpler and more concise version of the earlier example I posted.
```

**Comment by whitecolor** [comment]
@axefrog what do you think about doing circular via babel-plugin, would it fit your needs?

**Comment by axefrog** [comment]
Honestly, I'm not a fan of the idea because it's turning Babel into a DSL generator rather than a tool for getting early access to general language features. By using a plugin, you make Babel into a hard dependency for a Cycle app.

**Comment by staltz** [comment]
> By using a plugin, you make Babel into a hard dependency for a Cycle app.

The plugin would be entirely optional, opt-in.

> BTW how do you want to do imports for different cycle libs versions? It should be in some standar way for drivers as well I believe.

Drivers should be independent of stream libraries, but `Cycle.run` depends on the stream library. There will be `@cycle/run-rx`, `@cycle/run-most`, etc. The proxy library you are suggesting would be actually only for most, since RxJS already has a way for achieving that.

**Comment by axefrog** [comment]
> The plugin would be entirely optional, opt-in.

Of course, and people can do what they like with their own apps, but my point is with respect to core functionality being only available via a Babel plugin. People may want to solve the problem without being cornered into the land of Babel plugins. If there's a generic, non-plugin solution though, then there's no issue.

**Comment by whitecolor** [comment]
> People may want to solve the problem without being cornered into the land of Babel plugins. If there's a generic, non-plugin solution though, then there's no issue.

Babel ES2015 is - just a set of plugins. I'm not sure that everyting that included in babel ES2015 will be there in browsers/node eventually. At least not soon. So you will need babel (wich as I said are actually set of transformation plugins) for along time. The same is for TypeScript, it is too just transiper/compiler with some extended features.

Code is about convinience for developer and redability for users, not about following some "generic" solutions. For JS generic is writing everyting in ES5.

**Comment by whitecolor** [comment]
> Drivers should be independent of stream libraries.
I'm not sure about it, I mean many drivers will have to have kind of different entry points for different libs, and some common part for drivers mechanics. Probabably like:
```js
import {makeDOMDriver} from '@cycle/dom/most'
```

> The proxy library you are suggesting would be actually only for most, since RxJS already has a way for achieving that.
Not sure what you mean, what `most` lacks that `rx` has for a achieving that?

**Comment by staltz** [comment]
> I'm not sure about it, I mean many drivers will have to have kind of different entry points for different libs, and some common part for drivers mechanics.

Not really, we have found how to allow drivers use whatever stream library they wish, and we use a conversion layer in between. The whole point of Cycle Diversity is joining together community efforts together (Cycle + Motorcycle) and allowing seamless interop so people don't go asking: "is there a Notification driver compatible with RxJS 5?", "is there an HTTP Driver for most?" etc which would mean fragmentation.

**Comment by whitecolor** [comment]
> found how to allow drivers use whatever stream library they wish, and we use a conversion layer in between.

Yes I believe it is quite possible to have abstraction this kind of layer, but I wonder what API will look like.

**Comment by staltz** [comment]
It's open source, you can check the repos `base`, `rx-adapter`, etc

**Comment by whitecolor** [comment]
> Honestly, I'm not a fan of the idea because it's turning Babel into a DSL generator rather than a tool for getting early access to general language features. By using a plugin, you make Babel into a hard dependency for a Cycle app.

Babel by its creators meant to be more than just a single purpose transpiler for enabling ES6/ES7 features, people see it this way because of some limited understanding of its capabilities (and their own needs). "Javascript" (with all its caveats for creating functional code) and "rx" (or any other lib) is too hard dependencies for your app. If you wan't you code be more messy just because you don't wan't "another hard dependency", that is your choise. I maybe missing something but that is how I see it.

**Comment by staltz** [comment]
Yeah, the point of this plugin is it's still experimental and entirely optional. When something is experimental, we shouldn't push it away. We should try it out. That's what "experimental" means. :)
