### ISSUE TITLE
select(selector, options) to customize isolation

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#296]
E.g. `DOMSource.select('.button', {own: false}).events('click')` would change how isolation works by allowing click events from the children as well.

https://github.com/TylorS/cycle-snabbdom/issues/29#issuecomment-213075925

**Comment by laszlokorte** [comment]
why would one use isolation if all in such a use case?

**Comment by TylorS** [comment]
@laszlokorte Just when you want to isolate from siblings. So that a single component could have multiple instances in the same view, but still have access to its children.

**Comment by laszlokorte** [comment]
@TylorS Oh, that makes sense, thanks.

**Comment by TylorS** [comment]
Suggestion on the API would be welcome, I don't know if `own` is the best description.

**Comment by staltz** [comment]
@TylorS I'm thinking `includeChildren`

**Comment by TylorS** [comment]
That would work for me.

**Comment by whitecolor** [comment]
`includeEventsThatAreHappeningInsideChildIsolatedComponents` )

**Comment by TylorS** [comment]
> includeEventsThatAreHappeningInsideChildIsolatedComponents )

Hehe, but this would also work for `.observable` (being renamed to `.elements` in v10), so I think it'd have to be

`includeEventsThatAreHappeningInsideChildIsolatedComponentOrElementsThatExistInsideOfChildIsolatedComponents` :stuck_out_tongue_winking_eye:

**Comment by whitecolor** [comment]
I think by default select should include isolated children and their events events, like it is normal behaviour in HTTP driver - parent aware of all that children are doing.

**Comment by staltz** [comment]
> I think by default select should include isolated children and their events events, like it is normal behaviour in HTTP driver - parent aware of all that children are doing.

Actually we discussed this quite a bit with Laszlo, Frikki, and Tylor, and got to the conclusion the DOM driver simply has different isolation semantics than the HTTP driver does. It's very often needed to have parent-child isolation when it comes to the DOM Driver.

**Comment by whitecolor** [comment]
Not still completely sure about it, possible default isolation from parent is a good thing, but than `{own: false}` is needed too.

**Comment by staltz** [comment]
We actually did this already through a slightly different API than discussed https://cycle.js.org/releases.html#flexible-isolation
