### ISSUE TITLE
DevTool with stream graph visualization

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#302]
This one is a sister issue of #256, but still a very different task. It's already rather work in progress, supporting only xstream. 

Depends on:
- xstream-run 3.1 because it calls startGraphSerializer syncly
- xstream 6.1 because it has setDebugListener
- Cycle DOM 12.2 because it sets _isCycleSource on its source streams
- Cycle HTTP 10.2 because it sets _isCycleSource on its source streams

To close this issue:
- [x] Update devtool with xstream v5.3
- [x] Detect which streams are sources and sinks
- [x] Efficient updates (using dagre directly with snabbdom svg)
- [x] Fix the switch or restart of the DevTool
- [x] Fix zapping order to reflect exactly app streams
- [x] On `complete` zap, dont hide previous `next` zap
- [x] Stream that restarts should go from inactive=>active
- [x] Bug: startup zap event label not shown
- [x] Select speed of zapping
- [x] Operator labels as graph nodes, to improve looks of merge/combine
- [x] Use custom operator `timeSpread` for graphSerializer.js actualZap$ that knows how to speed up when the queue is long enough
- [x] Detect if app is Cycle.js/xstream app, otherwise show info about it
- [ ] Publish as Chrome extension

Later:
- [ ] Zoom/pan controls?
- [ ] How to display higher-order stream graph?

Links:
https://developer.chrome.com/devtools
https://developer.chrome.com/extensions/devtools
https://developer.chrome.com/extensions
https://github.com/snookca/CoffeeConsole

**Comment by niieani** [comment]
Is xstream support planned because of complexity of implementation with RxJS or simply because it's easier to release an xstream-only DevTool for v1 and then expand it to RxJS?

**Comment by staltz** [comment]
Both, but mainly the first reason. There are some things we need as metadata which are easier to just directly build in xstream, than to try to infer with advanced techniques, from RxJS. For now I am just focusing on getting the DevTool usable and have enough features with xstream. I don't know how much effort it would take to do that for RxJS.
