### ISSUE TITLE
Old drivers to support diversity via stream adapters

### ISSUE THREAD

**Issue by tusharmath** [cyclejs/cyclejs#324]
Thanks for taking cyclejs to the next level with the diversity release.  We have been using cyclejs in production for sometime now and have successfully migrated to the release candidate versions. I would like to share my experience here though —

I think this could be a much more controlled release. By that I mean once you start migrating to the latest version of cycle you end up breaking your application completely and thus requiring regression, which is not the actual intent for why one must upgrade. For instance to use cycle diversity we upgraded the following things in our application —
1. RxJS 5
2. Cycle/Core
3. Cycle/HTTP
4. Cycle/DOM

After this everything went haywire, our integration tests started failing and all the other libraries that were using the stable version of Rx don't work any more. The reason is that the diversity release doesn't only target diversity changes but also quite a lot of other  changes. A better way would be to not break the API in this release especially for DOM, HTTP and CORE together and let developers migrate their application incrementally. 

One way to achieve this would be to create depreciated methods that output warning on console when invoked. It is possible that in certain cases the API requires a change, in that case, one might replace the older api methods/props with stubs that output warnings when invoked.

**Comment by whitecolor** [comment]
Cycle drivers API is not completely stable yet, but it is reasonably small and simple to follow its updates. There is an issue #196 that allow to see breaking changes.

> A better way would be to not break the API in this release especially for DOM, HTTP

API is evolving and moreover it is just impossible to keep some of parts of old API, diversity is going to be a kind of major release.

**Comment by staltz** [comment]
@tusharmath how do you feel about this issue now that we have migration guides for Diversity?
I want your team using Cycle.js in production to proceed and have a good experience, so in case the migration is a real pain I could try releasing Cycle DOM v9.4.patch to support diversity.

**Comment by TylorS** [comment]
You can use the diversity drivers with the old versions of @cycle/core as things are currently, if I understand the motivation here, this might help.

```js
import Cycle from '@cycle/core' // v6.x
import RxAdapter from '@cycle/rx-adapter'
import {makeDOMDriver} from '@cycle/dom' v10.x

const DOMDriver = makeDOMDriver('#app', {transposition: true])

Cycle.run(main, {
  DOM: sink$ => DOMDriver(sink$, RxAdapter)
})
```

**Comment by staltz** [comment]
@TylorS I think he wants the opposite: old Cycle DOM with Cycle Diversity (Rx 5?).

**Comment by tusharmath** [comment]
@staltz Sorry for the delayed response I am on a vaccation.

It would make sense to have the older drivers support diversity.

**Comment by whitecolor** [comment]
@tusharmath if you need this you can do this with https://github.com/whitecolor/cycle-convert

Something like that, should work:
```js
import Cycle from '@cycle/rxjs-run' // v7.x
import RxAdapter from '@cycle/rx-adapter'
import RxjsAdapter from '@cycle/rxjs-adapter'
import {makeDOMDriver} from '@cycle/dom' // old dom
import convert from 'cycle-convert'

const DOMDriver = makeDOMDriver('#app', {transposition: true})
const adapters = [rxAdapter, rxjsAdapter]
// traverseSource if transposition is used
const DOMDriverRxJs = convert(DOMDriver, ...adapters, {traverseSource: true})

Cycle.run(main, {
  DOM: sink$ => DOMDriverRxJs(sink$)
})
```

**Comment by tusharmath** [comment]
@whitecolor thanks a ton! We wrote a tiny little adapter of our own but
cycle-convert looks much better. My point is it would have made migration
for most users much easier if diversity was supported by old drivers. There
are too many breaking changes to manage otherwise.

On Sun, Jul 3, 2016, 2:58 PM Alex <notifications@github.com> wrote:

> @tusharmath <https://github.com/tusharmath> if you need this you can do
> this with https://github.com/whitecolor/cycle-convert
>
> Something like that, should work:
>
> import Cycle from '@cycle/rxjs-run' // v7.ximport RxAdapter from '@cycle/rx-adapter'import RxjsAdapter from '@cycle/rxjs-adapter'import {makeDOMDriver} from '@cycle/dom' // old domimport convert from 'cycle-convert'
>
> const DOMDriver = makeDOMDriver('#app', {transposition: true})
>
> const adapters = [rxAdapter, rxjsAdapter]// traverseSource if transposition is usedconst DOMDriverRxJs = convert(DOMDriver, ...adapters, {traverseSource: true})
> Cycle.run(main, {
>   DOM: sink$ => DOMDriverRxJs(sink$)
> })
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cyclejs/core/issues/324#issuecomment-230144193>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAL3sqyOG-7sLDIgzw1feiN4d9RTeZI-ks5qR4C_gaJpZM4IvvsA>
> .
>
-- 
Regards,
Tushar Mathur.
www.tusharm.com

**Comment by tusharmath** [comment]
I think the documentation is in a really good state thus closing this issue.
