### ISSUE TITLE
Make DOM EventDelegator an xstream Producer

### ISSUE THREAD

**Issue by Hypnosphi** [cyclejs/cyclejs#333]
Currently, a stream obtained from `sources.DOM.select(selector).events(type)` isn't lazy: a DOM event listener is attached right after `.events()` call

**Comment by Hypnosphi** [comment]
ok, I'm wrong and

**Comment by Hypnosphi** [comment]
But it still would be good if DOM listeners would remove themselves when there's no destinations left

**Comment by TylorS** [comment]
Nice catch! Thank you for the example, and I totally agree.

**Comment by staltz** [comment]
Raised the priority of this issue.

**Comment by jvanbruegge** [comment]
Not relevant any more
