### ISSUE TITLE
Pass custom modules to snabbdom in HTML Driver

### ISSUE THREAD

**Issue by aronallen** [cyclejs/cyclejs#335]
I would like to be able to pass custom modules to snabbdom.
Specifically I would like to make a snabbdom module for [Stylematic](https://github.com/rtsao/stylematic)
So I can use it with snabbdom like this
`h('div', {stylematic : {/* ... styles ... */}}, [])`

**Comment by TylorS** [comment]
@staltz We should add the option to add modules to the html driver. 

Which makes me remember, we don't have isolation working for the initial render of html do we?

**Comment by staltz** [comment]
Yeah, two serious issues. Let's not block Cycle Diversity release because of that, but should do.

**Comment by leiserfg** [comment]
I read the code of DOM driver and the inscription of modules is really there, just is too complicated of ad custom modules. What about adding  a `extendDefaultModules` to  DOMDriverOptions an then:
```js
const modules =  (options.extendDefaultModules)? defaultModules.concat(options.modules || []): (options.modules || defaultModules);
```

**Comment by staltz** [comment]
This is done in the Cycle Unified branch. Not yet released though.
