### ISSUE TITLE
Update "Try Cycle.js" button on frontpage

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#339]
- [ ] Update Webpackbin Cycle.js template https://github.com/christianalfoni/webpack-bin/issues/149
- [ ] Update "try cycle" button on cycle.js.org

**Comment by Widdershin** [comment]
@staltz do you still want to do this now that `tricycle` supports xstream?

We can alternatively create any needed issue to improve `tricycle`.

**Comment by staltz** [comment]
Hey @Widdershin I think this issue is about using webpackbin. Now that Tricycle is updated to use latest versions and Webpackbin is a bit outdated project, I'd say this issue is irrelevant now. Also agree we can open issues on Tricycle.
