### ISSUE TITLE
Update React Native driver(s)

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#342]
Work in progress in the [`rn`](https://github.com/cyclejs/cyclejs/tree/rn) branch.

- [x] Example working
- [x] Update to the latest React Native just so it works
- [x] Tests
- [x] Rewrite it in TypeScript
- [x] Rewrite the example, make sure it works
- [x] Overhaul: use xstream and latest Cycle packages
  - [x] Screen driver
  - [x] Cycle Unified support
  - [x] Toast driver
  - [x] ScreenSource type
  - [x] Rework the handler architecture
  - [x] Rework handler architecture again
- [x] Separate the packages
- [x] 🇿🇼 Release candidate 1 
- [x] [Keyboard](http://facebook.github.io/react-native/releases/next/docs/keyboard.html) driver
- [x] Update to RN 0.45
- [x] Update to RN 0.48
- [x] Navigation? ~~https://reactnavigation.org/docs/intro/~~ "done" through [cycle-native-navigation](https://youtu.be/1ToJ7cxb1R8?t=508)
- [x] Investigate screen driver's problem with synchronous handler attachment
  - Problem is: we need intent() to be called before view() so that the handler subject exists prior to VNode creation which looks up the handler subject from the dict
  - Perhaps we could do some type of microtask handling to schedule handler lookup when creating ReactElements ?
  - What about elements that are `mapTo` prior to intent() call?
- [x] Isolation for native screen driver
  - [x] Use React context?
- [x] release cycle/react, cycle/react-dom, cycle/react-native
- [ ] Move non-screen drivers to their own repos (in this cyclejs org though)
- [ ] most.typings.d.ts and rxjs.typings.d.ts

-------

Not for the monorepo, but still relevant to do:

- Back button driver (somewhat related to navigation too)
- AsyncStorage driver
- [Alert](http://facebook.github.io/react-native/releases/next/docs/alert.html) driver with categories and isolation 
- [AccessibilityInfo](http://facebook.github.io/react-native/releases/next/docs/accessibilityinfo.html) driver
- [Vibration](http://facebook.github.io/react-native/releases/next/docs/vibration.html) driver
- Everything else :)

**Comment by TylorS** [comment]
I'm going to start tackling this issue beginning tomorrow.

**Comment by grabbou** [comment]
@TylorS I wouldn't say that I master CycleJS enough, but I know a bit about React Native, so if you'd like to have some extra hands to help - let me know!

**Comment by staltz** [comment]
And I'm going to start tackling this issue now. :D

**Comment by staltz** [comment]
As you may already have noticed, I'm building Cycle Native as [multiple drivers](https://github.com/cyclejs/cyclejs/tree/ac69d3990cd1b9b552f90282b8bfd23ef32c2b0b/native/src) as opposed to one. React Native and Mobile APIs have multiple "devices" (keyboard, screen, gyroscope, camera, storage), much more than the browser provides, so in Cycle.js concepts it certainly makes sense to have a driver for each of these.

I'm still not sure how to structure the drivers and packages though. There are basically two options:

**One package, many drivers**

- `@cycle/native/screen`
- `@cycle/native/toast`
- `@cycle/native/keyboard`
- ...

**One package per driver**

- `@cycle/native-screen`
- `@cycle/native-toast`
- `@cycle/native-keyboard`
- ...

Could I have some feedback from the community?
Please press 👍 for **one package, many drivers** 
or ❤️ for **one package per driver**.

**Comment by mightyiam** [comment]
## Importing

1 package, many drivers would be imported like:

```ts
import { screen, toast, keyboard } from '@cycle/native'
```

or this way

```ts
import screen from '@cycle/native/screen'
import toast from '@cycle/native/toast'
import keyboard from '@cycle/native/keyboard'
```

?

1 package per driver would be like this:

```ts
import screen from '@cycle/native-screen'
import toast from '@cycle/native-toast'
import keyboard from '@cycle/native-keyboard'
```

correct?

## Individual packages, individual versioning

Individual packages have the advantage of being able to break API of a single package. The users of all other packages will not be bothered to have to upgrade. Isn't that valuable to you, fellow users?

**Comment by staltz** [comment]
@mightyiam 

This way

```js
import screen from '@cycle/native/screen'
import toast from '@cycle/native/toast'
import keyboard from '@cycle/native/keyboard'
```

or this way

```js
import screen from '@cycle/native-screen'
import toast from '@cycle/native-toast'
import keyboard from '@cycle/native-keyboard'
```

> Individual packages have the advantage of being able to break API of a single package. The users of all other packages will not be bothered to have to upgrade. Isn't that valuable to you, fellow users?

Yes that sounds valuable to me too, and I'm preferring to do Option ❤️, but I want to hear what people think.

**Comment by staltz** [comment]
One package per driver it is. Check some packages I published on npm already. https://github.com/cyclejs/cyclejs/tree/rn

- native-keyboard
- native-screen
- native-toast

**Comment by staltz** [comment]
So far I've been on a path to make one driver for each native API in React Native. I've been thinking about doing something different instead. Given that React Native versions move fast and there's a steady amount of breaking changes, and also given that React Native is a monolith framework, not modular, it will be hard to stay up to date on the Cycle.js side, simply because of maintenance.

So I've been thinking that only `native-screen` would be in this monorepo, and other drivers and libraries would be in this `cyclejs` github org, but not in the monorepo, and independently maintained with various degrees of up-to-dateness and quality. This is fine because it's the *modular* open source way of doing stuff. The upside is that we can also give npm publish rights to whoever feels like updating `@cycle/native-toast` or `@cycle/native-whatever`, and we've been doing that already with some packages like `@cycle/storage`.

I'd like to have some *semantics* to the monorepo. It should mean "these packages are taken care of with equal diligence and are the core of the ecosystem". Because `@cycle/native-screen` would exist in every Cycle/RN app, and because it sets up the "App" React component, I think it could be a library in the monorepo, while other libraries are independently maintained. For instance, I already maintain https://github.com/staltz/cycle-native-navigation but it wouldn't be in this monorepo.

What do you think @jvanbruegge @Widdershin ?

**Comment by jvanbruegge** [comment]
I think is fine. It would be impossible to maintain all parts without community maintainers. Keeping the most important part official and maintained should be enough

**Comment by staltz** [comment]
This issue is now done, through a slightly different plan than initially. We won't have the `native-screen` driver, that was replaced by https://github.com/cyclejs/react-native. Now there's also https://github.com/cyclejs/react and https://github.com/cyclejs/react-dom. The issues with isolation and race conditions (described in the original post) are now solved in https://github.com/cyclejs/react which is a dependency of https://github.com/cyclejs/react-native.

Took 2 years to get this issue closed :tada:

**Comment by jvanbruegge** [comment]
Whoo
