### ISSUE TITLE
htmlDriver can only be used once

### ISSUE THREAD

**Issue by stucox** [cyclejs/cyclejs#348]
Similar to the [isomorphic example](https://github.com/cyclejs/examples/blob/master/isomorphic/server.js), I’m trying to generate snapshots of my app’s DOM at various URLs — although as an offline script rather than a server.

To do this I have a driver which provides a stream of mock Location objects (e.g. `{pathname: '/'}`) as a source, and am using [`htmlDriver`](https://github.com/cyclejs/dom/blob/master/src/makeHTMLDriver.ts) to render the output vnode stream:

```js
const locations = [
  {pathname: '/'},
  {pathname: '/about'},
  ...
];
run(app, {
  DOM: makeHTMLDriver(html => writeToFile(html)),
  history: () => xs.of(locations),
  ...
});
```

— but this only calls `writeToFile()` once, with the DOM of the `/about` page. I’ve discovered this is because `htmlDriver()` filters the vnode stream down with `.last()`:

https://github.com/cyclejs/dom/blob/master/src/makeHTMLDriver.ts#L27

Interested to know why it does this?

I appreciate in the context of a server you’d only want one value per request, but maybe that should be the server code’s job to handle and `htmlDriver` could just stick to turning a stream of vnodes into a stream of HTML strings?

**Comment by TylorS** [comment]
@stucox The html driver only emits one time because a server can only send 1 response per request. Staltz has explained this somewhere much much better than I can, I'll see if I can find that. I don't think this is really an issue you're facing though. This could still be accomplished.

Trying to follow your example code
```js
const locations = [...]

locations.forEach(location => {
  run(app, {
    DOM: makeHTMLDriver(html => writeToFile(html)),
    history: () => xs.of(location)
  })
})

```

**Comment by stucox** [comment]
As I said, I understand why a server would only want to handle one value per request — and you’d want this to be the last DOM state, if the DOM goes through several states in a request. But that’s server-specific behaviour, so I question whether that belongs in the `htmlDriver` (which could potentially be used for other things too).

Yes — wrapping `run()` in a `forEach()` is probably the simplest way to work around it in my immediate case, which is fairly static.

However if I wanted to snapshot a specific state where some state was retained between navigation (e.g. some specific part of a login flow), this wouldn’t work!

**Comment by staltz** [comment]
I understand your concern and use case. On the other hand, I'm wondering how could we support the existing `last()` logic if we were to implement the changes you are suggesting. Server-side rendering is the primary use case for the HTML Driver, but how could a developer specify `last()` for the stream? Any suggestions @stucox @TylorS ?

**Comment by staltz** [comment]
Answering myself: maybe `last()` should always be added in a lightweight `mainWrapper` like in here: https://github.com/cyclejs/examples/blob/master/isomorphic/server.js#L28-L38

**Comment by TylorS** [comment]
Yeah, I think that would be the correct way to do it. I think I like the idea of removing `last()` only if we take the time to document it properly 👍

**Comment by TylorS** [comment]
IF we decide to do this, we should roll this into a single breaking update with #351

**Comment by stucox** [comment]
Apologies for the delayed response. Yep — wrapping the app works.

Alternatively, we could consider other ways of emitting HTML… What if the htmlDriver provided a stream interface (e.g. `driver.html$`) rather than a callback?

```js
const htmlDriver = makeHTMLDriver();
htmlDriver.html$.last().map(html => res.send(prependHTML5Doctype(html)));

Cycle.run(app, {
  DOM: htmlDriver,
  ...
});
```

Of course the consumer could decide what to do with this stream (whether to take every value, the last value, etc).

Backward compatibility could be retained by still supporting the `effect` callback argument — which would continue to only be called with the last value.

**Comment by staltz** [comment]
Oops @TylorS, I already released v11, forgot to bundle this one too. Oh well, let's not fear the bumps to major number.

**Comment by staltz** [comment]
Done. I'll release a new version of Cycle DOM soon if all tests pass.
