### ISSUE TITLE
Using TSX

### ISSUE THREAD

**Issue by eshansingh** [cyclejs/cyclejs#350]
On the Cycle.js getting started guides, you explained how to use JSX with Babel instead of HyperScript. However, for those of us who are using TypeScript, which offers TSX, how might we use it with Cycle.js? I know that Snabberdom offers a JSX factory, but I am unsure if it'll work with TSX.

Thanks!

**Comment by TylorS** [comment]
@staltz I'm not sure these are the proper labels for the issue, but I wanted make sure that I think this should probably be documented if we do want to push the usage of TypeScript.

@eshansingh I don't know if anyone has taken the time to try this yet, we'll definitely take a look and try to get back to you. If you figure it out in the mean time, please share your findings :)

**Comment by staltz** [comment]
Yeah these seem to be the correct labels. I'll add also help wanted because right now I'm focused on extinguishing some fires.

**Comment by eshansingh** [comment]
So I've found two main options (_which I have not tested out yet_). After using a `.tsx` extention instead of `.ts`, you can:

* Disable the react-style emit by using `"jsx": "preserve"` in the `tsconfig.json` file (or passing `preserve` for the `--jsx` option in `tsc`). Then use `snabbdom-jsx` on that output (because the output will have JSX as-is).
*  Use the normal `import {html} from 'snabbdom-jsx'` and then change the `reactNamespace` option to `html`, which will make TypeScript use the the `html` function for TSX generation (hopefully)

Again, I've not tested these out yet. Give me an hour or two, and if it works, I'll send a PR as @staltz asked.

Once again, thanks!

**Comment by Steelfish** [comment]
Be wary of typescript optimizing out any import statements you haven't used. I believe the official way around it is to do a global import like: `import 'snabbdom-jsx'`. I could not get this to work in my own .tsx solution so I opted for a webpack plugin that adds the `import {html} from 'snabbdom-jsx'` statements to typescript's transpiled javascript. 
```
 {
    test: /\.tsx$/,
    exclude: /node_modules/,
    loader: 'babel-loader!webpack-append?import {html} from \'snabbdom-jsx\'!ts-loader'
}
```
Is the setup I am currently using along with `[ "transform-react-jsx", { "pragma": "html"}]` as a babel plugin in .babelrc and `"jsx": "preserve"`.

**Comment by eshansingh** [comment]
@Steelfish How did you get `snabbdom-jsx` to load? TypeScript complains that the module isn't there, even after `npm i --save snabbdom-jsx`.

**Comment by Steelfish** [comment]
Typescript will complain about any modules that do not have type definitions I believe. You can try to see if typings has any definitions for snabbdom-jsx or make your own definition.

I personally circumvented the issue by not having typescript load snabdom-jsx. I use webpack to let the ts-loader transpile the typescript, preserve the jsx in the transpilation using the `"jsx": "preserve"` option and then add the `import {html} from 'snabdom-jsx'` using the the webpack-append loader to the top of every compiled tsx file, and finally pass that to the babel loader for jsx transform.

**Comment by eshansingh** [comment]
@Steelfish That means that I'll have to add Babel on top of TypeScript, which is not at all ideal.

**Comment by Steelfish** [comment]
It is not. Which is why I am hoping there is a cleaner solution using the reactNamespace option, although I could not get that to work.

**Comment by eshansingh** [comment]
@Steelfish I couldn't either. It's tricky, because TSX always assumes `createElement`.

**Comment by staltz** [comment]
Done, now there is the example `tsx-seconds-elapsed`.

**Comment by dancasey** [comment]
@Steelfish @eshansingh, I know this issue is a little old, but if you still want a way to do TSX without babel, here is what I did:

`tsconfig.json`:

```json
    "jsx": "react",
    "reactNamespace": "JSX"
```

In your component `.tsx` file:

```ts
const snabbdom = require("snabbdom-jsx");
const JSX = {createElement: snabbdom.html};
```

So now you've tricked it to use JSX as the namespace, under which it will find `createElement` set to `snabbdom.html`. This works for me for simple demos since I can just compile with `tsc` and run with `budo app.js`, without needing babel or webpack.

**Comment by eshansingh** [comment]
@dancasey This is a pretty good solution, but do you know of a way to do this without putting 

```js
const JSX = {createElement: snabbdom.html};
```

in every single file?

**Comment by dancasey** [comment]
Yes, you could put those two lines just in your top-level file, and then make a `d.ts` file with the contents `declare var JSX;`. Just make sure that the `d.ts` file is picked up by your `tsconfig.json` and then `tsc` won't complain. 

Just tested and it works. I am using TS 2.0 beta, but I'm pretty sure it'll work with 1.8 also.

**Comment by dancasey** [comment]
Forgot to add that you need to make it global, so here's the 3 lines to put in your top file:

```ts
const snabbdom = require("snabbdom-jsx");
const JSX = {createElement: snabbdom.html};
(<any> window).JSX = JSX;
```

**Comment by eshansingh** [comment]
@dancasey Hey, sorry for bothering you, but how can you do this in environments where the window variable isn't available?

**Comment by dancasey** [comment]
@eshansingh If there's a global object in your environment (like `window` is for DOM) that you can attach your `JSX` object to, it might work...

**Comment by kritollm** [comment]
`import {html} from 'snabbdom-jsx';` doesn't work in TypeScript 2.0.

Here is how I solved it ( I use .tsx extension for files with jsx code).

tsconfig.json

```javascript
{
    "include": [
        "TypeScript/**/*.ts",
        "TypeScript/**/*.tsx"
    ],
    "exclude": [
        "node_modules"
    ],
    "compilerOptions": {
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es2015",
        "jsx": "preserve"
    }
}
```

Just remove the `import {html} from 'snabbdom-jsx';` in your code and replace babel.rc with this:

babel.rc

```javascript
{
plugins: [
                "syntax-jsx",
                ["transform-react-jsx", { "pragma": "bsj.html" }],
                ["jsx-pragmatic", { "module": "snabbdom-jsx", "import": "bsj" }]
            ],
            presets: ['es2015'], extensions: [".tsx"]
}
```
If you are using Browserify and Babelify you may need to delete the .babelrc and use options instead. (For some reasons, babelify didn't work when using a .babelrc file in the project, so I had to delete it and add the options in the gulp file.)

```javascript

gulp.task('default', function () {
    return browserify({
        basedir: '.',
        debug: true,
        entries: [paths.tsadmin],
        cache: {},
        packageCache: {},
        plugin: [tsify]
    })
        .transform('babelify', {
            "presets": [
                "es2015"
            ],
            "extensions": [
                ".tsx", ".ts", ".js", ".jsx"
            ],
            "plugins": [
                "syntax-jsx",
                [
                    "transform-react-jsx",
                    {
                        "pragma": "bsj.html"
                    }
                ],
                [
                    "jsx-pragmatic",
                    {
                        "module": "snabbdom-jsx",
                        "import": "bsj"
                    }
                ]
            ]
        }
        )
        .bundle()
        .pipe(source('bundle.js'))
        .pipe(buffer())
        .pipe(sourcemaps.init({ loadMaps: true }))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(paths.webroot + '/js'));
});

```
