### ISSUE TITLE
Update snabbdom to 0.5.0 in Cycle DOM

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#351]
## If you want to build this as a PR

Please
- [x] Update snabbdom in package.json
- [x] Update our tests that are related to thunks

**Comment by jadbox** [comment]
Are there any blockers to getting this in? Is it the thunk API changes that need refactoring to?

https://github.com/paldepind/snabbdom/releases

**Comment by staltz** [comment]
Yes, we just need to do it. I'd appreciate a PR if you are interested.

**Comment by artfuldev** [comment]
What tests should be run for this to be completed, and how? I would like to help here, seems a simple enough task.

**Comment by artfuldev** [comment]
I'm not able to test,
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test-browser"
npm ERR! node v6.2.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! @cycle/dom@10.1.0 test-browser: `testem`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @cycle/dom@10.1.0 test-browser script 'testem'.
npm ERR! This is most likely a problem with the @cycle/dom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     testem
npm ERR! You can get their info via:
npm ERR!     npm owner ls @cycle/dom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\Sudarsan Balaji\Source\Repos\dom\npm-debug.log
npm ERR! Test failed.  See above for more details.

**Comment by staltz** [comment]
@artfuldev I don't think it supports windows. You'll have to use bash on windows or install a virtual machine with Ubuntu on it.

**Comment by artfuldev** [comment]
hmmm... I thought everything was cross-platform.  :(

**Comment by whitecolor** [comment]
I've run all tests on windows. the only problem with windows is usage of `mkdir -p` flag that is not supported should use `mkdirp` instead. And `testem` aslways worked on windows.

**Comment by artfuldev** [comment]
@whitecolor For me the error occurs even before that, in `rm -rf`

**Comment by whitecolor** [comment]
@artfuldev `mkdir` on windows is not the same on linux, it doesn't support `-p` flag `mkdir -p xxx`  will create `-p` folder instead of `xxx`. `rm -rf` should work normally.

Maybe update to npm v3 will solve you issue.

**Comment by artfuldev** [comment]
@whitecolor like I said, `rm -rf` doesn't work for me. even on normal cmd. says `bad command or file name 'rm'`. Is something wrong with my (whatever)?

**Comment by artfuldev** [comment]
@whitecolor I will update the npm... I was using v3, maybe an installation of visual studio overwrote the path variables...

**Comment by staltz** [comment]
Specially now with the monorepo setup, it will be very hard to make this work on windows. We're heavily using bash in this repo.
I used to develop on Windows too, and I used to use a Virtual Machine running Ubuntu. It's for free, it's easy to do, and solves the problems. It's not worth trying to support Windows.

**Comment by artfuldev** [comment]
My problem is that I run Windows on a MacbookPro already. I'm starved for space. Hmm... Let me figure something out.

**Comment by artfuldev** [comment]
bash on Windows in only available in Insider Preview builds, which may not be stable enough for my work laptop. Using a VM with an ubuntu setup is something else entirely.

**Comment by artfuldev** [comment]
@staltz doesn't this mono repo make people who work on smaller stuff pull a huge repo with a lot of history etc.?

**Comment by whitecolor** [comment]
> bash on Windows in only available in Insider Preview builds,

Bash is installed with git setup for example.

> MacbookPro already 

use mac os)

> doesn't this mono repo make people who work on smaller stuff pull a huge repo with a lot of history 

git based code doesn't take much space, and all the cyclejs modules are very compact

**Comment by artfuldev** [comment]
@whitecolor you mean git-bash works with rm -rf and mkdir -p?
@whitecolor Mac OS doesn't help me as much as Windows does. It hampers my productivity, personally.

**Comment by whitecolor** [comment]
@artfuldev yes, bash provides linux compatible command line on windows

**Comment by artfuldev** [comment]
@whitecolor great, thanks :) I just tried it out and it works!!!
