### ISSUE TITLE
HTTP Driver calling request.type with json default forces browser to make invalid preflight request

### ISSUE THREAD

**Issue by n-j-m** [cyclejs/cyclejs#360]
I encountered this when trying to make a CORS request to https://www.reddit.com/r/all.json.  I kept getting a failed preflight request even though I was only making a plain GET request.  I tracked the issue to ```request.type``` where it is being defaulted to ```json```. While this may seem innocuous, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) the ```Content-Type application/json``` is not a safe header and triggers a preflight request. Reddit blocks all non plain GET CORS requests which led to my error.

I propose only calling ```request.type``` when the type property is explicitly set in the request options sent to the HTTP driver.

**Comment by staltz** [comment]
What if we issue a non-breaking change which would allow you to fix this issue? We can then take time to investigate whether not setting `request.type` by default is worth a breaking change.

The temporary fix would be to allow `type: null` on the request object to leave the type unset. Currently `type: null` doesn't work.
