### ISSUE TITLE
Stream swallows value

### ISSUE THREAD

**Issue by SuperManitu** [cyclejs/cyclejs#361]
Hello, I have a very confusing issue that happens with xstream and rxjs alike (that's why I'm opening the report here). I have a subcomponent:
```js
export function CycleLogin({ DOM, HTTP, sessionStorage } : ISources) : ILoginSinks
{
    const login$ : Stream<RequestOptions> = DOM.select('button[type="submit"]')
        .events('click')
        .map(event => {
            event.preventDefault();
            return DOM.select('.loginField').elements();
        })
        .flatten()
        .map(arr => ({
            url: apiLocation + 'login',
            method: 'POST',
            category: 'login',
            send: {
                personnelNumber: reduceElements(arr, 'Personalnummer').value,
                password: reduceElements(arr, 'Passwort').value
            }
        })).debug('variable');

    return {
        HTTP: login$.debug('return'),
    };
}
```
but I get this Browser output when triggering the event:
```
variable: Object {url: "http://localhost/Prozessdatenerfassung/login", method: "POST", category: "login", send: Object}category: "login"method: "POST"send: Objecturl: "http://localhost/Prozessdatenerfassung/login"__proto__: Object
```

There is clearly the second debug message missing, and the HTTP sink does not make a request to the server. **This happens only the first time I click the button**. Every following click (or enter keypress as it's a form) works as expected.

**Comment by staltz** [comment]
Looks like a bug, but we'd need to reproduce in a smaller setting.

**If someone wants to help with this**, first step would be to reproduce it in a small test case in e.g. webpackbin.

My suspicion is 
```js
        .map(event => {
            event.preventDefault();
            return DOM.select('.loginField').elements();
        })
        .flatten()
```
Maybe it behaves differently if the `DOM.select('.loginField').elements()` is assigned to `elements$` outside the function.

**Comment by Hypnosphi** [comment]
There's surely a bug if the same stream is logged on the first `debug`, but not on the second.

But why do you sample clicks stream on element stream, but not the other way around? I'm pretty sure that what  you want instead is

```js
DOM.select('.loginField').elements()
        .map(arr =>
            DOM.select('button[type="submit"]')
                .events('click')
                .map(event => {
                    event.preventDefault();
                    return arr;
                })
        )
        .flatten()
```

**Comment by SuperManitu** [comment]
@Hypnosphi
What is the difference between my and your version? My thought was: on click on the login button, the stream gets the input fields, maps to the values and uses them to login.

@stalz
I will try to reproduce the issue

**Comment by Hypnosphi** [comment]
What your code do is "when button is clicked, start listening for dom changes and react to that". What mine do is "whenever dom changes, change the reaction to clicks"

**Comment by SuperManitu** [comment]
Oh right, reactive is thinking the other way round. Of course, your code is right

**Comment by SuperManitu** [comment]
@staltz 
this should be a webpackbin with the issue, but for me webpackbin refuses to add @cycle/dom in a new version to the mix: http://www.webpackbin.com/E1L9JI2PW

**Comment by staltz** [comment]
Yeah, I noticed the same issue with Webpackbin some time ago. But anyway, thanks for the code.

**Comment by SuperManitu** [comment]
I found the source of the problem, it was because of cyclic-router, when I switched my implementation to use @cycle/history everything works normal
But this is still very strange behavior.

**Comment by SuperManitu** [comment]
I think this might have to do with the misunderstanding of streamadapters as I run into that issue again with my own driver. So basicly this is replaced by #392 
Closing it
