### ISSUE TITLE
Incorrect usage of the term "pure"

### ISSUE THREAD

**Issue by paldepind** [cyclejs/cyclejs#365]
I've recently been catching up with Cycle.js. The library has really improved since the last time I looked at :+1:. I also watched the Egghead videos which was very enjoyable. One thing that caught my attention though is that the term "pure" seems to be used a bit too liberal in the documentation. For example in the Streams section the documentation states:

> Streams become very useful when you transform them with the so-called operators, pure functions that create new Streams on top of existing ones.

It then shows an example using xstream's `fold`. However, `fold` is not pure. In fact any stateful operator in xstream/RxJS/most/etc. is impure. The impurity is rather subtle but occurs because the result of `fold` depends not only on its arguments—but also on the time at which it is called.

We can see this with a simple example ([JSBin here](http://jsbin.com/zawipo/edit?js,output)).

```js
function main(sources) {
  const inc$ = sources.DOM.select('.inc').events('click').mapTo(+1);
  const refresh$ = sources.DOM.select('.ref').events('click').startWith(0);
  const lastSum$ = refresh$.map(_ => inc$.fold((x, y) => x + y, 0)).flatten();
  const vdom$ = lastSum$.map(count =>
    div([
      button('.ref', 'Refresh'),
      button('.inc', 'Increment'),
      p('Counter: ' + count)
    ])
  );
  return {DOM: vdom$};
}
```

In the example each time the "Refresh" button is pressed the displayed sum is reset to zero. But why? At all times is `lastSum$` equal to an invocation `inc$.fold((x, y) => x + y, 0)`. If `fold` was a pure function `refresh$.map(_ => inc$.fold((x, y) => x + y, 0)).flatten()` should be equal to `inc$.fold((x, y) => x + y, 0)`. But this is not the case.

We can also try to make a simple refactor to the program:

```diff
    const inc$ = sources.DOM.select('.inc').events('click').mapTo(+1);
    const refresh$ = sources.DOM.select('.ref').events('click').startWith(0);
+   const sum$ = inc$.fold((x, y) => x + y, 0);
+   const lastSum$ = refresh$.map(_ => sum$).flatten();
-   const lastSum$ = refresh$.map(_ => inc$.fold((x, y) => x + y, 0)).flatten();
    const vdom$ = lastSum$.map(count =>
      div([
```

We are simply taking the sub expression `refresh$.map(_ => sum$).flatten()` and giving it a name. If `fold` was pure it would satisfy referential transparency and the refactor wouldn't change the program. But it does. After this change the "Refresh" button does nothing. This, again, is because `fold` is impure.

Since any stateful combinator in xstream/RxJS is impure and any non-trivial Cycle-app will have to make use of them this means that most uses of "pure" in the documentation are incorrect or misleading. I think what the documentation should emphasize instead is that Cycle-apps are completely free from from side-effects and non-reactive code. These things are huge advantages in themselves.

**Comment by staltz** [comment]
This has actually nothing to do with Cycle.js and nothing to do with `fold`. It's an issue with xstream `flatten`, because of its behavior with sync start and async stop when synchronously switching inner streams. I'd consider this a bug or issue in xstream.

Here's how RxJS works fine: http://jsbin.com/sutulaqoci/1/edit?js,output

**Comment by paldepind** [comment]
It does have something to do with `fold`. The problem is due to a combination of a stateful operator `fold` and `flatten`. How would you solve the issue in a way that would be pure but would still allow for `flatten` to work with streams that carry state (like those from `fold`)?

RxJS have similar problems: it's API doesn't ensure satisfy referential transparency and thus does not guarantee purity.

Consider this Cycle+RxJS program ([JSBin here](http://jsbin.com/yiluri/edit?js,console,output)).:

```js
function main(sources) {
  const inc$ = sources.DOM.select('.inc').events('click').mapTo(+1);
  const refresh$ = sources.DOM.select('.ref').events('click').startWith(0);
  const sum$ = inc$.startWith(0).scan((x, y) => x + y, 0).share();
  const lastSum$ = refresh$.map(_ => {
    return inc$.startWith(0).scan((x, y) => x + y, 0).share();
  }).switch().startWith(0);
  const vdom$ = Rx.Observable.combineLatest(sum$, lastSum$, (sum, lastSum) =>
    div([
      button('.ref', 'Refresh'),
      button('.inc', 'Increment'),
      p('sum: ' + sum),
      p('lastSum: ' + lastSum)
    ])
  );
  return {DOM: vdom$};
}
```

Clicking the "Refresh"-button effectively resets the `lastSum` counter. This happens because RxJS does not satisfy the property that `obs.map(_ => obs1).switch()` is the same as `obs1`.

We notice that the observable returned inside the mapping over `refresh$` is the exact same expression as the definition of `sum$`. So by referential transparency we can make this simple refactor:

```diff
  const sum$ = inc$.startWith(0).scan((x, y) => x + y, 0).share();
  const lastSum$ = refresh$.map(_ => {
-    return inc$.startWith(0).scan((x, y) => x + y, 0).share();
+    return sum$;
  }).switch().startWith(0);
  const vdom$ = Rx.Observable.combineLatest(sum$, lastSum$, (sum, lastSum) =>
```

But once again this refactor, that should be safe, changes the meaning of the program. Now clicking the "Refresh" button has no effect. We are again in impure-land because we combine higher order streams with stateful streams.

It seems to me like when using RxJS, xstream and libraries with similar API purity is not at all guaranteed. In fact, as far as I can tell, when using higher order stateful streams one is certain not to have purity. And thus it seems to me like the usage of "pure" in the documentation is misleading.

**Comment by staltz** [comment]
It's still not about `fold`. `scan` or `fold` operators "carry state" in the same sense that a summation formula or an integral over the reals "carries accumulation state". Both summation and integration are obviously pure, from mathematics.

The issues you are seeing are due to inner subscriptions in `flatten` or `switch`. When you added `share`, the common subscription to `sum$` is retained during the whole execution of the code, so that's why the scan operator is not re-subscribed when `switch` attempts to switch the inner Observable. **`share` is a side effect**, and this is how you are getting violation of referential transparency.

In xstream, we can cheat and manage subscriptions in a way that makes the overall behavior be ref transparent. I already opened an issue and have an idea how to fix that.

Also, just because of a corner case, I don't think emphasizing purity is misleading. 100% purity is anyway impossible in JavaScript, and we assume the reader knows this. When it comes to Cycle.js APIs, they are mostly pure and we strive to make it pure as much as we can.

**Comment by paldepind** [comment]
Yes. It's not `fold` in itself. It is stateful streams combined with higher order streams.

> share is a side effect, and this is how you are getting violation of referential transparency.

Yes. But as far as I can tell it is also the only way to carry state through the higher order operators.

> In xstream, we can cheat and manage subscriptions in a way that makes the overall behavior be ref transparent. I already opened an issue and have an idea how to fix that for flatten.

That sounds great. I'll be looking forward to seeing that.

> Also, just because of a corner case, I don't think emphasizing purity is misleading. 100% purity is anyway impossible in JavaScript, and we assume the reader knows this.

Do you think higher order stateful streams are a corner case? They are very useful in implementing dynamic collections of dynamic elements and that occurs quite often.

Also pure functions are of course possible in JavaScript. Blurring the distinction between what is pure and what isn't is misleading IMO. It's better not to call something pure when it contains impure parts.

**Comment by staltz** [comment]
> That sounds great. I'll be looking forward to seeing that.

Just fixed in xstream v5.3.2 https://github.com/staltz/xstream/blob/master/CHANGELOG.md#532-2016-07-23

**Comment by Hypnosphi** [comment]
As far as I remember, this talk gives a good explanation of why metastreams are incompatible with purity: https://www.youtube.com/watch?v=Agu6jipKfYw

I can maybe find exact timing some later

**Comment by paldepind** [comment]
@staltz, If I understand the changelog correctly, you restart in `flatten`. Then, as far as I can tell, you make it impossible to carry state through `flatten`. In xstream `fold` is _the_ way to create stateful streams and `flatten` is _the_ way to work with higher order streams. If the way to work with higher order streams restart stateful streams then the library is significantly less powerful than before.

Lets say I have two streams `a$` and `b$`. Both of these are created using `fold`, i.e. they are stateful. I now want to create a stream `c$` that switches beween `a$` and `b$`. At any time `c$` should act exactly like `a$` or `b$` including the state they have accumulated. With the old `flatten` that was possible, with the new `flatten` it seems to be impossible?

> Not really incompatible, but to enforce real purity when dealing with higher-order streams we need an infinite lookback, which causes memory issues.

There are a bunch of solutions to the problem. One is to make the reactive library less powerful. Like how  Elm solved it by not having `flatten` at all. That didn't turn out very well unfortunately.

**Comment by milankinen** [comment]
>Just fixed in xstream v5.3.2

Did you just made a breaking change with patch version increment?! 😧 If I remember right, the whole point in `xstream`'s async stop was that flattening same stream don't lose its subscriptions (and state as @paldepind pointed out). Now you just made an exception where you stop the previous stream **if** the next one has the same reference. That's the exact opposite what the semantics were before. Please consider the following code:

```js
import xs from 'xstream';
import memoize from 'memoizee';
import Cycle from '@cycle/xstream-run';
import {makeDOMDriver, h} from '@cycle/dom';
import {makeRouterDriver} from 'cyclic-router';
import {createHistory} from 'history';


const Component = title => memoize(({DOM}) => {
  const text = DOM.select("input." + title)
    .events("input")
    .map(e => e.target.value)
    .startWith("")

  return {
    DOM: text.map(t =>
      h("div", [
        h("h1", title),
        h("input." + title, {attrs: {type: "text", value: t}}),
        h("p", `Hello ${t}!`)
      ]))
  }
})

function main(sources) {
  const match$ = sources.router.define({
    '/': Component("home"),
    '/other': Component("other")
  });

  const page$ = match$.map(({value: C}) => {
    return C(sources)
  });

  const pageDOM$ = page$.map(c => c.DOM).flatten();
  const naviClick$ = sources.DOM.select("a").events("click");

  return {
    DOM: pageDOM$.map(page =>
      h("div", [
        h("div", [
          h("a", {attrs: {href: sources.router.createHref("/")}}, "Home"),
          h("br"),
          h("a", {attrs: {href: sources.router.createHref("/other")}}, "Other")
        ]),
        page
      ])),
    prevent: naviClick$,
    router: naviClick$.map(e => e.target.getAttribute("href"))
  };
}

Cycle.run(main, {
  DOM: makeDOMDriver('#main-container'),
  prevent: e => e.addListener({next: e => e.preventDefault(), complete: () => {}, error: () => {}}),
  router: makeRouterDriver(createHistory())
});
```

If I click the "home" link when I'm still in my home page, there are no changes to the page with `xstream@5.3.1` but with `xstream@5.3.2` the page resets. 

>  If I understand the changelog correctly, you restart in flatten. Then, as far as I can tell, you make it impossible to carry state through `flatten`.

@paldepind Nope. The change just makes `flatten` to reset the stream if (and only if) the next stream identity matches the previous one. 😄 Hence, e.g. if you make the following modification to my previous example, it's again possible to "carry state" over switching:

```diff
  const page$ = match$.map(({value: C}) => {
    return C(sources)
  });

- const pageDOM$ = page$.map(c => c.DOM).flatten();
+ const pageDOM$ = page$.map(c => c.DOM.debug("tsers")).flatten();
  const naviClick$ = sources.DOM.select("a").events("click");
```

**Comment by Hypnosphi** [comment]
@paldepind if c$ switches from a$ to b$,  a$ gets stopped and loses its state unless it has some more listeners attached

**Comment by whitecolor** [comment]
as I've told before (to @staltz) async behaviour modeled using `setTimeout` may lead to "unexpected results" in some cases (of course depending on expectant's view point). 

And 5.3.2 introduces kind of breaking behaviour:

```js
import xs from 'xstream'

let a$ = xs.periodic(200)
let b$ = xs.periodic(1000)

let c$ = b$.map(() => a$).flatten()

c$.addListener({
  next: (x) => console.log(x),
  error: () => {},
  complete: () => {}
})
```
| 5.3.1 | 5.3.2 |
|---|---|
| 0 | 0 |
| 1 | 1 |
| 2 | 2 |
| 3 | 3 |
| 4 | 0 |
| 5 | 1 |
| 6 | 2 |
| 7 | 3 |
| 8 | 0 |

**Comment by paldepind** [comment]
> Nope. The change just makes flatten to reset the stream if (and only if) the next stream identity matches the previous one.

Oh. Ok. Well, then it only fixes the impurity issues I  that single special case.

**Comment by paldepind** [comment]
Here is another example that demonstrates the impurity: http://jsbin.com/zawipo/edit?js,console,output. If we replace the definition of `shownSum$` with the commented one the behavior of the program changes even though it should be safe if referential transparency was satisfied. If I understand @milankinen correctly then the latest xstream release won't affect the above program. The impurity remains.

**Comment by milankinen** [comment]
@paldepind Sorry I used wrong term. The previous stream is stopped (instead of reset) but like @Hypnosphi said, if the stream has other listeners then they of course continue consuming events (thus the stream is not really stopped).

I'm not sure if I understood your second example right: what is the "correct" behaviour in that example? I'm not sure if the first version (`const shownSum$ = toggle$.map(b => b ? sum1$ : sum2$).flatten().startWith(sum1$);`) and the refactored version are semantically same anymore because you refer to `sum1$` and `sum2$` in  `combine`. Hmm, they would be same if the streams were unicast-only -- was this the issue you were trying to point out?

**Comment by paldepind** [comment]
@Hypnosphi, there isn't really any "correct" behavior. There wasn't any "correct" behavior in the first example either. In fact in the first example the behavior that would be most intuitive to me is if the "Refresh" button did nothing. But the only thing I'm trying to show is that the API is impure by showing that it doesn't satisfy referential transparency.

Referential transparency is a property of pure code that tells us that we can always replace a reference to a definition with the definition itself. Conversely we can also always replace an expression with a variable that is defined to be that expression. For instance we can easily see that `4 + 4` is the same as `const n = 4; n + n` but `const n = Date.now(); n + n` is not the same as `Date.now() + Date.now()`. This is because `Date.now` is impure and that fact severely limits the amount of refactorings that we can do with code that uses `Date.now`. 

Referential transperancy is very useful both for understanding and for refactoring code. In general it just makes it easier to reason about how a program works. However the last example shows that by replacing `inc1$` and `inc2$` with their definitions we actually modify the behavior of the program. This is because `fold` in combination with `flatten` leads to impurity.

As the video posted by @Hypnosphi explains this is pretty fundamental about FRP. Some APIs cannot be implemented in a pure way. Thus I believe there is no easy fix to the impurity and the Cycle documentation ought to not call things pure that aren't pure. Doing that only misleads people.

**Comment by staltz** [comment]
What actually happened in v5.3.1=>v5.3.2 was simply making flatten behave the same no matter if the next inner stream is (1) the same as the previous inner stream, or (2) is different to the previous inner stream. Case (2) is much more common than (1). We don't want to see a significantly different behavior just because the next inner stream is the previous inner. That's why (1) is a corner case.

In fact in @whitecolor's example, there would be no point using flatten in v5.3.1 if the expected behavior was 0,1,2,3,4,5,6,7,8. If that was the expected outcome, then it would be better just to use `a$`, not `b$.map(() => a$).flatten()`.

> Did you just made a breaking change with patch version increment?!

If a bug is considered a feature, then every bug fix is a breaking change, no matter what software it is.

Finally, I'm not in this discussion to defend anything. If you're claiming @paldepind that "it is incorrect and misleading", **I don't care**. I'm interested in suggestions on how to improve. Practical and helpful suggestions into how to make Cycle.js (or xstream, which seems to be the center of this discussion) more ref transparent and more understandable, more intuitive. Suggesting the fix that ended up in v5.3.2 was good, thanks for that. xstream is still young and did some bold innovations (i.e. hot-only) so I'm not claiming it's perfect. But telling me that it's imperfect doesn't help me at all. Recommending me to emphasize on the docs site that it's imperfect doesn't help me at all either. So if you want to be heard, suggest small improvements that would be aligned with the overall goals of xstream. I don't need to spend a Sunday reading proofs/claims of how things are wrong. Have a nice day, y'all.

**Comment by whitecolor** [comment]
>  If that was the expected outcome, then it would be better just to use a$, not b$.map(() => a$).flatten()

this is just a simple example, actually as you see this is implementation `withLastestFrom` from docs:
```js
B.map(b => A.map(a => a + b)).flatten()
```
And it won't work in for this case anymore.

but at least this aligns `xstream` behaviour with `rxjs` =)

@staltz I'm sure no one blames you, or something. Just pointing to some issues that people see, it is not always possible to give a suggestion of proper solution on how to fix or improve, but author should be much more capable of doing this.

**Comment by milankinen** [comment]
>If a bug is considered a feature, then every bug fix is a breaking change, no matter what software it is.

Changing semantics **intentionally** is a breaking change.

>What actually happened in v5.3.1=>v5.3.2 was simply making flatten behave the same no matter if the next inner stream is (1) the same as the previous inner stream, or (2) is different to the previous inner stream

You fix was **intentionally** to do the exact opposite: make `flatten` "referentially transparent" by stopping it *iff* the next inner stream is same as the previous inner stream. The code clearly tells that the handling is different if the identity mismatches. Or would you expect different results from these codes:
```js
import xs from 'xstream'

let a$ = xs.periodic(200)
let b$ = xs.periodic(1000)

let c$ = b$.map(() => a$).flatten()

c$.addListener({
  next: (x) => console.log(x),
  error: () => {},
  complete: () => {}
}) 
```

Versus:
```js
import xs from 'xstream'

let a$ = xs.periodic(200)
let b$ = xs.periodic(1000)

let c$ = b$.map(() => a$.debug('lol')).flatten()

c$.addListener({
  next: (x) => console.log(x),
  error: () => {},
  complete: () => {}
}) 
```


>In fact in @whitecolor's example, there would be no point using flatten in v5.3.1 if the expected behavior was 0,1,2,3,4,5,6,7,8. If that was the expected outcome, then it would be better just to use `a$`, not `b$.map(() => a$).flatten()`.

With the given and [documented](https://github.com/staltz/xstream#how-a-stream-starts-and-stops) semantics, user would expect that 0,1,2,3,4,5,6,7,8, whether using `a$` or `b$.map(() => a$).flatten()`. @whitecolor's example was extra simplified so that the change would be obvious (which was good IMHO). Of course there was also my example which was more real-life one but it seemed to be ignored totally.

**Comment by whitecolor** [comment]
Right, my example was just for the sake of simplification.

btw why works the same way in 5.3.2 and 5.3.1?
```js
let c$ = b$.map(() => a$.map(a => a)).flatten()
```

@staltz  I'm sure no one blames you, or something. Just pointing to some issues that people see, it is not always possible to give a suggestion of proper solution on how to fix or improve, but author should always be much more capable of doing this.

**Comment by paldepind** [comment]
I'm sorry that I can't offer ideas for improvements to the actual API or implementation. But this really is about suggesting improvements to the documentation. I believe reserving the term pure for what really is pure and differentiating between side-effect free functions and pure functions would make the documentation more precise and serve the users better.

**Comment by staltz** [comment]
@paldepind xstream docs don't mention the word "pure" neither "referential transparent" at any moment.

Whenever we use the word "pure" on cycle.js.org, it's just this case you said:

> I think what the documentation should emphasize instead is that Cycle-apps are completely free from from side-effects and non-reactive code. These things are huge advantages in themselves.

- - -

@whitecolor 
I think "withLatestFrom" in xstream is working in the same way for both v5.3.1 and v5.3.2.
http://jsbin.com/pegarajeni/1/edit?html,js,console
http://jsbin.com/bodanoxajo/1/edit?html,js,console

If we find a big problem, there's no need to panic, we could revert the change. I'm only interested in how can we go forward to make xstream more intuitive, whether or not that means making it more referentially transparent.

**Comment by whitecolor** [comment]
@staltz yes `withLatestFrom`:
```js
let c$ = b$.map(b => a$.map(a => a + b)).flatten() 
```
works the same way, I just wonder why `let c$ = b$.map(_ => a$).flatten() ` doesn't.

**Comment by staltz** [comment]
Yeah there's definitely something weird to be fixed. `debug()` presence does something weird too. But it's good, I finally nailed down a small reproducible case. http://jsbin.com/hihuvuqupo/edit?html,js,console Will put up an issue on xstream repo.

**Comment by paldepind** [comment]
> xstream docs don't mention the word "pure" neither "referential transparent" at any moment.

Indeed, yes. That is why I opened the issue against Cycle.

> If this issue is just about the particular stream library involved, we can of course add support for other stream libraries, like flyd, or Bacon, or Sodium.

As far as I know _all_ the reactive stream libraries in JavaScript are impure—so you don't get truly pure code from any of them.

I have probably not expressed this clearly enough, but I don't think the impurity is the problem. Impurity vs purity is always a trade off and there are many good reasons to have an impure streams library. It can have a simple API without loosing power. All the pure FRP implementations I've seen either loose too much power (like Elm) or add significant complexity to usage of the API (using arrows or monads). One might argue that Cycle sits at a sweet spot where code is reactive and free from side effects but without requiring the complexity that would be needed to be pure FRP. It just shouldn't advertise purity where it isn't.

**Comment by TylorS** [comment]
Man, I hate how abrasive this got in some places :/
