### ISSUE TITLE
DOM Source to support document and body

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#368]
We could support `domSource.select('document')` and `domSource.select('body')` as terminal domSources (meaning we don't know what should happen with additional `select()` after that) because there are cases where `domSource.select('document').events('click')` would be useful and easy to support.

### If you want to help build this

**assignee: @raquelxmoss**

- [ ] Add test for `domSource.select('document').events('click')` and perform a programmatic click on any part of the DOM, then assert
- [ ] Add test for `domSource.select('body').events('click')` and perform a programmatic click on any part of the DOM, then assert 
- [ ] Implement the feature in MainDOMSource.ts, in the `select` method. Somehow `document` and `body` should have special treatment. One idea is that `select('document')` would return an instance of the class `DocumentDOMSource implements DOMSource` and `select('body')` would return an instance of `BodyDOMSource implements DOMSource`. `DocumentDOMSource.select` could return always `this` instance of `DocumentDOMSource`, since it doesn't make sense to progressively select on that type.

**Comment by raquelxmoss** [comment]
If this isn't super urgent (which it doesn't seem to be), I'd like to take this on! I've been using the mouse driver for this, but if it's added to the core, we can probably deprecate parts of the mouse driver.

I haven't written typescript before, so this will be a good introduction to it.

**Comment by staltz** [comment]
Thanks @raquelxmoss, that would be great! Go ahead 👍

**Comment by wizardwerdna** [comment]
I'd be happy to tackle this is raquel doesn't have time for it.  In any case, I would propose a friendly amendment to the spec, to use `:document` and `:body` in lieu of the naked definitions (as we do with `:root`.

**Comment by raquelxmoss** [comment]
Hey folks 😄 I'm working on it this weekend, but if I don't get it done I'll hand it over 🌈

**Comment by eshansingh** [comment]
See PR #389

**Comment by staltz** [comment]
Cycle DOM v12.1.0 released with this feature. Thank you @raquelxmoss !
