### ISSUE TITLE
Define clearly somewhere how we're different from Elm

### ISSUE THREAD

**Issue by eshansingh** [cyclejs/cyclejs#374]
Personally, I feel like at first glance, Cycle.js seems to be Elm in plain JavaScript. I think we should have a section somewhere in the docs, or maybe just a link to a blog post somewhere, where we explain how the architecture of Cycle.js is different from that of Elm, why we may think that Cycle.js is a better concept than Elm (if we do think so) and what our main goals are.

Any thoughts? Modifications? Other ideas?

**Comment by staltz** [comment]
Watch this presentation http://www.atthefrontend.dk/session/Unidirectional-data-flow-architectures or read this blog post http://staltz.com/unidirectional-user-interface-architectures.html

**Comment by eshansingh** [comment]
Yes, I do know that. What I'm suggesting is linking to it in the docs.

**Comment by staltz** [comment]
Yeah we could put that in FAQ. For now, we can put it in the Wiki, and later we can move FAQ from Wiki to the docs site.
