### ISSUE TITLE
Feature request: HTTP Driver URL prefix or superagent instance option

### ISSUE THREAD

**Issue by wyqydsyq** [cyclejs/cyclejs#375]
I've found that in making an isomorphic app, if I try to make a request that browsers would resolve relative to the domain name (e.g. `/api/users`) with the HTTP driver, it'll fail on the server-side because those URLs will be resolved differently by superagent in that context. This can be avoided by having all URLs start with `http://localhost`, but that could have front-end impacts e.g. if the page is loaded by HTTPS or on a different domain. It would be nice if the HTTP driver took an options argument, with a prefix option to apply to all URLs passed to the driver, or allow passing of a custom superagent instance (so this functionality could be provided by setting up superagent with the [prefix](https://github.com/johntron/superagent-prefix) plugin).

Currently for my app to work isomorphically all URLs I pass to the HTTP driver looks like: `http://localhost/api/users`.

With a prefix option you could do something like this on the server side entry point to have the HTTP driver apply the prefix to all requests: 
```js
Cycle(App, {HTTP: makeHTTPDriver({prefix: 'http://localhost'})});
```

Or with a superagent option you could do something like this on the server side entry point to have the HTTP driver use the provided superagent instance (and any plugins it `use()`s) instead of it's default one:
```js
import superagent from 'superagent-use';
import prefix from 'superagent-prefix';

let mySuperagent = superagent.use(prefix('http://localhost'));
Cycle(App, {
    HTTP: makeHTTPDriver({superagent: mySuperagent})
});
```

A possible third solution would be to add a `use` array option to the HTTP driver which automatically adds each value to the HTTP driver superagent instance, you could then just pass an array of plugins to be `use()`d:

```js
import prefix from 'superagent-prefix';

Cycle(App, {
    HTTP: makeHTTPDriver({use: [prefix('http://localhost')]})
});
```

The two latter solutions would be a lot more powerful by allowing people to use custom superagent configurations with HTTPDriver, making this change useful well beyond this particular use case of allowing prefixes.

I'd be happy to attempt to implement this myself & submit a PR if this is something that would be accepted.

**Comment by staltz** [comment]
I think we've discussed this in the past, and since the prefix is app logic, it should live in the application, not in drivers and neither around driver setup. There are many cases where we can use sinks pre-processing before sending to drivers. Here is an example:

```js
function main // your app
```

```js
function serverMain(sources) {
  var sinks = main(sources);

  var prefixedRequest$ = sinks.HTTP.map(request => {
    return {...request, url: `http://localhost${request.url}`};
  });  

  return {
    ...sinks,
    HTTP: prefixedRequest$,
  }
}
```

```js
function clientMain(sources) {
  var sinks = main(sources);

  var prefixedRequest$ = sinks.HTTP.map(request => {
    return {...request, url: `http://www.myserver.com${request.url}`};
  });  

  return {
    ...sinks,
    HTTP: prefixedRequest$,
  }
}
```
