### ISSUE TITLE
HTTP api: response$$ vs select()

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#376]
Currently in HTTP driver API:
`HTTP.response$$` is doing the same as `HTTP.select()`

Is it worth to keep both? Maybe consider removing one option to to make API more consistent? Personally I don't like `HTTP.response$$` - not sure why, maybe because it introduces additional symbolic semantics and wider API surface.

An from a talk I remember @staltz said that he will probably decide to go with just `select()` and remove `response$$`.

**Comment by Hypnosphi** [comment]
I would prefer if it was just `HTTP` and if `HTTPSource` interface would just extend `Stream` with `select` method

**Comment by whitecolor** [comment]
Yes, but it was decided to avoid patching stream with `select` method, this is probably the main reason for non-stream HTTP source. But there is also `isolateSink`, `isolateSource` methods, and not sure how TS is going to handle this stream api extension (probably would not be a problem).

**Comment by staltz** [comment]
If we remove `response$$`, I think users will be limited as they won't be able to accomplish everything that they need. For the majority of the cases, `select(category)` is enough, but what if you want to get all the `DELETE` responses? Then you need

```js
var deleteResponse$ = sources.HTTP.response$$
  .filter(response$ => response$.request.method === 'DELETE')
  .flatten();
```

**Comment by whitecolor** [comment]
considering that `HTTP.response$$` is doing the same as `HTTP.select()`:
```js
var deleteResponse$ = sources.HTTP.select()
  .filter(response$ => response$.request.method === 'DELETE')
  .flatten();
```
BTW, I would also extend select API with function param for to filter request:
```js
var deleteResponse$ = sources.HTTP
  .select(request => request.method === 'DELETE')
  .flatten();
```

**Comment by staltz** [comment]
> considering that HTTP.response$$ is doing the same as HTTP.select()

That's very true, I had forgotten that you can use `select()` with no argument.

> BTW, I would also extend select API with function param for to filter request

You can do `HTTPSource.filter(req => req.method === 'DELETE').select().flatten()`

**Comment by whitecolor** [comment]
`HTTPSource.filter` takes predicate to filter response$ not request
https://github.com/cyclejs/cyclejs/blob/master/http/src/MainHTTPSource.ts#L21

so to simplify custom request filtering either `HTTPSource.filter` API could be changed to handle request instead of response$, but in this case `HTTPSource.filter` could be a little confusing with common stream filter method that deals with something that comes out of stream.

If select API could be extended, and there would be no need in custom `filter` method, and `select` would be the one that deals with `request` either selecting it with fn predicate or by string category for the sake of simplicity.

**Comment by whitecolor** [comment]
@staltz 

This actually would be the same as your example (select comes first, and then stream's `filter`) applied:
```js
 var deleteResponse$ = sources.HTTP
     .select()
     .filter(r$ => r$.request.method === 'DELETE')
   .flatten();
```
This could be replaced with:
```js
 var deleteResponse$ = sources.HTTP
     .select(request => request.method === 'DELETE')
   .flatten();
```
I'm not for minimizing amount of symbols in the code, but for concise API, and may be wrong here.

so you are against extending `select` API with function predicate for `request` object?

**Comment by staltz** [comment]
`.select().filter(...).flatten()` wouldn't work because filter returns an HTTPSource, not a stream. 

And yes in general I'm against polymorphic function type for `select`. If some functionality A is significantly different to another functionality B, then they should be in separate API functions, not conflated. `select` is basically a specialized `filter(...).response$$`. I'd like that select for HTTP looks and behaves like select for the DOM. And it's nice that HTTPSource.filter is very similar to array.filter and stream.filter. No need to conflate them.

**Comment by staltz** [comment]
That said, if we remove `response$$` and use just `select()` with no params, we could consider removing `HTTPSource.filter` too.

**Comment by whitecolor** [comment]
The only value I seen in filter is that it creates "filtered" source that can be pass further in components as source object, not a stream.

```js
let filteredHTTP = HTTP.filter(r$ => r$.request.method === 'DELETE')
component({HTTP: filteredHTTP})
```

**Comment by staltz** [comment]
Actually `HTTPSource.filter` is used in `isolateSource`. Maybe it's not worth removing filter just for the sake of removing.

**Comment by whitecolor** [comment]
Well right then I agree. What you think about `HTTPSource.filter` to handle `request` not `response$`? The reason for this may be: this method still custom and returns not a stream but HTTPSource, and accessing any other props in `response$` for filtering doesn't make any sense.

```js
.filter(request => request.method === 'DELETE')
.select()
```

**Comment by staltz** [comment]
That makes sense, but it would be breaking change. Is it worth it?

**Comment by whitecolor** [comment]
Well I woudn't be so worried about breaking changes if API would becomes better, it will come up with major version anyway.

I would ask what others think about it, so proposal is two (quite minor) changes to `HTTPSource` API:

1) remove `HTTPSource.response$$` prop in favor of `HTTPSource.select()`
2) make `HTTPSource.filter` handle `request` object not `response$` for simpler advanced source filtering (the reason is given in my previous post)

@Hypnosphi @TylorS @laszlokorte

**Comment by whitecolor** [comment]
@staltz 
What in general do you think about making `HTTPSource.filter()` accept predicate function for `request` not for `response$$` which still makes no big sense?

**Comment by staltz** [comment]
Done in HTTP v11.0.0
