### ISSUE TITLE
Cycle/DOM isolateModule is being bailed out be chrome profiler

### ISSUE THREAD

**Issue by tusharmath** [cyclejs/cyclejs#383]
version: `12.0.3`

Dom driver performance suffers because of the `try catch` being used inside the loop. 
https://github.com/cyclejs/cyclejs/blob/master/dom/src/isolateModule.ts#L26

<img width="593" alt="screen shot 2016-08-06 at 3 00 08 pm" src="https://cloud.githubusercontent.com/assets/194482/17456055/b0d91caa-5be8-11e6-9762-ef19373cfad3.png">

Instead of using try/catch putting a simple `if`  condition such as —
```js
 if (!result.value) {
  hasNext = false
  break
}
```

Makes the driver perform much better. More details — https://github.com/GoogleChrome/devtools-docs/issues/53

**Comment by whitecolor** [comment]
try catch in this case is really ugly

**Comment by staltz** [comment]
Thank you @tusharmath 
Sometimes my brain equals poop
