### ISSUE TITLE
make running tests compatible with windows

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#384]
tests can not be run without hassle on windows because different details inside the npm scripts commands. People that would like to contribute **will have a hard time** with cycle repo.

Some problems on windows:
`mkdir -p lib` doesn't work (p argument is not supported)
`../node_modules/.bin/typings install` - doesn't work: `../ is not a command` (not sure how to fix)

I would even consider moving to **gulp** eventually, it is more suitable for complex tasks, it is only may seem that it is exessive complication but really it is just easier to maintain eventually. You still just reinvent gulp when creating something like `.scripts` folder for complex tasks

Leave it here just as a reminder.

**Comment by staltz** [comment]
I'm sorry, this definitely will not happen. Our bash scripts are small enough, understandable, easy to maintain, and get things done. Migrating to gulp or grunt would be a major task, and I'm not even sure it would be able to do everything that bash can do, like `${PWD##*/}` here https://github.com/cyclejs/cyclejs/blob/master/dom/package.json#L79. Also it's very important that me and Tylor are fully aware of how the scripts work in details.

Windows users will have to try bash for Windows or install Linux in another partition or in a virtual machine. I myself used to do that when I had a Windows computer.

**Comment by TylorS** [comment]
I've been using Windows 10 with Ubuntu for Windows, and can confirm that these scripts work there.

**Comment by whitecolor** [comment]
Ok, will use docker, maybe it will be even better.

**Comment by TylorS** [comment]
@whitecolor https://github.com/vdemedes/trevor is a useful tool for using docker for testing

**Comment by whitecolor** [comment]
@TylorS thanks, didn't see it)

**Comment by artfuldev** [comment]
The line number mentioned above has been revised:
https://github.com/cyclejs/cyclejs/blob/master/dom/package.json#L98
