### ISSUE TITLE
Extract `HTMLDriver`

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#385]
Remove exessive and heavy `makeHTMLDriver` dependency from index. Just a reminder as it is still not done.

**Comment by whitecolor** [comment]
@staltz @TylorS 
Do you think it is really needed because in webpack config there is can be workaround using empty loader not to load `makeHTMLDriver` module.

Aslo `mockDOMSource` is not needed in production.

How would you remove it and how it should be imported and used?

**Comment by TylorS** [comment]
In private staltz and I have mentioned wanting to provide ES2015 module builds for tree shaking, so maybe it isn't necessary?

**Comment by whitecolor** [comment]
Well yes for ES2015 builds it will be possible to avoid it due to tree shaking. As a workaround for now as I mentioned one can to use custom empty webpack's loader or browserify's transform to get rid of unnecessary/unused inner module's requires.

**Comment by staltz** [comment]
This is done.
