### ISSUE TITLE
HTTP driver makes lazy (not eager) requests

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#387]
@staltz 
If I am correct HTTP driver only starts making request after (first) subscription to corresponding `response$` stream is made inside the app. Is it desired behaviour? In previous version for requests with `eager` option side effect was performed (started) just after `response$` creation (`response$.connect()` was used). And it seems there was a desire to make it all eager and shared. In current version they became shared but not *eager*.

**Comment by Hypnosphi** [comment]
Doesn't seem to reproduce http://www.webpackbin.com/E1yze-ft-

**Comment by whitecolor** [comment]
Right, my mistake.
