### ISSUE TITLE
Default HTTP params

### ISSUE THREAD

**Issue by Hypnosphi** [cyclejs/cyclejs#390]
It would be nice to have a driver option which would set default options for all the requests. This can also include `urlRoot` option which would be prepended to all relative urls

**Comment by staltz** [comment]
Will make sense to build this for all existing request options, but I'm not favorable of `urlRoot`, as it can be easily built as a http sink post processing inside `main()`, which is where application logic should be.

**Comment by TylorS** [comment]
I see what you mean here, but I'd probably also stick to post processing the sink stream. I've found the following type signature extremely useful recently. This is also the type signature for `isolate`

```haskell
ComponentUtility :: Component -> Component
```

It is general purpose and will always work to augment any component

```js
function addDefautHttpOptions (Component) {
  return function (sources) {
    const sinks = Component(sources)
    const http = component.http.map(request => ({...defaultOptions, ...request}))
    return {...sinks, http }
  }
}

const augment = compose(isolate, addDefaultHttpOptions)
const app = augment(main)

Cycle.run(app, {...})
```

**Comment by whitecolor** [comment]
If we consider that request should can be updated that is ok. RootUrl was an old topic, it is also may also use different superagent plugins like for prefixing URLs https://github.com/johntron/superagent-prefix on driver level.

**Comment by whitecolor** [comment]
The issue stemmed because `lazy` option, I think this option could be a driver scope, because it actually changes the behaviour of the driver (how it handles streams), other request params are more application domain specific and effects `superagent` behaviour.

**Comment by staltz** [comment]
I'm still unsure about this issue, given what Tylor suggested. I'm trying to come up with a good criteria "what should be and what should not be driver options?" for any driver.

**Comment by whitecolor** [comment]
I believe basically in driver options should go everything that configure drivers behaviour but can not be configured from app's standpoint. 

In this case `lazy` param behaviour can be configured in app's logic, that should not go in driver options. 

Though it could, if we assume that it creates another kind of driver, but this is more actual for some more generic solution like `cycle-async-driver` factory.

**Comment by jvanbruegge** [comment]
@staltz should we close this? Wrapping the HTTP driver is the way it is working now

**Comment by staltz** [comment]
Yes, I guess so, it's not looking like this will proceed.
