### ISSUE TITLE
Support for directly updating the DOM

### ISSUE THREAD

**Issue by tusharmath** [cyclejs/cyclejs#391]
Cycle/DOM driver should have the ability to make direct updates to the DOM. This can be really useful when you want to to extremely performance intensive work and by pass the driver's virtual dom's diffing approach.

**Comment by whitecolor** [comment]
If you want to do this declaratively this should be probably in another special "direct-dom-update" driver.

**Comment by tusharmath** [comment]
@whitecolor I am doing that right now but it can't be exported as a standalone driver because it's tightly coupled to Cycle/DOM.

**Comment by whitecolor** [comment]
> It would make more sense for it to be a part of the main driver.

Then you probably can propose a reasonable API for this?

**Comment by tusharmath** [comment]
How about — 

```js
// contains style changes
const style$ = ...
return {DOM: DOM.select('.my-element').update(style$)}
```

**Comment by TylorS** [comment]
You could use https://github.com/TylorS/snabbdom-selector
Its out of date but this is possible in other fashions already, and it will be handled by snabbdom in a way that won't confuse it. @staltz Wants to build an immutable version of the mutable example I'm about to try writing

```js
import select from 'snabbdom-selector' 

const style$ = $.of({ transform: 'translate(50%)' })
const vNode$  = state$.map(view)

function addStyle(style) {
  return function (vNode) {
    if (!vNode.data) vNode.data = {}
    vNode.data.style = style
  }
}

const DOM = combine(style$, vNode$).map(([style, vNode]) => {
  const matches = select('.my-element', vNode)
  matches.forEach(addStyle(style))
  return vNode
})
```

**Comment by TylorS** [comment]
See: https://github.com/cyclejs/cyclejs/issues/352

**Comment by whitecolor** [comment]
I believe modifying vnode in mutable or immutable manner would not increase snabbdom performance. https://github.com/cyclejs/cyclejs/issues/386 would help to deal such small "updates" via snabbdom.

@tusharmath 
And I'm not sure that direct DOM modification should be included in the DOM driver. If you need it just to increase performance you may use shabbdom hooks to directly modify DOM.

**Comment by staltz** [comment]
I don't understand why can't you use snabbdom hooks for this.

**Comment by tusharmath** [comment]
@staltz Shouldn't side effects be outside the `main` function? That way it would be easier to test as well.

**Comment by whitecolor** [comment]
With hooks they are too "outside" of main, they will be executed "inside" the driver realm. If you need it declarative way may do your layer for this.

**Comment by tusharmath** [comment]
@whitecolor can you please provide an example?

**Comment by whitecolor** [comment]
See how snabbdom hooks work. This is a function that will be executed when element is created by snabbdom while performing side effect - so logically it refers to driver responsibility, not your application logic.

**Comment by tusharmath** [comment]
My usecase to to change the element's `transform` property with the `touchmove` event on the screen. I highly doubt that hooks can be of help here.

**Comment by staltz** [comment]
Make a one-line driver like people usually make the preventDefault driver and change the transform property there. I think we could close this issue because there isn't any concrete suggestion here.

**Comment by Widdershin** [comment]
@tusharmath could you share the relevant code sample? Maybe it could be optimized somehow? There are a lot of little tricks for getting more performance out of snabbdom

**Comment by tusharmath** [comment]
This is the gist of my original code, I am trying to drag the `.draggable` element on the UI via the `touchMove` event

```js

function clientX () {/*gets the clientX prop of the touch event */}

const seek$ = clientX(DOM.select('.draggable').events('touchmove'))

return {DOM: view({seek$, $1, $2})} // $1 and $2 are other streams that make up the view using combineLatest()
```

I am using RxJS because even though it's slow it has the best testing capabilities amongst other streams via `VirtualTimeScheduler`.
As you can see here the view is made up of multiple stream, which makes it even slower. Apart from that, calculating virtual dom diffs is again expensive.

My new code looks more like this ([see original](https://github.com/funag/ui-core/blob/master/src/components/scrobber/scrobber.js#L33)) — 


```js

function clientX () {/*gets the clientX prop of the touch event */}

const draggableEL = DOM.select('.draggable')
const seek$ = clientX(draggableEL.events('touchmove'))

return {
  DOM: view({$1, $2}),
  QUICK: seek$.withLatestFrom(draggableEL)  // special driver that can directly update the DOM.
}
```

Even with the second approach the bottle neck had now become RxJS. The last resort that I had was to use webcomponents but it's a different paradigm altogether :(

**Comment by Widdershin** [comment]
@tusharmath try putting a `key` on your `draggable` element.

```jsx
<div key="draggable-marker" className={css(css.scrobberTrack, 'flb row jc_fe', 'draggable-marker')}
style={style({completion, transition})}>
```
`virtualdom`, `snabbdom` and `react` all take a `key` property which is a unique identifier for the element. If omitted, you end up in situations like this where changing a single css property on the element causes it to be removed and a new one added. This is both slow, and breaks CSS transitions. By providing a key, the vdom library can tell when an element is the same element, just changed slightly. Updating is much cheaper than replacing, so it goes a lot faster.

I usually use `node-uuid` to generate my keys, but unique strings will do to start.

**Comment by tusharmath** [comment]
@Widdershin Thanks I will give this approach a shot.
