### ISSUE TITLE
JSX instructions missing "npm install babel-plugin-syntax-jsx"

### ISSUE THREAD

**Issue by abrinsmead** [cyclejs/cyclejs#394]
**Code to reproduce the issue:**
Follow steps to use JSX at http://cycle.js.org/getting-started.html

> The following only works if you are building with Babel: (1) install the npm packages babel-plugin-transform-react-jsx and snabbdom-jsx; (2) specify a pragma for JSX as shown in the following example .babelrc file:
...
> (3) import Snabbdom JSX as import {html} from 'snabbdom-jsx';, and then you can utilize JSX:

**Expected behavior:**
Babel transpiles JSX without error.

**Actual behavior:**
Module build failed: ReferenceError: Unknown plugin "syntax-jsx" specified in "base" at 0

**Solution:**
npm install babel-plugin-syntax-jsx --save-dev

**Versions of packages used:**
    "babel-cli": "^6.11.4",
    "babel-plugin-syntax-jsx": "^6.13.0",
    "babel-plugin-transform-react-jsx": "^6.8.0",
    "babel-preset-es2015": "^6.13.2",
    "snabbdom-jsx": "^0.3.0",
    "webpack": "^1.13.2"

**Comment by staltz** [comment]
@abrinsmead take a look at this example and how it doesn't include `babel-plugin-syntax-jsx` https://github.com/cyclejs/cyclejs/blob/master/examples/jsx-seconds-elapsed/package.json

**Comment by abrinsmead** [comment]
Thanks @staltz. I'll try using the pattern from the demo and see what happens.  I'll also try with just babel, without webpack.
