### ISSUE TITLE
Each official driver should have docs about its isolation semantics

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#395]
See the discussion in https://github.com/cyclejs/cyclejs/issues/369 towards the end.

**Comment by kevinmctigue** [comment]
I guess we'll need a convention for naming isolation levels.

Right now we have just the two, correct? Total isolation, where the source and sink are totally isolated (DOM) and sibling, where parents of an isolated child have access to the child's sinks but the any siblings are isolated from each other.

Any input on names? Sibling and Total? Are there any plans for other types?

**Comment by whitecolor** [comment]
child and orphan =)

**Comment by staltz** [comment]
We're talking sibling-sibling and parent-child isolation. DOM driver has both, and HTTP has only sibling-sibling isolation.

**Comment by staltz** [comment]
This is finally done! :D

**Comment by mightyiam** [comment]
:fireworks:
