### ISSUE TITLE
Snabbdom Dataset Module to Defaults for DOM Driver

### ISSUE THREAD

**Issue by WorldMaker** [cyclejs/cyclejs#396]
In the process of updating a large codebase to latest DOM driver (across the change from VirtualDOM to Snabbdom) and one of the first pain points I bumped into was that my codebase uses data attributes and the `event.target.dataset.someUsefulField` relatively often. It took a bit to realize I needed to both patch `snabbdom-jsx` (because I'm using TSX files for views) and pass to the DOM driver a customized set of modules to include the Snabbdom dataset module. This module is generally useful enough that I think it would be a good one to include in the defaults.

**Comment by Widdershin** [comment]
:+1:, I've been using `div({attrs: {'data-foo': value}})`, I was unaware of the dataset module.

**Comment by Hypnosphi** [comment]
and my way was `{props: {dataset}}`

**Comment by staltz** [comment]
Yes we should do this, specially considering how kb-small the module is.

##### If you want to contribute, this is a fairly easy task.

**Comment by staltz** [comment]
This issue is done in the Cycle Unified branch. Not yet released.
