### ISSUE TITLE
DOM Isolation and Snabbdom Key-based DOM Errors

### ISSUE THREAD

**Issue by WorldMaker** [cyclejs/cyclejs#397]
**Code to reproduce the issue:**

I have several isolated sinks whose contents change entirely based on a set of state machines/loading progress etc. Most importantly the outer-most elements change "selector elements", primarily static classes between states.

**Expected behavior:**

In VirtualDOM this produced the expected changes to the DOM.

**Actual behavior:**

In Snabbdom this was producing a `Failed to execute 'insertBefore'` error. This is the same error as paldepind/snabbdom#110, and seems to be the same issue: the key applied by the DOM driver isolation was impacting the change in "selector elements" (static classes).

**Workaround:**

For now in all the places where I'm isolating DOM views I'm adding in a wrapper DIV (`.map((vnode: any) => h('div', [ vnode ]))`) and that solves the error. Maybe DOM isolateSink needs to use a wrapper node if/when it applies a scope key?

**Versions of packages used:**

```
@cycle/dom: 12.0.3
snabbdom: 0.5.1
```

**Comment by staltz** [comment]
@WorldMaker since you're changing the `sel` (I assume) often, could you instead try using the class module?
```js
div('.neverChangeThis', {
  class: {
    'selectedClass': true,
    'hoverClass': isHovered,
  }
})
```

**Comment by WorldMaker** [comment]
Not in this case because the change was between entirely different view functions that I didn't want to couple. In the easiest example, I have a simple `<div classNames='ui active inline loader />` placeholder view getting swapped for whatever the "real" loaded view might be, which might be a `<p>`, even.
