### ISSUE TITLE
Type check main function and drivers in run()

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#404]
Suggestion from @justinwoo to use tuples (or fixed length arrays) so that run can match driver signatures with main sources/sinks. Example with bmi-typescript:

``` typescript
import xs, {Stream, MemoryStream} from 'xstream';
import {h2, div, VNode} from '@cycle/dom';
import {DOMSource} from '@cycle/dom/xstream-typings';
import isolate from '@cycle/isolate';
import LabeledSlider, {LabeledSliderProps} from './LabeledSlider';

// export type Sources = {
//   DOM: DOMSource,
// };
// export type Sinks = {
//   DOM: Stream<VNode>,
// }

function domDriver(sink: Stream<VNode>): DOMSource {
  return null;
};

run(function (sources) {
  let WeightSlider = isolate(LabeledSlider);
  let HeightSlider = isolate(LabeledSlider);

  let weightProps$ = xs.of<LabeledSliderProps>({
    label: 'Weight', unit: 'kg', min: 40, initial: 70, max: 140
  }).remember();
  let heightProps$ = xs.of<LabeledSliderProps>({
    label: 'Height', unit: 'cm', min: 140, initial: 170, max: 210
  }).remember();

  let weightSlider = WeightSlider({DOM: sources[0], props$: weightProps$});
  let heightSlider = HeightSlider({DOM: sources[0], props$: heightProps$});

  let bmi$ = xs.combine(weightSlider.value$, heightSlider.value$)
    .map(([weight, height]) => {
      let heightMeters = height * 0.01;
      let bmi = Math.round(weight / (heightMeters * heightMeters));
      return bmi;
    }).remember();

  return [
    xs.combine(bmi$, weightSlider.DOM, heightSlider.DOM)
      .map(([bmi, weightVTree, heightVTree]) =>
        div([
          weightVTree,
          heightVTree,
          h2('BMI is ' + bmi)
        ])
      )
  ];
}, [domDriver]);

function run<A1, A2>(main: (sources: [A1]) => [A2], drivers: [(sink: A2) => A1]) {
};
```

This should be a non-breaking change since we can support both objects and arrays.

**Comment by TylorS** [comment]
How about supporting a `Map`? Personally I really like using maps over an object or an array in many cases

**Comment by justinwoo** [comment]
Can maps support this kind of precision that a specific property should
match a specific type?

**Comment by TylorS** [comment]
Hmm, no it can't. Is the plan to override the types for run?
```typescript

type Driver<A,B> = (sink: B) => A
type Main<A, B> = (sources: A) => B

interface RunFn {
  <A, B>(main: Main<[A], [B]>,  drivers: [Driver<A,B>]),
  <A, B, C, D>(main: Main<[A, C], [B, D]>, drivers: [Driver<A, B>, Driver<C, D>])
  <A, B, C, D, E, F>(main: Main<[A, C, E], [B, D, F]>, drivers: [Driver<A, B>, Driver<C, D>, Driver<E, F>])
}
```

So on an so forth?

**Comment by justinwoo** [comment]
Probably easier to identify A1, A2, B1, B2 and so on, but yeah, just like that. The underlying mechanism should probably just translate the array into an object with whatever keys and do the normal run, or however run works normally now.

I don't think we've figured out to do nested components though, but my use for this is just making sure my top level run is correct for the fairly hands-off cycle apps I do personally. I guess this won't really be an issue though if we just merge the child streams into the correct "tuple elements"? Haven't thought about this enough though, what do you think?

**Comment by TylorS** [comment]
> easier to identify A1, A2, B1, B2

Sure, I can agree with that.

> just translate the array into an object

Yeah that's probably easiest.

> I don't think we've figured out to do nested components though

Well that's 100% dependent on the Component, it can have any type signature it'd like, but it reuse the `Main` type I defined above, but maybe it could simply be renamed to `Component` anyways.

```js
export type Component = (sources: A) => B

<Component<[DOMSource], [Stream<VNode>]>> function MyComponent (sources) {
  const [DOM] = sources

  const vNode$ = Stream.of(div('hi'))
  return [vNode$]
}
```

---

With `main` it will be a little weird when you have a driver that is source or sink only. What do you provide then? Same goes for a Component I suppose too

**Comment by justinwoo** [comment]
Yeah, I guess if you have the child component's types as either a "tuple" or a typed record, it shouldn't be much work to just merge them as needed.

**Comment by justinwoo** [comment]
I think #432 done in any kind of fashion makes this one not very important to do

**Comment by staltz** [comment]
Correct.

**Comment by whitecolor** [comment]
For typing nazi the third `Drivers` type could be added for `run` fn:
```ts
function <Sources, Sinks>(main: (sources: Sources) => Sinks,
                            drivers: {[name: string]: Function}): CycleExecution<Sources, Sinks>
function <Sources, Sinks, Drivers>(main: (sources: Sources) => Sinks,
                            drivers: Drivers): CycleExecution<Sources, Sinks>
```
It would be overloaded function defs. So it would allow to type only Sources and Sinks, or Sources and Sinks, with Drivers.

This would be just overloaded function definitions a few lines of code

**Comment by staltz** [comment]
This was mostly done through TypeScript `type` and recently with https://github.com/cyclejs/cyclejs/issues/560, not with tuples as originally thought, though. Check e.g. these tests https://github.com/cyclejs/cyclejs/blob/90e1f5030868bf27083e47249dcad0a271cbbde2/run/test/index.ts#L57-L89

The megadriver idea is a different issue and is mostly working too, so this issue can be closed.
