### ISSUE TITLE
Document that the default export of *-run is a function.

### ISSUE THREAD

**Issue by mrapogee** [cyclejs/cyclejs#405]
This issue isn't a bug, but a confusing behaviour. Even when using typescript, this silently failed and I spent a while looking in my code before I realized that I need to include the member `{run}`,
 not the default.

**Code to reproduce the issue:**
Rather than using `import {run} from 'xstream-run'` use `import run from 'xstream-run'`.

**Expected behavior:**
It shows an error or it starts the drivers

**Actual behavior:**
It displays nothing and doesn't start drivers

Thanks for considering!

**Comment by whitecolor** [comment]
Both options are possible:
````js
import Cycle from 'xstream-run'

// this is if you need to access sinks and sources
let {run, sinks, sources} = Cycle(Main, drivers)
let dispose = run()
````

````js
import {run} from 'xstream-run'

// this more common option
let dispose = run(Main, drivers)
````

**Comment by TylorS** [comment]
@whitecolor Beat me to it. I was just typing it when your answer popped up

**Comment by whitecolor** [comment]
@TylorS 
:smile: you may send you variant

**Comment by TylorS** [comment]
I think this is sort of the expected behavior, but it *should* be documented as only the backwards compatible usage is documented.

**Comment by mrapogee** [comment]
I understand that both are possible, just wondered if there was a way to send a warning. It's a bit confusing when you call run and nothing happens.

**Comment by craigmichaelmartin** [comment]
@TylorS are you saying the current way is more intuitive and so desired? If we `export default run`, and simply `export Cycle`, we could still have both exported, but prioritize `run`. This seems more intuitive to me, given that it is imported from 'xstream-**run**'. That said, it is a breaking change.

**Comment by TylorS** [comment]
`Cycle.run` is merely a more backwards compatible short-cut to the longer way of doing things. Because *most* of the time you don't need access to `sinks` and `sources` returned by `Cycle()`

**Comment by TylorS** [comment]
Sometmes, though it can be useful to have access to those. https://github.com/cyclejs/cyclejs/blob/master/dom/test/browser/events.js#L27

**Comment by craigmichaelmartin** [comment]
For sure; I'm still suggesting exporting both. But switching [which](https://github.com/cyclejs/cyclejs/blob/master/xstream-run/src/index.ts#L36) [one](https://github.com/cyclejs/cyclejs/blob/master/xstream-run/src/index.ts#L85) is the default.

**Comment by Widdershin** [comment]
@craigmichaelmartin I think there is a tradeoff here.

I agree that switching the default would be less confusing for new users, and potentially cuts out a class of errors.

On the other hand, Tylor's point about backwards compatibility is important. Breaking `import {run} from '@cycle/xstream-run'` would require all existing Cycle apps to change when they update.

A potential compromise exists:

Currently:
```js
{
  default: asyncRun,
  run: syncRun
}
```

Could be:
```js
{
   default: syncRun,
   run: syncRun,
   Cycle: asyncRun
}
```

This would still be a breaking change:
```js
import Cycle from '@cycle/xstream-run'
//becomes
import {Cycle} from '@cycle/xstream-run'
```

However, my guess is that this would impact far fewer users. It would also throw a runtime error if you didn't update, unlike the current silent failure that exists.

All that said, I'm still not sure the breaking change is worth it.

**Comment by whitecolor** [comment]
Such introduces additional semantics `Cycle`
```js
import {Cycle} from '@cycle/xstream-run'
```

In my view current state is quite good one, only `run` semantics inside, you may cal default import whatever you like. Maybe it should be stated in docs more clearly.

**Comment by staltz** [comment]
This is already clearly documented in the README for each `@cycle/____-run`, and also in many examples.

The current API is consistent with
`import CycleDOM from '@cycle/dom'`
with destructuring:
`const {div, button, makeDOMDriver} = CycleDOM;`
or just
`import {div, button, makeDOMDriver} from '@cycle/dom';`

Or with the HTTP package:
`import {makeHTTPDriver} from '@cycle/dom'`

So that's why with Cycle run we have
`import Cycle from '@cycle/xstream-run'`
and with destructuring:
`const {run} = Cycle`

Or just
`import {run} from '@cycle/xstream-run';`

The breaking change is not worth it, it would impact many people's code, and probably make it less intuitive for them. I also don't see what else we could do with docs.

**Comment by staltz** [comment]
Also, with TypeScript, you can inspect in your editor what is the type of `var y = run(main,drivers);`. If `y` is CycleExecution, you could inspect what does that contain, and see that it has `run`.

**Comment by craigmichaelmartin** [comment]
> The breaking change is not worth it, it would impact many people's code, and probably make it less intuitive for them.

I definitely understand not wanting to force a breaking change for something semantic like this. That said, it could be as part of the next major release. 

As a new user to cycle, api consistency is less important than api clarity. I don't follow the logic that importing from `xstream-run` and receiving a CycleSetup is more intuitive than receiving a run function. Maybe someday after working with the library more I'll see it, or after using more packages I'll appreciate the consistency.

> I also don't see what else we could do with docs.

Should `help wanted` be removed and the issue closed then? If not, it is not clear to me what contribution is being sought.

**Comment by staltz** [comment]
Ok, let's see if other people experience similar stuff in the future.

**Comment by staltz** [comment]
We're doing this feature now together with Cycle Unified #425, so that:

`import run from '@cycle/run'` works
`import {run} from '@cycle/run'` works
`import {setup} from '@cycle/run'` works

But

`import Cycle from '@cycle/xstream-run'` no longer supported
