### ISSUE TITLE
make type definitions of DOMSource generic

### ISSUE THREAD

**Issue by maiermic** [cyclejs/cyclejs#408]
This issue is a suggestion how to improve the type definition of DOMSource. I will refer to [xstream-typings.d.ts][xstream-typings.d.ts], but the same can be applied to the other stream adapters ([most-typings.d.ts](https://github.com/cyclejs/cyclejs/blob/master/dom/most-typings.d.ts), [rx-typings.d.ts](https://github.com/cyclejs/cyclejs/blob/master/dom/rx-typings.d.ts), [rxjs-typings.d.ts](https://github.com/cyclejs/cyclejs/blob/master/dom/rxjs-typings.d.ts)).

`DOMSource` of [xstream-typings.d.ts][xstream-typings.d.ts] looks like this at the moment:

```ts
import {EventsFnOptions} from './lib/DOMSource';
import {Stream, MemoryStream} from 'xstream';
export interface DOMSource {
  select(selector: string): DOMSource;
  elements(): MemoryStream<Element>;
  events(eventType: string, options?: EventsFnOptions): Stream<Event>;
}
```

Let's take a look at this code example:

```ts
DOMSource.select('a').events('click') // returns `Stream<Event>`
  .map(event =>  event.target.hash.replace('#', ''))
```

**Note:** This code is part of [my port](https://github.com/maiermic/todomvc-cycle-typescript) of [todomvc-cycle](https://github.com/cyclejs/todomvc-cycle) to TypeScript (see [TaskList/intent](https://github.com/maiermic/todomvc-cycle-typescript/blob/master/src/components/TaskList/intent.ts#L35)). I got an error because `event.target` is of type [`EventTarget`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L7888) which has no property `hash`. However, the compiler could know that it exists if type definitions are improved.

`select` and `events` act as filter. After the call `DOMSource.select('a')` you know that events happen on a `HTMLAnchorElement`. After the call `events('click')` you further know that the event is a `MouseEvent`. Taken together, you know that `event` in our example is a `MouseEvent` with a `HTMLAnchorElement` as `target`.

That's why I used the following type definitions in [my project](https://github.com/maiermic/todomvc-cycle-typescript):

```ts
import {EventsFnOptions} from './lib/DOMSource';
import {Stream, MemoryStream} from 'xstream';

export interface EventWithTarget<T> extends Event {
  target: EventTarget & T
}

type EventStream<Target, E extends Event>
  = Stream<EventWithTarget<Target> & E>

export interface DOMSource<T> {
  select(selector: 'a'): DOMSource<HTMLAnchorElement>;
  select(selector: 'input'): DOMSource<HTMLInputElement>;
  select(selector: string): DOMSource<any>;

  elements(): MemoryStream<Element>;

  events(eventType: 'keydown' | 'keyup', options?: EventsFnOptions): EventStream<T, KeyboardEvent>
  events(eventType: 'click', options?: EventsFnOptions): EventStream<T, MouseEvent>
  events(eventType: string, options?: EventsFnOptions): Stream<Event>;
}
```

**Note:** The overloaded function signatures are not complete yet. There are more `selector`s and `eventType`s that can be added in a similar way. If you accept my idea, I will create a pull request with the missing signatures.

The only downside I noticed is that you have to write `DOMSource<any>` of `DOMSource<MyType>` instead of `DOMSource`. However, I can live with that. What do you think?

[xstream-typings.d.ts]: https://github.com/cyclejs/cyclejs/blob/master/dom/xstream-typings.d.ts

**Comment by whitecolor** [comment]
I think for events it would work fine, for the elements I'm not sure about elements selectors as too limited for simple selectors (I would be more reasonable if TS will support tagging with regexp)

I don't why you need generic <T> for whole DOMsource, what is T actually?

**Comment by maiermic** [comment]
`T` is the target of the event.

`DOMSource.select('a')` returns `DOMSource<HTMLAnchorElement>` (here `T` is `HTMLAnchorElement`). If you call `events` on it, you get an event target of type `HTMLAnchorElement`.

Without generic type signature, you have to cast

```ts
DOMSource.select('a').events('click')
  .map(event =>  (event.target as HTMLAnchorElement).hash.replace('#', ''))
```

which is verbose and error prone, since you have to remember to change the cast if you change the selector `'a'` to something else.

> it would be more reasonable if/when TS will support tagging with regexp

I don't think this will ever happen. Do you know any language or type system that supports something complex like this? There might be another solution, but that is pure speculation on my part.

My solution is helpful in common usage (see [todomvc-cycle-typescript](https://github.com/maiermic/todomvc-cycle-typescript)). Without it you need type casts in most cases where you use `@cycle/dom`.

**Comment by whitecolor** [comment]
> I don't think this will ever happen
https://github.com/Microsoft/TypeScript/issues/6579

**Comment by staltz** [comment]
I like the purpose of this issue, it didn't occur to me we could be doing this. However, it wouldn't be that useful (enough to justify a minor change in the API) because I think in most cases people shouldn't be selecting only with tagName, but specially with the classname.

I would write `domSource.select('a.link')` not `domSource.select('a')`. Also, I would recommend `domSource.select('input').events('input')` not `domSource.select('input')`. It would indeed be feasible if TypeScript supported regex string types.

**Comment by maiermic** [comment]
You could write `domSource.select('.link').select('a')` instead of `domSource.select('a.link')` to get type safety again but I admit that this is a discussable workaround. I prefer it since it avoids casting.

After all, I can use my type definitions as a custom/alternative xstream adapter type definition file that I import instead of `@cycle/dom/xstream-typings`. Where is the best place to share it with other people?

By the way, why is [xstream-typings.d.ts](https://github.com/cyclejs/cyclejs/blob/master/dom/xstream-typings.d.ts) part of `@cycle/dom` and not part of `@cycle/xstream-adapter` or `@cycle/xstream-run`. I think that would be more logical. For example `@cycle/xstream-adapter/DOMSource`.

**Comment by whitecolor** [comment]
> By the way, why is xstream-typings.d.ts part of @cycle/dom

Because this typings are specific for for DOMDriver

**Comment by whitecolor** [comment]
Potentially `select` could have a second string parameter to point to the type of the element selecting.

> By the way, why is xstream-typings.d.ts part of @cycle/dom

Because those typings are specific for DOMDriver

**Comment by staltz** [comment]
> After all, I can use my type definitions as a custom/alternative xstream adapter type definition file that I import instead of @cycle/dom/xstream-typings. Where is the best place to share it with other people?

@maiermic I think that would be a good temporary solution. If we are not sure about adding something, we keep it as an external library, let it stabilize for a while, then include that. That's the approach I'm taking with #407, even if I'm the main author of Cycle.js.

You can publish the .d.ts typings as an npm package and instruct people to install through `typings` tool.

- - -

@whitecolor Those are decent ideas, but we could also try experimenting with it before putting in Cycle DOM. One concern I have is that those APIs wouldn't make sense for JavaScript users.

**Comment by whitecolor** [comment]
> One concern I have is that those APIs wouldn't make sense for JavaScript users.

They eventually will become ts user, whether they want it or not -) Without types cycle is much harder as any functional approach.

**Comment by maiermic** [comment]
> Because those typings are specific for DOMDriver

`DOMSource` depends on the used adapter even though those typings are specific for DOMDriver. If the adapter changes its interface, because the underlying library does (for example RxJS decides to rename `Observable` to `Stream` in a new version), you have to change the related typings in DOMDriver although the driver itself didn't change. Further, you have to maintain two different versions/files (old and new RxJS API) in the DOMDriver. The user has to know that there are two files and which to import. A breaking change in the underlying library might cause a change of the adapter, but it shouldn't be necessary to change DOMDriver. DOMDriver doesn't know the specific interface of `DOMSource`, but only the adapter does.

On the other hand, if the typings are part of the adapter, you import the `DOMSource` typings file of the adapter you use. If you update the underlying library it is required to update the related adapter. That would be the same case at the moment, but you would also have to change import paths of `DOMSource` (to the other typings version/file in DOMDriver), which isn't the case if you import `DOMSource` from the adapter, because they are updated with the package of the adapter.

Another argument is that someone creates an adapter for another library that is not supported yet. Accordingly, he has to provide related typings of `DOMSource`. Where should he provide them? If he provides them in his adapter package then the location differs from the usual location (DOMDriver package). If he likes to provide his typings in this usual location then he has to ask for contribution to the DOMDriver. This wouldn't be the case if the standard location is the adapter package. I admit that this argument is somehow feeble. Nevertheless, this structure seems more logical to me.

**Comment by whitecolor** [comment]
@maiermic

I see you point. But how those typings should be implemented? 

I see it this way: adapters should also provide `Stream` and `MemoryStream` types.

Instead of 
```js
import {DOMSource} from '@cycle/dom/xstream-typings'
```
You could do:
```js
import {DOMSource} from '@cycle/dom' // generic source take adapter type param
import xsAdapter from '@cycle/xstream-adapter'
let XsDOMSource = DOMSource<xsAdapter>
```
of course it could placed in `@cycle/dom/xstream-typings.d.ts` to have specific typings available.

What do you propose?

**Comment by staltz** [comment]
`DOMSource` depends on the used stream library, not the adapter for that stream library.

We have to admit the xstream DOMSource typings are inherently related to **both** xstream and DOM Driver, and a breaking change in either one of these would mean a breaking change to the package containing the xstream-DOMSource typings. The alternative to avoid that would be publish those typings as a completely separate library. But we chose the DOM package because the xstream-DOMSource *would* have been independent to the stream library (meaning no rxjs-typings.d.ts no xstream-typings.d.ts) *if* TypeScript supported higher-order generics or something like that.

@whitecolor About your most recent idea, we tried that as much as we could, and I think we really hit a limitation with TypeScript in this case. If any one can hack around the type system so that users can get DOMSource typed for the stream library without any `@cycle/dom/xstream-typings.d.ts` or similar, that would be awesome. Try doing the `DOMSource<xsAdapter>` approach in practice, and you'll see the issues I'm talking about.

**Comment by whitecolor** [comment]
@staltz 
I see nothing wrong with importing typings and even whole `makeDomDriver` from specific stream lib sub-module:

```js
import {DOMSource, makeDOMDriver} from '@cycle/dom/xstream'
// import {DOMSource, makeDOMDriver} from '@cycle/dom/rx'
// etc

// this `makeDOMDriver` version would produce correct DOMSource with proper stream lib typings

// DOMSource has xstream dom typings
```

**Comment by staltz** [comment]
How is that an improvement over what we currently do?

**Comment by whitecolor** [comment]
Well actually it allow nothing more than current situation, just a little bit different API for importing things.

Well and yes you with `import {makeDOMDriver} from '@cycle/dom/xstream'` you get correct typings of the resulting source which is not big deal because those types still won't flow any where.

I just do it this way currenlty in drivers I create.

I not sure if @maiermic want to propose something more.

**Comment by maiermic** [comment]
I realized that I laboured under the misapprehension that adapters are only used with the DOMDriver

![ashamed](http://cdn.thedailybeast.com/content/dailybeast/galleries/2013/05/16/george-takei-s-nine-favorite-star-trek-memes/jcr:content/gallery/fdd49858-ed35-4e66-b83e-6bb4c07af2d9/image.img.1280.1024.jpg/45624913.cached.jpg)

What a fail of mine :sweat_smile: I'm sorry, I take it back. `DOMSource` typings shouldn't be part of the adapter and I'm fine with DOMDriver as location.

A generic solution of `DOMSource` for different adapters could look like this

**@cycle/dom/GenericDOMSource.ts**

```ts
export default interface GenericDOMSource<ElementStream, EventStream> {
  select(selector: string): GenericDOMSource<ElementStream, EventStream>;
  elements(): ElementStream<Element>;
  events(eventType: string, options?: EventsFnOptions): EventStream<Event>;
}
```

**@cycle/dom/xstream-typings.d.ts**

```ts
import GenericDOMSource from './GenericDOMSource';
import {Stream, MemoryStream} from 'xstream';

export type DOMSource = GenericDOMSource<MemoryStream, Stream>
```

**@cycle/dom/most-typings.d.ts**

```ts
import GenericDOMSource from './GenericDOMSource';
import {Stream} from 'most';

export type DOMSource = GenericDOMSource<Stream, Stream>
```

**@cycle/dom/rx-typings.d.ts**

```ts
import GenericDOMSource from './GenericDOMSource';
import {Observable} from 'rx';

export type DOMSource = GenericDOMSource<Observable, Observable>
```

However, I don't like this solution. I would prefer code generation of this interface to hide generic complexity. This would lead to the same situation (multiple typing files) at the moment.

Future TypeScript features might add other possibilities. If [type providers](https://github.com/Microsoft/TypeScript/issues/3136) will be implemented, we might be able to write `DOMSource<'xstream'>`.

**Comment by whitecolor** [comment]
> export type DOMSource = GenericDOMSource<Observable, Observable>

Doesn't bring anything.

> we might be able to write DOMSource<'xstream'>

As I've said it could be done more eleganlty with just adapter: DOMSource<xsAdapter>, if adpaters API would provide `Stream` and `MemoryStream`.

**Comment by maiermic** [comment]
Your suggestion is `DOMSource<xsAdapter>`. How does the definition of `DOMSource` look like in this case?

**Comment by whitecolor** [comment]
```js
export interface DOMSource<adapter> {
  select(selector: string): DOMSource<adapter>;
  elements(): adapter.MemoryStream<Element>;
  events(eventType: string, options?: EventsFnOptions): adapter.Stream<Event>;
}
```

**Comment by staltz** [comment]
@whitecolor That doesn't work in TypeScript.

**Comment by whitecolor** [comment]
Ah, ok, then this option:
```
export default interface GenericDOMSource<ElementStream, EventStream> {
  select(selector: string): GenericDOMSource<ElementStream, EventStream>;
  elements(): ElementStream<Element>;
  events(eventType: string, options?: EventsFnOptions): EventStream<Event>;
}
```
would be ok, though not seeing much need in it.

**Comment by staltz** [comment]
@whitecolor That doesn't work either. We can't have generic-of-generic in TypeScript.

**Comment by whitecolor** [comment]
Then we would have to provide 
```js
import GenericDOMSource from './GenericDOMSource';
import {Stream} from 'most';

export type DOMSource = GenericDOMSource<Stream<Element>, Stream<Event>>
```
Though not very pleasant but will work)

**Comment by staltz** [comment]
`GenericDOMSource<Stream<Element>, Stream<Event>>` is basically the same thing as casting to `Stream<Event>` (from the perspective of work that the user-developer needs to do).

**Comment by whitecolor** [comment]
Kind of that, that only case it would be useful if source would have big definition (for example kind of overloaded interfaces) and such generic would simplify creation of specific lib interfaces, but as interfaces are simple, developer can just created it own custom version if really needed.

**Comment by staltz** [comment]
Let's close this issue since it doesn't look like it will be good enough return-on-investment, and even reliably doable with TypeScript and its limitations.
