### ISSUE TITLE
Isolated DOM stops receiving events after parent element replaced

### ISSUE THREAD

**Issue by chromakode** [cyclejs/cyclejs#409]
Hi!

**Code to reproduce the issue:**

Unfortunately I wasn't able to get webpackbin to load the latest version of `@cycle/dom` (kept hanging on downloading deps), so here's an old fashioned repo with a demo: https://github.com/chromakode/cyclejs-dom-isolate-repro

In this example, an isolated component is being inserted into a parent node with a changing key. When that parent node's key changes, the element's content is re-rendered. The isolated component stops receiving events after this occurs.

**Expected behavior:**

Clicking the first button should increment the count once per click.

**Actual behavior:**

The count only goes up to 2, after which click events are ignored.

**Comments**

I believe the issue lies in the behavior of `isolateModule`'s `destroy` hook:

https://github.com/cyclejs/cyclejs/blob/0126d2ee917d15d8e42b799b369944d1985e19b4/dom/src/isolateModule.ts#L103

In the debugger, I've observed that when the parent element is recreated, we first see the `create` hook run with the new element, and then `destroy` is called on the old one. This causes the `eventDelegators` list to be emptied, even though we just added a new valid element to it.

I believe we could fix this by filtering the `eventDelegators` list so we only clear out delegators associated with the removed element. We should probably do this for both the `destroy` and `remove` hooks. I'd be happy to write a PR for this if it's on the right track.

Thanks! :)

**Versions of packages used:**

```
  "dependencies": {
    "@cycle/dom": "^12.2.2",
    "@cycle/isolate": "^1.4.0",
    "@cycle/xstream-run": "^3.1.0",
    "snabbdom-jsx": "^0.3.1",
    "snabbdom": "chromakode/snabbdom#fix-attribute-removal",
    "xstream": "^6.2.0"
  },
  "devDependencies": {
    "babel-core": "^6.9.1",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-plugin-transform-react-jsx": "^6.8.0",
    "webpack": "^2.1.0-beta.20",
    "webpack-dev-server": "^2.1.0-beta.0"
  }
}
```

**Comment by Hypnosphi** [comment]
What's the point of changing the key when the element stays semantically the same?

**Comment by chromakode** [comment]
This is a bit of a contrived example. :smile:

There are cases in which you explicitly don't want DOM nodes reused when rendering a view. For instance, I was rendering slides in a presentation, and didn't want image tags to carry over slide transitions (causing a flash of the previous slide's image as the src prop changed).

**Comment by Hypnosphi** [comment]
Ok, but you do reuse the controls, so maybe they shouldn't be children of the slide element?

**Comment by chromakode** [comment]
That is actually precisely [the workaround](https://github.com/chromakode/bicyclejs-talk/blob/07479fe3acfd722c930229d62ecadfa7ad3cdce3/src/main.js#L211) I hacked in when I hit this bug. Let's not focus too much on the test-case though. The expectation is that we continue receiving events from a node regardless of what happens to its parent element in the dom-diff update.

**Comment by staltz** [comment]
Thanks @chromakode for reporting. 

We would be glad to receive a PR as you suggested.

Ping @TylorS JFYI

**Comment by chromakode** [comment]
Sounds good, I'll whip this up tonight if I have time.

**Comment by TylorS** [comment]
IsolateModule and it's never ending edge cases :)
