### ISSUE TITLE
Using elements() function on DOM calls querySelector too often

### ISSUE THREAD

**Issue by tusharmath** [cyclejs/cyclejs#410]
`element.querySelector` gets called multiple times on every dom change event, from here — https://github.com/cyclejs/cyclejs/blob/master/dom/src/ElementFinder.ts#L44

**Code to reproduce the issue:**

``` js
const input = DOM.select('input').elements()
  .tap(x => console.log(x)) // prints on every touchmove event

return {DOM: DOM.select(':root').events('touchmove').withLatestFrom(input).map(h('div'))}
```

**Expected behavior:**
`elements()` should fire only when the DOM element has actually changed.

**Actual behavior:**
`elements()` keeps firing unnecessarily even when no change has been made to that part of the DOM.

**Versions of packages used:**

``` json
"@cycle/core": "^7.0.0",
"@cycle/dom": "^12.0.3",
```

**Comment by tusharmath** [comment]
I think the solution would be to use snabbdom hooks instead of query selector?

**Comment by staltz** [comment]
Raised the priority of this issue.

**Comment by staltz** [comment]
I think this is a sub-issue of issue #699. When that one is resolved we should test if this issue happens, and close if this issue is resolved.

**Comment by jvanbruegge** [comment]
This is done in `@cycle/dom` v21
