### ISSUE TITLE
Mutation of original request object in isolate

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#415]
Currently isolation of http driver mutates original request object 
https://github.com/cyclejs/cyclejs/blob/master/http/src/isolate.ts#L20

Don't you think that it should be avoided and new object created instead in isolate? Though it is not clear what to do it request object is not a plain object but for example immutablejs.

**Comment by whitecolor** [comment]
Btw in HTTP driver https://github.com/cyclejs/cyclejs/blob/master/http/src/http-driver.ts#L15 there some other mutations of original object, that probably should be avoided.

**Comment by staltz** [comment]
I don't think mutation is a problem **if** it doesn't express itself as a bug in applications. Actually there are many cases where it's more performant to use mutations. Generally, Cycle.js is written internally with OOP classes and mutation, but Cycle.js is *used* with only functions and immutability.
