### ISSUE TITLE
Swapping VNodes doesn't update children

### ISSUE THREAD

**Issue by SuperManitu** [cyclejs/cyclejs#416]
I'm not entirely sure with this one:
I'm taking a stream of a VNode (a subtree) and swap two of its children.
The children swap as expected (in the actual dom), but their children are not swapped. (They are correct in the vnode i give to the dom driver). I clone the object via Object.assign and construct a completely new child array, so the references are not equal.
Is this intended behavior and if so what should I do to change the behavior, or is this a bug in the vdom that optimizes over-agressivly?

**Code to reproduce the issue:**
Will follow

**Expected behavior:**
children of swapped children change positions in dom

**Actual behavior:**
the vdom modifies the parent attributes, so they seem to swap, but their children are not moved

**Versions of packages used:**
The newest versions of xstream, xstream-run and dom

**Comment by staltz** [comment]
Required follow up question: are you using `key` on each vnode?

**Comment by SuperManitu** [comment]
No, is it needed to distingush nodes? I thought the algorithm would use a simple equality check.

**Comment by staltz** [comment]
There's no way the virtual DOM can disambiguate whether you want to just change the attributes of the two or if you want to swap the two. Unless with keys.

**Comment by SuperManitu** [comment]
Ok, thanks, is this documented? I read the interfaces.ts file and a little comment there would be helpful.
Should I open a PR?

**Comment by staltz** [comment]
It's documented in snabbdom and also in React (keys are a known mechanism in all these virtual DOM libraries).
