### ISSUE TITLE
Creating loosely coupled components

### ISSUE THREAD

**Issue by domagojk** [cyclejs/cyclejs#417]
I wanted to create an application using multiple components, but not in a parent-child relationship with one root function. I ended up creating a ["grid" driver](https://github.com/domagojk/cycle-grid-driver) and I also wrote a [blog post](https://medium.com/@domagojk/creating-a-scalable-javascript-application-with-cycle-js-589f4d4020a5#.v8a7zr585) about it, explaining the concept in more detail.
So I would appreciate any feedback on this... Is this something that should not be done in cycle or would this be a good concept for creating large-scale apps?

Edit:
To clarify: a component in this case is a main cycle function and I am proposing an app composed of "multiple cycles" which is primarily designed for large-scale apps.

**Comment by whitecolor** [comment]
Seems like a kind of solution for dealing with stream circular dependencies. Kind of complicated one.

**Comment by domagojk** [comment]
@whitecolor I don't see how is this related with stream circular dependencies, can you elaborate on that? 
This concept is actually inspired with cycle-http-driver where http responses from multiple components are connected in one stream and received as a source and then you filter what you need. The same principle is used in grid-driver but instead of making http requests component is in charge of what is sent to the main stream.

**Comment by whitecolor** [comment]
No need in driver for this, driver is something that produces side effects, changes in the outer world.

**Comment by domagojk** [comment]
@whitecolor driver produces changes in the outer world of a main component. If you design your application with multiple independent components, then other components would indeed be in the "outer world" and that is the whole point.
If as you say there is no need for driver to accomplish this, how to implement it otherwise?

**Comment by eshansingh** [comment]
@domagojk No. The external world is outside of your app. The components are part of your app. Therefore, don't use a driver here.

**Comment by domagojk** [comment]
@whitecolor and what should I use? To me its either this or connecting them inside one root component creating parent-child relationships.

**Comment by whitecolor** [comment]
Use `imitate` inside your main, like you do inside your driver.

**Comment by domagojk** [comment]
@whitecolor and then you create parent-child relationships in your components. My question is how to not do that?

**Comment by whitecolor** [comment]
I don't understand what you are talking about. It is better to show the code: snippet that shows the problem, snippet that solves it.

**Comment by eshansingh** [comment]
@domagojk They are, after all a parent and a child. As @whitecolor suggested please show the code where this kind of coupling is problematic.

**Comment by domagojk** [comment]
@whitecolor @eshansingh I wrote a blog post about it (linked in original question) but I will create an example for it as well. It should be done soon.

**Comment by whitecolor** [comment]
> I wrote a blog post about it

Just show the code)

**Comment by geovanisouza92** [comment]
@domagojk Take a look at https://github.com/staltz/elementify. That @staltz's experiment makes possible to turn a `Component` in a `<component />` custom element, that could be used on vtree's creation, without one component makes a direct reference to other.

But, if the child component need some source/stream for the parent, or vice versa, you cannot get rid off the direct instantiation inside components. The only way is through Web Components (that elementify's all about) attributes and events.

**Comment by eshansingh** [comment]
@geovanisouza92 Or, just don't worry about streams if it fits your use case, and just make a normal function that returns a vdom tree.

**Comment by domagojk** [comment]
Using driver or not, it seems to me I didn't made myself clear on why would I use multiple main functions. So, to anyone who is interested, I've updated my [post](https://medium.com/@domagojk/creating-a-scalable-javascript-application-with-cycle-js-589f4d4020a5#.v8a7zr585) with section "Why would you do that?" but bear in mind that this is primarily designed for creating large-scale applications.

**Comment by whitecolor** [comment]
@domagojk For decoupling I would advice to use type system that allows have strictly defined interfaces for your components. And in general using cyclejs without type system is hard and probably impossible for a large scale.

**Comment by domagojk** [comment]
@whitecolor I agree that having interfaces would only help in creating a large scale app.
But, interfaces are not used for decoupling. Even though they provide strictly defined requirements on how to create an component, component would still depend on other components sinks and for all the new features every developer in a team still needs to change that main function.

**Comment by whitecolor** [comment]
If you really want decoupling you may want to use separate cycles with main running nearby and communicating via some driver, maybe alike yours one. But build communications inside one Main function using driver just not needed. Drivers are for side effects and making change in the external world, or getting signals from external world, not from internal components.

**Comment by domagojk** [comment]
@whitecolor 

> If you really want decoupling you may want to use separate cycles with main running nearby and communicating via some driver, maybe alike yours one.

That is exactly what I did. The reason I opened a discussion on this is because I didn't found any cycle example where app is separated in multiple main functions which are communicating in this way.

> But build communications inside one Main function using driver just not needed. Drivers are for side effects and making change in the external world, or getting signals from external world, not from internal components.

It was never my intention to use this driver from internal components, only with separate cycles inside a main function.

**Comment by whitecolor** [comment]
@domagojk ok, then this ok, if you mean that, you just needed to state main points in the OP, not send to blog post. And your code example in https://github.com/domagojk/cycle-grid-driver do not contain multiple main functions which supposed to communicate via driver, so your intention is really not clear.

**Comment by domagojk** [comment]
@whitecolor Perhaps all the confusion and the reason why you thought I am using this for communication inside one main function is because I am calling this main cycle function - a component.
I didn't found any other terminology for it besides maybe "Cycle app". But since my app is actually composed of multiple cycles, it was awkward to me to state that an app is composed of apps. 

But you are right, I will edit my main post to clarify it.

I'm not sure on what example you are referring to? There are two snippets - each one is a main cycle function where the sink is something that goes in the grid.

**Comment by whitecolor** [comment]
What I want to say that It not clear from the first glance what is the purpose of your module.
One phrase on the top:

> This stuff is for communication of multiple cyclejs Main functions bla bla

```js
HTTP: makeGridDriver() //-> grid: makeGridDriver()
```

**Comment by domagojk** [comment]
@whitecolor Ok I see, thank you.

**Comment by staltz** [comment]
I can see the idea of this approach, but there will always be "a parent". With the "grid driver", it's the parent of those cycle main functions. Since it's not a true driver in the sense of side effects, you could have put the Cycle sub apps in a... well... main function. :)

Maybe the point here is that your library is useful, but it doesn't need to be a *driver*. There are so many other opportunities to make e.g. factory functions that return a "main" function. This hasn't been explored, but it's something I do sometimes, and Tylor too.

All in all, cool stuff.

**Comment by domagojk** [comment]
@staltz I'm not actually insisting this library should be a driver. Clearly, it shouldn't. But I'm glad you find it useful. My main goal for this discussion was to find out weather this kind of approach could be a good concept for creating scalable and flexible (easily replaceable etc) components. 

But since there are no complaints on the concept itself (for now) I will keep exploring this, and first reimplement it to be a utility function instead :)

**Comment by staltz** [comment]
Cool :) Looking forward to hear more about it

**Comment by geovanisouza92** [comment]
What about Dependency Injection?

**Comment by lidorcg** [comment]
Actually from my experience with this idea so far it looks, to me, very much like dependency injection:
You would declare your needs (as some kind of named/tagged/labelled stream) and know (in your heart ;) that some other component will provide those needs (as the same named/tagged/labelled stream) to the grid.
All you need to define is the streams tags (your interface), and when you replace one, you wont need to touch the code of the others (unlike parent/child import/export relations) just make sure your new component fill its part of the contract.
I've experimented with this idea before, in elm, but lacked the reactive paradigm cycle offers.
