### ISSUE TITLE
Rename interfaces in HTTP driver

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#422]
If one wants to use general interfaces from HTTP driver he would have to do:
```js
import {HTTPSource} from '@cycle/http/xstream-typings'
import {Response, RequestInput, RequestOptions} from '@cycle/http'
```
`HTTPSource` is ok, but importing and using generic names may not clear in the apps code.

One could make of course, but it is a kind of not user-oriented:
```js
import {Response as HTTPResponse} ...
```

So I propose to rename those interfaces:
- Response -> HTTPResponse
- RequestInput -> HTTPRequestInput (HTTPInput?)
- RequestOptions -> HTTPRequest (HTTPOptions?)

**Comment by staltz** [comment]
The renaming would be a breaking change, and it's not worth it to force people to migrate if it's just a cosmetic rename. As you said, the import trick is enough.

**Comment by whitecolor** [comment]
@staltz 
I think if it is consistent it would make sense, and for other drivers typings it should set a kind of standard not make them conflict. Why `HTTPSource` and not `HTTPResponse`?
