### ISSUE TITLE
Designing collections in xstream vs other stream libs

### ISSUE THREAD

**Issue by ntilwalli** [cyclejs/cyclejs#427]
This is more of a broad question for the community to clarify my understanding... 

It seems to me that the architecture you can use for designing collections is more limited if you don't use xstream, i.e. if you use Rx4, Rx5, or most.  With xstream, you have the flexibility to hold component state within the component itself since `map(() => combine(...collectionDOMs))` + `flatten` will never cause the number of subscribers on any of the DOMs in the collection to drop to zero (due to the novel way in which `flatten` is implemented in xstream), ensuring the state associated with those components never gets reset.  In non-xstream libs, the equivalent of the above will cause each of the DOM streams in the collection to drop to zero subscribers temporarily causing them to reset.  My impression is, there is no way to avoid this without hacks or manually managing subscriptions.

For non-xstream libs, engineering around this seems to require moving child component state into the parent and then injecting it into each collection component the way it's done in TodoMVC, where each Todo item doesn't actually store any state, and is just a facade for collecting interaction messages which then get fed back to the parent circularly.  

(Another approach would be to use Stanga which bypasses this issue entirely, but I'd like to put that discussion aside for now...)

Is my understanding correct?  Does xstream's `flatten` approach enable building proper components for collections in a way the other stream libs don't?

**Comment by whitecolor** [comment]
> With xstream, you have the flexibility to hold component state within the component itself  since map(() => combine(...collectionDOMs)) + flatten

Why do you want to flatten `combine(...collectionDOMs))`, are `collectionDOMs` streams contain other streams?

**Comment by staltz** [comment]
`flatten`'s and sync-start/async-stop unique feature was built precisely to make building collections in Cycle.js easier. So...

> It seems to me that the architecture you can use for designing collections is more limited if you don't use xstream, i.e. if you use Rx4, Rx5, or most.

It's true, but with Rx and others, you need to architect it in a different way that you would with xstream. One way I did it in the past is to `publish()` the inner streams, then `connect()` them. So they basically never stop because they don't use refCount. And that's by default a bad idea. But not always. Just, "by default" a bad idea.

Currently, for handling lists of stuff, the main discussion is over here: https://github.com/cyclejs/cyclejs/issues/312

I'm currently betting on the use of Web Components whenever we need lists of stuff, for programmer convenience. It works for most cases, except those cases where each item in the list really really should take care of its own HTTP effects or anything else not DOM-related. Nick's Collection library is also looking good and evolving.

**Comment by whitecolor** [comment]
Actually I don't see a big difference between xstream and other here, with xstream you have a nice `imitate`, in other you should use another proxying technique to achieve circular deps. 

@ntilwalli Without actual code it is all speculations. If you could show the code with the problem it would be easier to articulate on the topic.

**Comment by ntilwalli** [comment]
@whitecolor This issue came up because I was working with @wizardwerdna trying to fix an issue he was having on the app he's building using Rx5:  http://github.com/wizardwerdna/FRPBowlingKata

In the app he has an input to allow new components to be added to his collection.  This "add" component sits at the parent level.  The component is added by pushing it onto an array in the parent's state, so the state stores an array of components where each component contains a DOM stream and an delete$ stream (which is an event stream that's merged with the other delete$ streams in the collection and circularly fed back into the parent's state whenever a component is "deleted".) https://github.com/wizardwerdna/FRPBowlingKata/blob/3fac4b022913115f0ff7c0261f9160798671993f/src/model.ts#L66

The parent also renders a `combineLatest` of the DOM streams from the stored components like so:
```
  function toModel$(state$) {
    return state$
      .switchMap(state => O.combineLatest(
        ...state.list.map(listItem => listItem.line.DOM)
      ).defaultIfEmpty([]))
      .startWith([]);
  }
```
https://github.com/wizardwerdna/FRPBowlingKata/blob/3fac4b022913115f0ff7c0261f9160798671993f/src/model.ts#L47

It's this `switchMap(...combineLatest(...DOM))` line that triggers a reset on each of the child components.  If the equivalent in xstream is used `map(...combine(..DOM)).flatten()`, the reset will not occur due to the way in which `flatten` is architected.

We discussed manually managing subscriptions using `publish` + `connect` but avoiding hot/cold distinctions was something Andrew wanted to do for now.

**Comment by whitecolor** [comment]
@ntilwalli instead of `switchMap(...combineLatest(...DOM))` you should try `combine(...).withLatestFrom(state$)` for circular deps you may use https://github.com/whitecolor/cycle-proxy

**Comment by wizardwerdna** [comment]
@whitecolor proposed the use of combine().withLatestFrom() in lieu of switchmap.  Unless I'm mistaken, there is is no combine() in RxJS 5.0.  If you have any alternative in mind that would address this issue (ideally in a way that would be pedagogically straightforward for use in a screencast), few things would make me happier.

**Comment by whitecolor** [comment]
@wizardwerdna combineLatest?

**Comment by wizardwerdna** [comment]
right.  that's what i'm using in the code... see above.
