### ISSUE TITLE
captureClicks captures anchor link clicks

### ISSUE THREAD

**Issue by mz3** [cyclejs/cyclejs#430]
Copied from [cyclejs/history](https://github.com/cyclejs/history). PR is ready [here](https://github.com/cyclejs/cyclejs/pull/431).

```html
<a href='#myAnchor'>...</a>
```

Expected behaviour: page jumps to anchor element
Actual behaviour: router re-runs current component/app

I can submit a PR if wanted. I think it's just a matter of changing

captureClicks.js:42
```js
if (link && link.indexOf('mailto:') > -1 || link === '#') {
    return;
}
```

to

```js
if (link && link.indexOf('mailto:') > -1 || link.charAt(0) === '#') {
    return;
}
```

**Comment by staltz** [comment]
Done in `@cycle/history` v4.0.1
