### ISSUE TITLE
Update snabbdom to v0.6.1

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#433]

**Comment by vipero07** [comment]
Just wondering if there is any particular reason to not consider alternative VDOM libraries? At this point it appears as if [inferno](https://github.com/trueadm/inferno) may be a faster VDOM implementation (than most of the others). When accounting for recalc style, layout, paint, and composition it is almost 200,000 ms faster on my machine than snabbdom according to [this benchmark](https://localvoid.github.io/uibench/). With [this](http://vdom-benchmark.github.io/vdom-benchmark/) one it is almost half the time.

Personally I'd prefer an interface to allow for implementation of any VDOM as opposed to being locked into any one. Especially with all the optimizations that have been going on in that area.

**Comment by mightyiam** [comment]
@vipero07 see #467

**Comment by TylorS** [comment]
@vipero07 Snabbdom is likely never going to be a bottleneck in most users' applications. Inferno is fast, but it has tradeoffs too. Performance is not the dominating factor IMO. Also you may be interested in this [article here](https://medium.com/@localvoid/how-to-win-in-web-framework-benchmarks-8bc31af76ce7#.xcxl9qwgx) it goes into a bit of information how all of these virtual-dom benchmarks are skewed.

**Comment by staltz** [comment]
What Tylor said.

**Comment by staltz** [comment]
Done in the Cycle Unified branch. Not yet released.
