### ISSUE TITLE
history: update typings to be compatible with mjackson/history

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#443]
Use standard `history` typings (from @types/history) in @cycle/history.

**Comment by TylorS** [comment]
I don't think this is very useful to do. The typings from `@types` are mirrored from DefinitelyTyped and the types there are for version 1.8 https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/history/history.d.ts#L1

**Comment by whitecolor** [comment]
> types there are for version 1.8

Will 1.8 is compatible with 2.0 and probably soon will be updated. If people are not supposed to know about `hystory` typings, probably `hystory` should be a dependency of `@cycle/history`.

**Comment by TylorS** [comment]
1.8 of the history library, not TypeScript, which is now at 4.x. @cycle/history is designed to work with the API of the history library, but *not* as a requirement. @cycle/history only requires a simple history interface to be met, and that is not dependent upon the `history` library. I'm not a fan of having hard dependencies unless it's actually required.

**Comment by whitecolor** [comment]
@TylorS ok about version, but modules in @types are versioned and if you install latest `@types/hystory` you will get defs for history v2, not sure in what branch or they are stored in DT

**Comment by whitecolor** [comment]
@TylorS so what do you say?

**Comment by TylorS** [comment]
I think we can update the typings here to be more accepting of other stuff, this was this first thing I'd ever written in TypeScript. I don't think we should depend directly on history or it's typings as it's merely just a library that happens to implement the interface this driver works with.

**Comment by TylorS** [comment]
Yeah, that'd be as simple as changing the `interface`s in interfaces.ts to `type`s I believe. Then TS should be able to check the structure of the objects instead of checking to see if the interface is implemented.

**Comment by whitecolor** [comment]
So, its better reopen not to forget.

**Comment by staltz** [comment]
Seems done long ago
