### ISSUE TITLE
Refactor cycle/dom

### ISSUE THREAD

**Issue by Frikki** [cyclejs/cyclejs#445]
### Overview

Refactor cycle/dom using clean code principles.
### Motivation

Clean code is a reader-focused development style that produces software that is easy to write, read and maintain.

> Programming is the art of telling another human what one wants the computer to do.
> Donald Knuth
#### 1. You’re an Author

An author is someone who practices writing as a profession. Developers write all day. Yet as developers, it’s easy to forget that each line of code we write is likely to be read 10 or more times by humans during its lifetime. These humans are our fellow developers. They’re busy fixing bugs and adding features.
#### 2. It’s Foundational

Implementing clean code principles is a foundational skill that pays off especially well when it’s time to refactor code or bring code under test. Clean code principles lead to source code that’s highly modular and thus easier to read and test. If you think of these practices as part of a house, clean code is the foundation.
#### 3. Justify Your Technique

Imagine you’ re sitting in a technical interview. If you’re asked about your code quality, could you provide a professional and rational justification? Or would this be you?

_Interviewer: How do you write code that is readable and maintainable by others?
Interviewee: Uh... I use comments?_

Clean code is able to convey many concrete activities, patterns and techniques used to keep the code clean. After all, **clean code doesn’t happen by accident**. It requires a deliberate and regular focus on clearly conveying intent.

> What gets measured, gets managed.
> Peter Drucker

Building a vocabulary around clean code fosters level-headed conversations in code reviews by establishing a common vocabulary and framework for discussing code readability.
#### 4. Reading Is Hard

Developers often pride themselves with their ability to solve difficult problems. However, writing code is relatively easy. Reading is hard. This is why so many developers are tempted to rewrite rather than do the hard work of reading and comprehending existing code. Since reading code is naturally challenging, if you write code that you’re barely able to follow as you write it, you’ll find you're unable to comprehend it all later. Professional developers write so much code that after a few weeks of separation, most the structure and design decisions fall out of memory. It's like looking at the project with a fresh perspective. Not being able to understand your own code a few weeks later can be a really depressing situation.
#### 5. Technical Debt Is Depressing

Writing sloppy or confusing code injects technical debt into our projects. And while technical debt can be useful when carefully considered in context, excessive technical debt is depressing and drives talent away from the organisation. When the easy things become hard, developers start voting with their feet and go elsewhere. Developers derive more satisfaction out of the quality of their work than the quantity. Technical debt decreases the chance of reuse and sets a low bar for quality throughout the rest of the code base.
#### 6. You Are Lazy

Larry Wall, author of the PERL programming language, said that the three great virtues of a programmer are [laziness, impatience and hubris](http://threevirtues.com). Professional developers strive to be the good kind of lazy. This laziness is based on putting extra care into the code so that it’s not so hard to write up front, and it’s easier to work with later. **Writing clean code doesn’t take any longer**. Once you grasp the principles, you can actually code more quickly because terse, expressive code that does one thing is easier to manage.

When under pressure, it’s tempting to cut corners and ignore best practices. However, as Uncle Bob Martin reminds us in his book [Clean Code](http://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882), we don’t have time to be sloppy. Being sloppy ultimately slows us down in the long-term due to the increased frequency of bugs and the long-term costs of maintenance later. History has shown it’s unlikely you’ll find time to clean it up later, so why not do it right the first time?
#### 7. Don’t Be a Verb

The reasons are solid, but this one is the clincher: Everyone knows the previous developer whose name became a verb to describe dirty code.

> Oh man, this code has been Jimmy’d.

Comments like this are the kiss of death. Being known for writing clean code is a great way to assure your fellow developers recommend you and look forward to working with both you and your code in the future.
### The Fix
1. **Each class, method or any other entity should remain undisturbed.** It should conform to [the SRP (Single Responsibility Principle)](http://en.wikipedia.org/wiki/Single_responsibility_principle)
2. **The language you wrote your code with should look like it was made for the problem.**
3. **Code should not be redundant.** It should comply with [the DRY rule (Don’t Repeat Yourself)](http://en.wikipedia.org/wiki/Don't_repeat_yourself). When the DRY principle has successfully been applied, the modification of any single element of a system doesn’t require a change in any other logically unrelated elements.
4. **Comply with [the KISS principle (Keep It Simple, Stupid!)](http://en.wikipedia.org/wiki/KISS_principle) and [YAGNI principle (You Ain’t Gonna Need It)](http://en.wikipedia.org/wiki/You_ain't_gonna_need_it).** The KISS principle states that most systems work best if they are kept simple rather than made complex.
5. **Don’t write code for yourself**, or worse – for a compiler. You write code for other developers.
6. **Code should have minimal dependencies.** The more dependencies it has, the harder it is to maintain and change it in the future.
7. **Code should be minimal.** Both classes and methods should be short, preferably just a few lines of code. It should be well divided (also within one class). The better you divide your code the easier it becomes to read it.
8. **Code should have unit and acceptance tests**.
9. **Code should be expressive.**

**Comment by staltz** [comment]
One-year stale issue
