### ISSUE TITLE
Tests: Write tests in TypeScript

### ISSUE THREAD

**Issue by TylorS** [cyclejs/cyclejs#446]
# Overview

Update the tests of this repo to use TypeScript via `ts-node`
# Motivation
1. Allow TypeScript to type-check our tests <br/>
   It's quite possible to write tests that are not doing what we think they are, it can be useful to have a compiler that better understands our intentions and can spot errors in our lines of thought.
2. Allow writing tests that ensure intuitive and correct type inference<br/>
   Without writing tests in TypeScript, it is impossible to write a test that checks if type signatures are inferred by the compiler in an intuitive way.
3. Single language used across the stack <br/>
   Use the same language to write a test as you write features with.

**Comment by staltz** [comment]
This is done.
