### ISSUE TITLE
Release the latest storage driver to npm

### ISSUE THREAD

**Issue by ntilwalli** [cyclejs/cyclejs#447]
See https://github.com/cyclejs/storage/issues/19

The diversity-compatible (v3) version of the storage driver is not the official version on npm, it's only avail as an `RC` version which specifically must be targeted...  Please merge the diversity changes to master and publish...

**Comment by SuperManitu** [comment]
I added a PR to this v3 release converting it to typescript, this might be good to integrate too

**Comment by staltz** [comment]
Done
