### ISSUE TITLE
DOM click event bug

### ISSUE THREAD

**Issue by philipyoungg** [cyclejs/cyclejs#449]
Hello guys. I think I found an issue regarding click event on DOM.

I made an simple app where it pulls a 10 list of user from API.
For each lists, I made a click listener where:

- it found the user ID from `e.target.getAttribute('key')`,
- update the total user array with scan,
- and updates the DOM.

You can also click 'refresh user' to get new user from the same API.

There's 2 issue that I encountered: click handlers bug & visual bug

1. **Click handlers bug:** After a while clicking delete and refresh user (working as expected), there's a strange behavior starts. It somehow works like there's 2 DOM working layer on layer. For example, when I clicked remove on user ID 2, it also clicks on user ID 3 (or any random number, possibly the next sibling node ID on the list). The weird thing is, the user **are not removed**, despite the click events are registered from `console.log`.

2. **Visual bug:** Imagine there's a user ID 1 - 10 on the list. When you clicked to remove user ID 4, it immediately hovered to the next user ID (on this case, ID 5) on DOM for 50-100ms, and moved back to the correct user ID. While not a big problem, it's annoying and I think this issue has a correlation with the first one. 
EDIT: to reproduce the issue, try to delete **one previous item before the last** (for example 9th items when there's 10 item). Succesfully reproduced it 100% from Safari 10.0 & Chrome 53.0.2785.143

Screenshot for double click bug
[http://imgur.com/a/UUwLg](http://imgur.com/a/UUwLg)

I've uploaded the project to github if you are interested to see the issue from your browser

```javascript
git clone https://github.com/philipyoungg/cyclejs-test-project
npm i
npm run || node_modules/.bin/webpack-dev-server
```

Any help would be appreciated.

**Excerpt code to reproduce the issue:**

```javascript
const userComponent = ({ DOM }) => {
  const initialState = { users: [], filter: true };

  const toggleFilter = DOM.select('.toggle-filter').events('click')
    .mapTo('toggle click')
    .map(bool => state => //eslint-disable-line
      R.evolve({
        filter: R.not,
      })(state));

  const deleteUser = DOM.select('.delete-user').events('click')
    .map(e => e.target.getAttribute('key'))
    .map(Number)
    .do(console.log)
    .map(actionId => state =>
      R.evolve({
        users: R.reject(R.propEq('id', actionId)),
      })(state));

  const requestClick = DOM.select('.refresh-user').events('click')
    .startWith('init click')
    .mapTo('https://jsonplaceholder.typicode.com/users/')
    .flatMap(URL => Observable.fromPromise(fetch(URL)))
    .flatMap(x => x.json())
    .map(initState => state => R.assoc('users', initState)(state));

  const state = Observable.merge(deleteUser, toggleFilter, requestClick)
    .scan((acc, x) => x(acc), initialState)
    .startWith(initialState)
    .do(console.log);

  const view = state.map(data =>
      div('.pv4.ph5', [
        h1(`Filter: ${String(data.filter)}`),
        button('.toggle-filter.pa3.mb4', 'toggle filter'),
        button('.refresh-user.pa3.mb4', 'refresh new user'),
        data.users.length > 0 ? UserList(data.users) : p('Loading...'), // eslint-disable-line
      ])
    );

  const sinks = {
    DOM: view,
  };
  return sinks;
};
```

**Versions of packages used:**
```javascript
"devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.17.0",
    "babel-loader": "^6.2.5",
    "babel-preset-es2015": "^6.16.0",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.16.2"
  },
  "dependencies": {
    "@cycle/dom": "^12.2.5",
    "@cycle/http": "^11.0.1",
    "@cycle/rxjs-run": "^3.0.3",
    "@cycle/xstream-run": "^3.1.0",
    "ramda": "^0.22.1",
    "rxjs": "^5.0.0-beta.12",
    "universal-fetch": "0.0.1",
    "xstream": "^6.4.1"
  }
```

*Edited Oct 11 '16 at 12:33 (UTC), @Frikki*
Corrected `webpack-dev-server` command to include *node_modules* path.

**Comment by Frikki** [comment]
There is no build script in the `package.json`  and no instructions on how to build the project, @philipyoungg .

Running `webpack-dev-server` provides a browser response:

> Cannot GET /

**Comment by philipyoungg** [comment]
@Frikki I forgot that I installed webpack-dev-server and babeljs globally on my system. Appreciate your correction, @Frikki!

**Comment by Frikki** [comment]
The issue of 

> Cannot GET /

is still not solved in your project, @philipyoungg

**Comment by philipyoungg** [comment]
@Frikki ...and I ignored the dist/index.html file from .git. Should be fixed by now.

**Comment by Widdershin** [comment]
@philipyoungg I see the issues you're experiencing.

The issue with the wrong items being displayed after removal/things getting stuck can be solved by giving each `User` a unique `key`:

```diff
  const User = ({ id, name, email }) =>
-   li('.mb5', [
+   li('.mb5', {key: id}, [
```

This is used as a hint by snabbdom to determine when an element has modified, rather than created or destroyed. (virtualdom and react also require unique keys in this situation)

As for why the cursor occasionally focuses on the next item's remove button immediately after removal, I see that but I'm not sure how to fix that.

My best guess is that when we remove the second to last element, the last element pops up to take its place. It seems that there is a timing error where sometimes the document is not resized until after the hover animation for the last element has been triggered.

I wonder if perhaps part of snabbdom or cycle/dom should be using `requestAnimationFrame` but is not.

**Comment by philipyoungg** [comment]
@Widdershin thank you for the quick follow up! Unfortunately, changing the key to `li` instead of `span` still produces the same issue.

**previous code:**
```javascript
const User = ({ id, name, email }) =>
  li('.mb5', [
    h1('.mb0', name),
    p('.mt2.mb4.black-60', email),
    span('.delete-user.pointer.ba.pa2.hover-bg-black.hover-white.bg-animate',
    { attrs: { key: id } }, 'remove user'), //the key was here
  ]);
```
**changed to:**
```javascript
const User = ({ id, name, email }) =>
  li('.mb5', { attrs: { key: id } }, [ // moved to here
    h1('.mb0', name),
    p('.mt2.mb4.black-60', email),
    span('.delete-user.pointer.ba.pa2.hover-bg-black.hover-white.bg-animate', 'remove user'),
  ]);
```

**and I also changed the intent/model to:**
```javascript
const deleteUser = DOM.select('.delete-user').events('click')
    .map(e => e.target.parentNode.getAttribute('key')) // changed here
    .do(console.log)
    .map(Number)
    .map(actionId => state =>
      R.evolve({
        users: R.reject(R.propEq('id', actionId)),
      })(state));
```

so it's properly targeted to `ul` element.

As for the second issue, I think this is actually an expected behavior. It only happens when the element are on bottom viewport. Notice how the browser's scrollbar jumps everytime the element get removed from DOM.

-----------------------------------------------------------------------------

EDIT: By the way, I also try to change the code as you stated to
```javascript
const User = ({ id, name, email }) =>
  li('.mb5', { key: id }, [ // added key here
    h1('.mb0', name),
    p('.mt2.mb4.black-60', email),
    span('.delete-user.pointer.ba.pa2.hover-bg-black.hover-white.bg-animate',
    { attrs: { key: id } }, 'remove user'),
  ]);
```

and so far I haven't encountered the problem anymore! Why does this works? Would this issue persist if the generated user ID are random (compared to sequential 1 to 10)?

**Comment by Widdershin** [comment]
Here's the relevant documentation for snabbdom (all the way at the bottom):
https://github.com/snabbdom/snabbdom#key--string--number

You must ensure that all of the keys that you use are unique. So they can be random, as long as you hold on to the values (the key for a given User shouldn't changed.)

As I noted above, all virtual dom libraries require keys when you have a dynamic list of similar elements.

You might also be interested in `cycle-collection`, a helper library that manages ids and keys for you: https://github.com/cyclejs/collection

**Comment by philipyoungg** [comment]
I see, thank you @Widdershin and @Frikki for solving this issue. I'm going to close this! ☺️
