### ISSUE TITLE
Transpilation failing for typescript users on @cycle/dom v12.2.6 

### ISSUE THREAD

**Issue by ntilwalli** [cyclejs/cyclejs#454]
Transpilation is failing for Typescript users using @cycle/dom v12.2.6.  The reason is, type reference directives for any implicitly referenced ambient types are added to the top of declaration files automatically by the compiler since TS v2.0 (https://github.com/Microsoft/TypeScript/commit/376c493e678ca702f9f0f87779ce320f437b3132)

This is causing a `///<reference types="core-js">` to be added to the top of any generated .d.ts files in the lib directory which implicitly reference `core-js` types in `@cycle/dom`. For that package `core-js` is a devDependency. so upon npm install, those types are not installed for regular users.  For typescript users, this means if your project does not install `@types/core-js` locally the transpilation will error out since the `@cycle/dom` typings will reference types which are not available.

In my analysis, this effectively makes `@types/core-js` a peerDependency or dependency for Typescript users and a devDependency for non-typescript users.

I dunno the right way to handle this...

cc: @staltz @geovanisouza92

Note: I've requested they add a flag to disable this directive inclusion here: https://github.com/Microsoft/TypeScript/issues/11586

**Comment by staltz** [comment]
I noticed the same issue today in my project at work. I'm also not sure yet how to solve this, but it's rather important.

**Comment by staltz** [comment]
Should we do something like this? https://github.com/ReactiveX/rxjs/pull/2027/files

**Comment by TylorS** [comment]
Yeah, my initial thoughts to this was that we should use the `es2015` typings that TypeScript already offers us.

**Comment by ntilwalli** [comment]
Yeah, I was just playing with those options.  It fixes the issue.  We could def use `es2015`. This subset also fixes the issue:
```
    "lib": [
      "dom",
      "es5",
      "scripthost",
      "es2015.collection",
      "es2015.promise",
      "es2015.iterable"
    ]
```

**Comment by ntilwalli** [comment]
Using those options means not installing`@types/core-js` at all, right?

**Comment by TylorS** [comment]
Yeah, no more core-js.

**Comment by staltz** [comment]
I'll close this when I release the new version of DOM.

**Comment by staltz** [comment]
@ntilwalli no worries for now, but just informing: next time use 3 separate commits `fix(dom)`, `fix(xstream-run)` etc because these will prompt for 3 different version releases automatically. I can do it manually now, but fix(META) is a type of commit we shouldn't do.

**Comment by staltz** [comment]
<img width="775" alt="screen shot 2016-10-13 at 20 27 20" src="https://cloud.githubusercontent.com/assets/90512/19359584/79f4c358-9183-11e6-912a-ebe052e6519f.png">

In fact I'll just issue an update to our `npm run commit` command so that it's impossible to write `fix(META)` commits.

**Comment by staltz** [comment]
The new version of DOM is out. Super thanks to Nikhil! (Love it that you're contributing recently)
