### ISSUE TITLE
(Wrong) use of `const run = require('@cycle/xstream-run').default` silently fails

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#457]
**Code to reproduce the issue:**

Right here in this repository:
https://github.com/mightyiam/cyclejs-xstream-run-default-export

**Expected behavior:**
Use of wrong import gives an error. Perhaps even pointing you in the right direction.

**Actual behavior:**
Use of wrong import (`const run = require('@cycle/xstream-run').default`) silently fails...

This cost me some time.

**Versions of packages used:**
`"@cycle/xstream-run": "3.1.0"`

**Comment by staltz** [comment]
Use TypeScript. It tells you these problems. I can't imagine how to do this in normal ES6. JavaScript is an hard-to-work-with language without any intelligent errors and for people with an adventurous spirit. Use TypeScript.
