### ISSUE TITLE
Click event fired twice

### ISSUE THREAD

**Issue by svileng** [cyclejs/cyclejs#464]
**Code to reproduce the issue:**

```js
  let submitClick$ = sources.DOM.select(buttonSel)
    .events("click")
    .debug()

  let submitDeal$ = submitClick$.map(() => {
    // Implementation logic omitted.
    // let data = {...}
    
    event.preventDefault()
    event.stopPropagation()
    
    // Logged twice.
    console.log("Submitting...")
    
    return xs.fromPromise(DealAPI.post(data))
  })
```

[Full code and template here](https://gist.github.com/svileng/36cc443f6cc94f9f1b6c01a98d14861d)

**Expected behavior:**
The code in the `submitClick$.map` function to be called once after a click.

**Actual behavior:**
The code is firing twice, but the stream emits once. Some of my findings so far:

1. The JS bundle is included only once on the page, so it's not run twice;
1. The `event.timestamp`s of the two events are exactly the same, coming to and from the correct element;
1. There is only one `.btn--add-deal` element on the page. There is no other code that attaches events to this element in the code base;
1. `@cycle/dom`s `EventDelegator` calls `addEventListener` only once.

I noticed that cycle/dom actually attaches the click event to the DOM root element, and then seems to re-route the events to the correct element, but I'm not completely sure how that works and if it could be source of the problem.

Also [posted on StackOverflow](https://stackoverflow.com/questions/40064504/cycle-js-xstream-click-event-streamed-once-but-fired-twice) sometime ago, where @staltz had a quick look, but there wasn't code attached at the time.

**Versions of packages used:**
- @cycle/dom@12.2.8
- @cycle/xstream-run@3.1.0
- xstream@6.4.1

Chrome  54.0.2840.71

**Comment by staltz** [comment]
@svileng can you try using xstream v7.0? We fixed a bug there that looks like your use case.

**Comment by staltz** [comment]
(Will reopen if we confirm it's still a bug on our side)

**Comment by svileng** [comment]
Upgrading to xstream 7 fixes the issue! Thanks!

**Comment by staltz** [comment]
Cool 😎
