### ISSUE TITLE
DOM is not rendered directly inside shadow root

### ISSUE THREAD

**Issue by foxylion** [cyclejs/cyclejs#468]
**Code to reproduce the issue:**
As a base use the code from [here](https://github.com/foxylion-playground/cyclejs-test/tree/039b02fda5dbb735947b61ab1cadda25af7be56d).
Then replace in `src/index.ts` the following code block:

```
var span = document.createElement("span");
root.appendChild(span)
createUserGreeter(span);
```

with

```
createUserGreeter(root);
```

**Expected behavior:**
The website shows `My Awesome Cycle.js app!`.
I've a similar react [example](https://github.com/foxylion-playground/react-test/blob/master/webcomponent.html) which is working when using the shadow root.

**Actual behavior:**
The website is empty and does not throw any exception or show an error.

**Versions of packages used:**

```
"@cycle/dom": "^13.0.0",
"@cycle/xstream-run": "^3.1.0",
"xstream": "^7.0.0"
```

**Comment by staltz** [comment]
I believe this was fixed in Cycle DOM v14.2. Please put a comment if you see this issue still happening.
