### ISSUE TITLE
DOM Driver is not reusable after disposal

### ISSUE THREAD

**Issue by Widdershin** [cyclejs/cyclejs#485]
**Code to reproduce the issue:**
```js

  it('is reusable after disposal', function (done) {
    function app() {
      return {
        DOM: Rx.Observable.of(
          div('Hello world')
        )
      };
    }

    const drivers = {
      DOM: makeDOMDriver(createRenderTarget('disposal-reuse'))
    };

    const {sinks, sources, run} = Cycle(app, drivers);

    const dispose = run();

    setTimeout(() => {
      let renderTarget = document.getElementById('disposal-reuse');
      assert.equal(renderTarget.innerHTML, '<div>Hello world</div>', 'expected hello world before dispose');

      dispose();

      setTimeout(() => {
        let renderTarget = document.getElementById('disposal-reuse');
        assert.equal(renderTarget.innerHTML, '', 'expected nothing after dispose');

        let newSinksSourcesAndRun = Cycle(app, drivers);

        newSinksSourcesAndRun.run();

        setTimeout(() => {
          let renderTarget = document.getElementById('disposal-reuse');

          assert.equal(renderTarget.innerHTML, '<div>Hello world</div>', 'expected hello world after rerun');

          done();
        }, 100);
      }, 100);
    }, 100);
  });
```

**Expected behavior:**
Expected that the drivers object would be reusable for multiple successive calls to run.

**Actual behavior:**
Disposing an application means that if the drivers object is reused, the DOM driver will not emit any new updates.

The above test cases fails at the last assertion, 'expected hello world after rerun'. This test case can be made to pass by creating a new drivers object for the second run.

**Versions of packages used:**
14.1.0

@staltz I mentioned this to you, and I am able to work around it by requiring that users wrap their drivers object in a function. This is not ideal, but it works.

I wrote a test case to reproduce this issue, but I was unable to fix it without serious investigation. I'm opening this issue in the hopes that the answer might obvious to you or @TylorS.

It seems like potentially it's not worth assuming that the drivers object can be reused, as it seems like it's quite common to do setup inside of a `makeFooDriver` method. That setup all has to remain intact for this to work.

**Comment by whitecolor** [comment]
if to move those two lines inside driver function itself: 
https://github.com/cyclejs/cyclejs/blob/master/dom/src/makeDOMDriver.ts#L43-L44

would it work?

**Comment by Widdershin** [comment]
Perhaps, it would be awesome if you'd like to give it a go.

I almost feel that this issue should just be closed, as relying on a driver being reusable means that driver authors have to be very careful about where resources are created and disposed. There is already one issue on cycle-restart caused by this: https://github.com/Widdershin/cycle-restart/issues/38

**Comment by whitecolor** [comment]
Yes probably relaying on usability is not a good thing and should be avoided, though, this should be mentioned in the docs that `makeFooDriver` is a factory that is used to pass configuration parameters and should return specially configured driver that should be possible to reuse as this would make it more transparent and simplify testing and usage.

**Comment by staltz** [comment]
Yeah I think you answered yourself already:

> It seems like potentially it's not worth assuming that the drivers object can be reused, as it seems like it's quite common to do setup inside of a makeFooDriver method. That setup all has to remain intact for this to work.

Basically `makeFooDriver()` is similar to `new FooDriver()`. We create an instance of the driver. It has beginning (the setup), middle (the usage in main), and end (disposal). After that, we need to create a new instance. It's how we teach how to make drivers: https://cycle.js.org/drivers.html

`Cycle.run` was always the imperative part of Cycle.js and we didn't have assumptions such as "`drivers` object will be used multiple times". I fear there isn't a way of making that assumption valid without redesigning the framework with some breaking changes.

So let's start looking at workarounds for the use case you want to support (restarting, correct?). How about not disposing between restarts? Any other ideas?

**Comment by TylorS** [comment]
As a workaround, if you're calling Cycle.run() multiple times already..

```js
const drivers = {
  DOM: (...args) => makeDOMDriver('#app')(...args),
  HTTP: (...args) => makeHTTPDriver()(...args),
}
```

This will create new "instances" each time that Cycle.run() is being called.

**Comment by Widdershin** [comment]
For cycle-restart, I ask the users to wrap their drivers object in a
makeDrivers function and pass that in instead.

```js
function makeDrivers () {
  return {
     DOM: restartable(makeDOMDriver (...))
  }
}
```

This works well and allows me to dispose the drivers as normal.

**Comment by jvanbruegge** [comment]
@staltz I think this is solved with `setupReusable`, so we can close this issue

**Comment by staltz** [comment]
Agreed
