### ISSUE TITLE
Access response in cycle http driver on error

### ISSUE THREAD

**Issue by Steelfish** [cyclejs/cyclejs#486]
Currently the cycle http driver only returns the error message associated with the HTTP status code to the subscribing stream. The problem I am currently facing is that many different kinds of validation errors can be associated with the same status code. Rather than simply displaying: "Something went wrong." to the user, I'd like to display the error message in the response body returned from the api. 

This change could be as simple as changing lines 90-92 on the http driver from 

`
this.request.end((err: any, res: Response) => {
          if (err) {
            listener.error(err);
`

to
`
this.request.end((err: any, res: Response) => {
          if (err) {
            listener.error({ error: err, response: res});
`

**Comment by whitecolor** [comment]
Driver should emit full Error object that comes from superagent, and it contains response (`err.response`)

**Comment by whitecolor** [comment]
@staltz I believe this could be closed, see my comment.

**Comment by Steelfish** [comment]
@whitecolor is correct. Due to the console messaging only showing the error object's message property, I thought this was the only content of the error message. There is indeed already a response object on the error object.
