### ISSUE TITLE
Cycle GraphQL

### ISSUE THREAD

**Issue by kennetpostigo** [cyclejs/cyclejs#487]
Hello,

I'm working on a GraphQL client called greed that I haven't open sourced yet. Its framework/library agnostic and wanted to create some cycle bindings for it. I want to base the bindings off the same signature that I got working with react and vue which is:

```js
container(
  greed, 
  defaults, 
  queries, 
  mutations
)(component);

// Using a decorator
@container(
  greed, 
  defaults, 
  queries, 
  mutations
)
someComponent
```
**greed: greedInstance-** is the greed instance you want to use
**defaults: ?function -** are the default data for the component to render
**queries: ?function -** are the queries you can run when some user input occurs
**mutations: ?function -** are the mutations you can run when some user input occurs
**component: Component -** the component to enhance

The container essentially enhances whatever component it receives with data needed to render and methods that can be executed to run queries and mutations when some user input occurs in the application.

I'm not familiar with cycle myself, so I wanted some tips and feedback for the best way to go about implementing this in cycle.

**Comment by kennetpostigo** [comment]
@staltz are there any best practices when making libraries for cycle?

**Comment by staltz** [comment]
https://cycle.js.org/drivers.html

**Comment by kennetpostigo** [comment]
@staltz thank you, feel free to close this issue, but do you mind if we continue the discussion here so I can provide updates and ask for review?

**Comment by staltz** [comment]
Sure, feel free to discuss!
