### ISSUE TITLE
Add a manual alternative to test-browser in cycle/dom's package.json

### ISSUE THREAD

**Issue by ajmchambers** [cyclejs/cyclejs#491]
Hello again,

I've been testing 'Bash on Ubuntu on Windows' with the goal of being able to run the cycle/dom browser tests against my local browsers: chrome, firefox, edge, ie etc... however I've run into a couple of issues.

Running `npm run test-browser` fails when attempting to launch Chrome and Firefox (because its trying to run chrome and firefox on ubuntu):

```bash
not ok 1 Error
    ---
        message: >
            Launcher firefox not found. Not installed?
    ...

1..1
# tests 1
# pass  0
# skip  0
# fail  1
```

I don't think you can run windows programs directly from it and if I wanted to test Chrome/Firefox running on Ubuntu I could use a VM anyway.

So I'm thinking that instead a more general npm testem script could be added, that only runs testem and lets you manually launch the browsers that you want to test.
Something like below (with possibly better naming):

```javascript
"scripts": {
  //...
  "pretest-browser-manual": "npm run pretest-browser",
  "test-browser-manual": "../node_modules/.bin/testem",
  "posttest-browser-manual": "npm run posttest-browser",
  //...
},
```

This would be pretty great for testing locally on windows and would allow easier testing of things like the PointerEvents API for Touch/Stylus input, Pen Pressure etc... (which may not work or would work differently in a VM).

----------------------------------------------

I tested this locally, and for this to work I had to modify `.testem.json` so that the mocha files are copied/removed `on_start` / `on_exit` instead of `before_tests` / `after_tests`:

```json
  "before_tests": "cp ../node_modules/mocha/mocha.* ./test/browser/page/",
  "on_start": "./.scripts/saucie-connect.js",
  "on_exit": "./.scripts/saucie-disconnect.js",
  "after_tests": "rm ./test/browser/page/mocha.*",
```

To something like this:

```json
  "on_start": "./.scripts/saucie-connect.js; cp ../node_modules/mocha/mocha.* ./test/browser/page/",
  "on_exit": "./.scripts/saucie-disconnect.js; rm ./test/browser/page/mocha.*",
```

Otherwise I would get this error when opening a browser to test:

![testem-error](https://cloud.githubusercontent.com/assets/5426717/21154809/a92de94c-c167-11e6-817c-995a092de329.png)

What do you reckon?

**Comment by staltz** [comment]
If the changes to make it work for you are few lines of code, send a PR, and I'll check if it still works in Ubuntu and macOS.
