### ISSUE TITLE
rxjs-run broken with rxjs@5.0.1 (even rxjs@5.0.0-beta.12)

### ISSUE THREAD

**Issue by jhamlet** [cyclejs/cyclejs#494]
**Code to reproduce the issue:**
simple app:
```js
import rx from 'rxjs';
import { run } from '@cycle/rxjs-run';
import { makeDOMDriver, h1 } from '@cycle/dom';

function main () {
  return {
    DOM: rx.Observable.interval(1000).map(i => h1(`interval ${i}`))
  };
}

const drivers = {
  DOM: makeDOMDriver('#app')
};

run(main, drivers);
```

**Expected behavior:**
```
(<h1>interval 0</h1>)---(<h1>interval 1</h1>)---(etc...)
```

**Actual behavior:**

```
makeDOMDriver.js:22 Uncaught Error: The DOM driver function expects as input a Stream of virtual DOM elements
```

**Versions of packages used:**
installed dependencies:
```js
    "@cycle/dom": "^14.2.0",
    "@cycle/http": "^11.2.0",
    "@cycle/rxjs-run": "^4.0.0-rc.1",
    "rxjs": "^5.0.1"
```

**Other Info**

* running through webpack
* tried previous versions of `rxjs` (the one listed in devDependencies for the rxjs-run package.json)

**Some Insights**

* works fine if I switch to the `xstream` version of things
* `@cycle/rxjs-adapter` **does not** get installed, however `@cycle/xstream-adapter` does
* `main()` is never called (i assume this is because it is failing the validation check on the vdom stream)

**Comment by jhamlet** [comment]
FWIW works with the old version of `RxJS`
```js
    "@cycle/dom": "^14.2.0",
    "@cycle/rx-run": "^7.1.0",
    "rx": "^4.1.0"
```

**Comment by jhamlet** [comment]
More FWIW:

https://github.com/cyclejs/cyclejs/blob/master/dom/src/makeDOMDriver.ts#L48-L76
expects three arguments: a stream, and adapter, and a name.

However, when used with `rxjs-run`, the input arguments are an `rxjs.Observable`, the string "DOM", and undefined for the third (`name`).

...still digging

**Comment by jhamlet** [comment]
Another FWIW:

If I clone the repository, run `npm dist` in the `rxjs-run` directory and then `npm install [path-to-local-repo]/rxjs-run` everything works...

Must be an npm issue...?

**Comment by staltz** [comment]
I think you are missing the dependency with `xstream`. Cycle DOM uses xstream so you need to include that in package.json too. Can you try that?

**Comment by staltz** [comment]
I'll close this and reopen once you answer, because it's unclear whether it's a question or a bug.

**Comment by jhamlet** [comment]
Apologies for the slow response @staltz

I reinstalled latest and everything worked... apologies for the time suck.

;-j
