### ISSUE TITLE
Support history 4.0.0+

### ISSUE THREAD

**Issue by mz3** [cyclejs/cyclejs#498]
History ^3.0.0 works fine with @cycle/history, but using the most recent version of history (4.5.0):

`makeHistoryDriver requires an valid history object containing createLocation(), createHref(), push(), and listen() methods`

A cursory glance indicates that `createLocation` is deprecated in newest history.

**Comment by TylorS** [comment]
Hello @mz3 Closing this as a duplicate to #434 Feel free to join the chat there :)

**Comment by mz3** [comment]
Thanks! Sorry, did not see the other issue :)
