### ISSUE TITLE
An attempt to "liberate" from selectors: a modest proposal

### ISSUE THREAD

**Issue by dmitriz** [cyclejs/cyclejs#501]
Having suffered from Angular's lack of data flow structure and React's verbosity and boilerplate, I find Cycle really fascinating -- truly amazing piece of work and probably the most elegant, flexible and advanced JS framework out there!

Unfortunately, there is one major thing that keeps bothering me: 

- The apparent lack of DOM's encapsulation inside the Components and accessing its view implementation details directly with selectors. I would like to "protect" my Components from the "prying eyes" of other Components and their sisters. ;-)
- Selectors are used inside Intent Functions, which is far away from the code declaring the actual selectors inside the View Function. In my opinion, that breaks the code's cohesion (closely related parts don't stay close) and makes it hard to keep things in sync when refactoring.

I kept thinking, it might be just me, but then came across someone else mentioning the same problem, who had actually built an app with Cycle:

https://www.reddit.com/r/javascript/comments/4ru2d3/cyclejs_a_reactive_framework_humancomputer/d54fkvp/

> I built a medium size internal app half a year ago, spent around a month building it.
> ...
> My biggest problem was an unclear component model. Component creates observables by selecting DOM elements by Id. I can declare in the header to watch for events on the footer but when looking in the footer I will have no idea that someone is observing footer DOM events. And, from what I understand, there can be no redux-like global state because observables hook up to DOM only in the component functions.
>
> For now I am really happy with React+Redux and I plan to stick with it, but I am really interested to see where Cycle.js goes.

So the sad part here, that person actually dropped using Cycle for that precise reason. :(

---

Having, hopefully, made a compeling case, here is my humble attempt to address this problem.

[Here is a complete example with comments](https://github.com/dmitriz/cyclejs/blob/exp-modify/examples/basic/counter/src/main-modified.js) (based on the [counter example](https://github.com/cyclejs/cyclejs/blob/master/examples/counter/src/main.js)):

And here are the main parts of it:

```js
// We don't import and expose the DOM,
//  it remains the implementation detail we want to hide.
// Instead only import the event streams as that is all we care about 
function main({decrement, increment}) {

  // Now import and handle action streams
  //  without going directly into the DOM with selectors
  let action$ = xs.merge(
    decrement.map(ev => -1),
    increment.map(ev => +1)
  )

  let count$ = action$
    .fold((acc, seed) => acc + seed, 0)

  // Declare the sinks object, 
  //  so we can send our event streams directly into its props!
  // In "traditional" frameworks this would be the place
  //  to declare event handlers.
  // But here we don't need to couple the handlers directly with the view,
  //  as per Cycle's philosophy,
  //  we merely declare the sinks for the event streams we care about.
  let sinks = {}

  // Alternatively we could declare individual sinks for each event:
  // let decrement
  // let increment

  let $view = count$.map(count =>
    div([

      // Here is the proposed way of sending click streams into the sinks props,
      //  that should store the streams as 'sink.decrement' and 'sink.increment'.
      // 
      // Advantages: 
      //   (1) Actions are instantly visible in the view!
      //   (2) No selectors are needed, no naming pain, no global scope clash.
      //   (3) Easy to switch to another element without messing up selectors.
      //   (4) More in spirit of traditional frameworks using event handlers,
      //        attached directly to the elements, 
      //        so can appeal to folks used to those.
      // 
      button('Decrement').clickToStream(sink, 'decrement'),
      button('Increment').clickToStream(sink, 'increment'),

      // Alternative a possible shorter syntax can be used to send our event steams
      //  directly into individual sinks variables,
      //  that would allow for extra flexibility,
      //  e.g. to transform the streams before exporting.
      // 
      // button('Decrement').clickToStream(decrement),
      // button('Increment').clickToStream(increment),

      p('Counter: ' + count)
    ])
  )

  // Finally add the DOM prop for the drivers only
  //  as we don't need to show the inner parts to our Intent Function
  sinks.DOM = $view

  // Alternatively we could combine the streams or filter to 
  //  expose only important parts and encapsulate the rest.
  // 
  // sinks.actions = xs.combine(decrement, increment).filter(someFunction)

  // Simply export our event streams as sinks props
  return sinks
}
```

Note there are no selector classes needed!
Instead we use the new method called here `.clickToStream`,
whose purpose is to send the `click` event streams directly into their sinks variables,
and subsequently export as sinks properties.

I have listed several advantages in the comments above, but let me ephasize
that could likely bring Cycle closer to the event handler style of other frameworks,
and so make it appear more familiar and accessible to the folks over there,
with lower barriers to try Cycle, leading to hopefully wider adoption.

Further, it fully addresses the concern of the person mentioned above,
about being hard to see from the view, what events are selected and observed.
I understand that choosing "clever" selectors might also mitigate the problem,
but those would be exposed inside the DOM together with their "sisters"
and can get lost in the noise of other selectors used for styling,
instead of being segregated into a clean inteface.

---

Before being sent to read the explanation
> [Why CSS selectors for querying DOM events?](https://cycle.js.org/model-view-intent.html),

which I already did, I would like to address its main points:

- In the current proposal, we do not "specify what happens as the consequence of user's actions". We only export the actual event streams that we would, in the current Cycle architecture, still need to "fish" from the DOM with selectors later anyway. So the view is still not a "Proactive component".

- "Adding user actions shouldn’t affect the View." That mostly applies to the current proposal. The only thing added are the methods sending event stream into the props. We can always ignore them and export only what is needed. This goes well with the [Interface Segregation Principle](https://en.wikipedia.org/wiki/Interface_segregation_principle), where we only export what we want to and hide everything else. Note that in the current selector-based architecture we would still need to add and switch selectors inside the view code, leading to a similar unavoidable modification of the view.

- "The MVI strategy in Cycle DOM is to name most elements in the View with appropriate semantic classnames." In the current proposal, we can do exactly the same with the sink props instead of selectors. With the additional advantage, that we can also transform and pre-package our exported stream
for better encapsulation and separation of concern. Further, it can be argued that the need to declare "semantic classnames" is actually short of expressing the Intent inside the View, which is what we want to avoid, if I see it right.

---

To conclude, I'd like to address the common concern about "yet another feature?" ;) The only real addition needed is small - providing those methods `.clickToStream()` to store event streams into variables or props. Or, alternatively, providing a single method `.toStream()` taking event as another argument:

```js
button('Decrement').toStream('click', 'decrement')
//
// or this slightly uglier way:
// button('Decrement').toStream('click', sink, 'decrement')
```
or 
```js
button('Decrement').toStream('click', 'decrement')
```

Finally, if that addition is unwanted or needs to be tested, it can always be provided as extra plugin,
with the possibility of merging later when and if desired.

**Comment by geovanisouza92** [comment]
@dmitriz Nice idea, but I have some questions:

- Your proposal of a `.<eventName>ToStream` or `.toStream(eventName)` would be added in the snabbdom elements? because, the current syntax are from helper methods from snabbdom, that returns objects (elements)
- Considering that `$view` (or `vtree$` as commonly refered) is a Stream, the result of `.toStream` methods would be also streams? In that case, this would require some kind of transposition (flattening of stream with streams inside), that is a feature that old versions of DOM driver already had, but was dropped because it's implementation turn the codebase more complex and practical usage was low, AFAIK ( @staltz and @TylorS could confirm)
- What about composition? How can we connect parent components with its children? This sources seems to be manipulated somehow, to connect the `.toStream` on the sources, so can I guess that would be some High-Order component wrapper (e.g. isolate, onionify, etc)? In that case, this could be experimented aside from any Cycle.js modifications...

**Comment by staltz** [comment]
Hi @dmitriz , thank you for taking your time to elaborate your comment. I appreciate it, however this is not the first time this is raised. Every time the question I have to confirm that this will not happen, because: (1) it would change central ideas in Cycle.js related to dataflow and separation of concerns in MVI style, (2) it would remove selectors as names, but add stream names, so `-1+1==0`, (3) it would mean a huge breaking change to Cycle.js, basically becoming a different framework.

- - -

If you want more details why, and to learn more how Cycle.js came to be:

 > The apparent lack of DOM's encapsulation inside the Components and accessing its view implementation details directly with selectors. I would like to "protect" my Components from the "prying eyes" of other Components and their sisters. ;-)

`isolate`. Basically read this chapter https://cycle.js.org/components.html. There are many embedded FAQ there too, that address a lot of the concerns you raised.

> Selectors are used inside Intent Functions, which is far away from the code declaring the actual selectors inside the View Function. In my opinion, that breaks the code's cohesion (closely related parts don't stay close) and makes it hard to keep things in sync when refactoring.

Your proposal wouldn't change this issue. Instead of "selectors used in intent functions" we would have "names of sink streams used in intent functions". The **same name** is used in both view and intent, no matter if that name is a selector or a stream var name. 

> I built a medium size internal app half a year ago, spent around a month building it.
> My biggest problem was an unclear component model. Component creates observables by selecting DOM elements by Id. I can declare in the header to watch for events on the footer but when looking in the footer I will have no idea that someone is observing footer DOM events. And, from what I understand, there can be no redux-like global state because observables hook up to DOM only in the component functions.

They should have taken a look at isolate and https://github.com/staltz/cycle-onionify, which address both component boundaries and global state management. 

> I understand that choosing "clever" selectors might also mitigate the problem,
but those would be exposed inside the DOM together with their "sisters"
and can get lost in the noise of other selectors used for styling,
instead of being segregated into a clean inteface.

For styling, we highly recommend the use of https://github.com/blakeembrey/free-style which creates human-unreadable classnames, so there is no chance you could by accident use a styling classname in intent. When it comes to selection isolation, you need to use `isolate`.

> "The MVI strategy in Cycle DOM is to name most elements in the View with appropriate semantic classnames." In the current proposal, we can do exactly the same with the sink props instead of selectors. 

Actually you can't. Because you would have to declare all event types in the view. E.g. `.toStream('click', 'decrement')`, `.toStream('mouseenter', 'decrement')`, `.toStream('mouseleave', 'decrement')`, etc including all possible event types, so the intent can choose whatever event it wants. 

> Further, it can be argued that the need to declare "semantic classnames" is actually short of expressing the Intent inside the View, which is what we want to avoid, if I see it right.

No, not really. It's just a name for each element in the view. There shouldn't be any indication of "how the user can interact with this element" in that classname. Check out this codebase and how I use classnames in the view. https://github.com/staltz/matrixmultiplication.xyz/blob/master/src/Calculator/view/common.ts

Finally, I'd like to note that long time ago Cycle.js used to be the way you described. We had multiple iterations and things changed a lot with its design. I invite you to look at what we did from Cycle.js 0.11 to 0.12: https://github.com/cyclejs/cyclejs/releases/tag/v0.12.1 I'm very happy with the way the design evolved (through feedback from the community) and we're not looking to go back.

**Comment by dmitriz** [comment]
@geovanisouza92 Thanks for the good questions!

- I later realised that it is perhaps better to export the elements themselves. I'd like to make it agnostic of the vDom implementation but snabbdom is most important for now. It does provide event callbacks, but not sure if Cycle will like it ;)

- Good point, I'm a bit struggling at the moment to understand how it works.

- Composition is a valid point, I am simply thinking of the child component exporting its event streams into the sink to be consumed by the parent. So the parent component can listen to child's events and do nice things like sending HTTP requests. Very similar to the traditional callback via props patterns, just reversing control if I see it right.

After some reading, I noticed that Cycle child component currently export their state (or part of it) instead.

Here is what I've been trying to do but right now got stuck trying to use `.select` onto imported dom element, which doesn't seem to work:

https://github.com/dmitriz/cyclejs/blob/reflow-attempt/examples/intermediate/bmi-nested/src/LabeledSlider.js

**Comment by dmitriz** [comment]
@staltz Many thanks for your in-depth answer and your time, really appreciate the details, there is always more than looks on the surface ;) 

I did come across some some of the sources but would like to do some more reading and experimenting before answering something meaningful ;)

**Comment by milankinen** [comment]
@dmitriz Nothing prevents you from creating your own driver that supports such functionality. :) If you need a starting point, [this](https://github.com/milankinen/culli/tree/master/packages/dom) might give you some ideas (example usage [here](https://github.com/milankinen/culli/blob/master/examples/xstream-counter/Component.js#L45-L52), it's not actually hard to change the implementation to support your suggestion):

```js
  function view({num}) {
   let inc, dec, vdom = h("div", [
      h("h1", ["Counter: ", num.value]),
      h("div", [
        inc = h("button.inc", "Increment"),
        dec = h("button.dec", "Decrement")
      ])
    ])
    return {vdom, inc, dec} 
  }

  function intent({inc, dec}) {
    return xs.merge(
      inc.on("click")
        .map(() => ({type: "INC"})),
      dec.on("click")
        .map(() => ({type: "DEC"}))
    )
  }
```

(In case I understood your point right 😄)

Just be aware that if you change the dependency order from I->V to V->I, you need [`onionify`](https://github.com/staltz/cycle-onionify), [`@culli/store`](https://github.com/milankinen/culli/tree/master/packages/store) or [`stanga`](https://github.com/milankinen/stanga) to handle your circular app state.

**Comment by dmitriz** [comment]
@milankinen Thanks a lot for the suggestion! I've tried that and had to mess with streams in addition, but at the end it doesn't work for unclear to me reasons: 
my additional property `el` returned by the main function
comes back as `undefined`:

https://github.com/dmitriz/cyclejs/blob/naive-pass-el/examples/intermediate/bmi-nested/src/BmiCalculator.js#L46

Perhaps I fundamentally misunderstand how Cycle works....

But there is actually a bigger problem I ran into: in order to pass around the element that way inside my children component, I had to pollute the main root component, which does not feel right. And the reason being that the Cycle's data flow does not cycle inside individual components. Which creates a fundamental problem for my approach with current architecture.

Your projects look interesting BTW, I'll give them closer look, and perhaps you might want to make them "better discoverable" by linking from the main Cycle repo and the awesome-cycle.

**Comment by dmitriz** [comment]
There is perhaps some progress related to this issue, at least for me, that I'd like to report.

Having chatted with the fine folks from the [Mithril community](https://mithril.js.org/), specifically with @JAForbes whom I am grateful for calling my attention to how [the `flyd` stream library](https://github.com/paldepind/flyd) (and similarly [streams in Mithril](https://mithril.js.org/stream.html)) makes it really easy to have the view updating the action stream in a way extremely close to the popular Redux architecture (or Elm etc):

```js
const view = dispatch => state =>
  // the full event object is passed
  button({
    onclick: dispatch
  })
  // the interesting value is passed
  button({
    onclick: dispatch(`You shouldn't have clicked the red button!`)
  })
```

This view is very similar to the one in Cycle, except it is simpler being at the level of the plain objects and unaware of streams. It is easier to write, easier to scale etc. And to get a "proper" stream-based view as in Cycle, all you need is to `map` it over any state stream, where this `map` conforms to the [very general Functor interface](https://github.com/fantasyland/fantasy-land#functor), as implemented for the streams e.g. by flyd/mithril. 

Of course, the "real" stream-based view as in Cycle is more powerful and is capable of doing things a lifted plain view wouldn't be able to, but that power comes with the cost of complexity, it makes it harder to manage and even understand, especially for newcomers. And the thing is, your most views are probably going to be simple lifts of plain views, with only few more powerful and complex ones you ever need. And you can even try to squeeze further views into plain lifts by extract the stream complexity out of the view, e.g. by what the folks doing Redux call "action creators".

Now the `dispatch` will send all our actions down to the action aka intent stream (which is the drivers' responsibility behind the scene we don't need to care about). What we need is to write a reducer, which is again a simple pure function like again in Redux/Elm/whatever...:

```js
const reducer = (state, action) =>
   // or whatever
   state.concat(action)
```

So again we have a plain pure dumb function unaware of streams that can be again mapped over any state stream, via the standard Functor interface, to rise to a "proper" more powerful stream-based reducer as is currently  used in Cycle in all possible cases. But again, a lift of a dumb thing is always simpler than the real thing, and may just work fine for many cases. And if it doesn't, you can always switch to the real thing.

Another nice feature that might be worth noting, if I am not missing anything, is the absence of any higher order streams aka streams of streams for such a lift. At least as long as you don't create any new streams inside the reducer of the view. Which is why I find it simpler to pass existing streams from outside rather than creating new ones. Then you never need to `flatten`!

So now without any framework you can create your action (aka intent) stream, then `scan` your reducer over it

```js
// get streams from our library factory, to be done by drivers in Cycle
const actions = Stream()
const states = actions.scan(reducer, initState)
```
then pass it to your lifted view
```js
// shameless use of our view's curry
const vnodes = states.map(view(actions))
```

or pass directly into the more powerful stream-based `view`
```js
// view: stream -> stream -> stream
const vnodes = view(actions)(viewStream)
```

and finally to whatever vnode render driver we want to use (hyperscript, snabbdom, ...):
```js
vnodes.map(render)
```
and that is it.

Of course, that last step should be taken care of by drivers in Cycle, so we shouldn't need to worry about it. We would just pass the vnode stream to the sink as usual in Cycle.

Now the beauty is, in most cases, both view and reducer  are simple pure dumb functions, completely unaware of streams. Exactly as you see in the (good parts of) traditional frameworks. And -- no more selectors! Instead you pass the additional `dispatch` argument that you can treat as your callback function, which is very easy and natural for anyone using the traditional way, and so making easier to onboard new users. 

And you instantly see which `vnode` emits the action, and you see it right inside your view. And this is substantial improvement feature in my view, the lack of which I have seen mentioned by people as one of the "problems" with the selector approach. It is very likely that your view will have many selectors but you only pass single dispatcher to it. So it feels easier to "reason about" as everyone likes to say, and more "scalable" to invert the control from the stream reaching out for selectors to the vnode dispatching the action. 

I have [noticed the recent discussion about onboarding new users](https://github.com/cyclejs/cyclejs/issues/579) and to give my few cents, the selector based approach is one of the things that might repel many newcomers. And even some experienced programmers [seem to feel the same](http://www.christianalfoni.com/articles/2016_04_06_CycleJS-driven-by-state):

> It is indeed very weird that our view says nothing about how it changes state and our state change logic just has some random class names it listens to. This selector also has some challenges thinking scalability. Imagine an application with hundreds of elements and you depend on classnames to find your elements. It is very fragile. Maybe we can do something about that.

So the problem is there, and I understand the Cycle has its reasons to do things its way and it would be too much efforts to change. 

But what about an add-on built on top of Cycle that would allow me to write my plain dumb views and reducers that way? And even real ones with action stream passed to the view as argument, so I can avoid the "flattening" rope?

The event module is already provided by the `snabbdom`, and if activated, I can go and `dispatch` my actions directly from the view. That actions will then appear in my reducer where I write the logic to update the state stream. Which will be received by the view to update the DOM and the cycle is closed :)

To conclude, I'd like to apologise in advance for any possible ignorance on my part, from being unaware of other problems, that might make my proposal less realistic than it looks :)
In any case I'd be very interested to hear how the Cycle community feels about this approach.

Finally, I need to quote [the very interesting Meiosis project](https://github.com/foxdonut/meiosis), where I have learned from, as well as from the inspiring [`mostjs` todos example app](https://github.com/briancavalier/most-todomvc/blob/master/src/index.js)
