### ISSUE TITLE
Strange behavior of "isolate" over time

### ISSUE THREAD

**Issue by datokrat** [cyclejs/cyclejs#507]
I'm trying to implement an other possibility for solving the collection problem but I'm facing problems with "isolate".

This jsbin works perfectly: https://jsbin.com/decariwidi/1/edit?js,output
It simply displays two isolated components how they evolve over time. Finally, we see on the screen
* Article 1b
* Article 2b,
which is the second state of the two components.

An app created with create-cycle-app (so, using NPM and RxJS 4 with Typescript and Webpack), however, gives me a different result. CycleDOM and isolate seem to "forget" to update the second article.

* Article 1b
* Article 2a

Is this behavior expected?

This is my app.ts:
```typescript
import {VNode, div, span, ul, li} from '@cycle/dom'
import isolate from '@cycle/isolate';
import {DOMSource} from '@cycle/dom/rx-typings'
import * as Rx from 'rx'

export type Sources = {
  DOM: DOMSource
}

export type Sinks = {
  DOM: Rx.Observable<VNode>
}

function Test1({ inner }: any) {
  return {
    DOM: Rx.Observable.of(span(["Article 1a"]), div(["Article 1b"]))
  }
}

function Test2({ inner }: any) {
  return {
    DOM: Rx.Observable.of(span(["Article 2a"]), span(["Article 2b"]))
  }
}

export function App (sources: Sources): Sinks {
  const a1 = isolate(Test1, "article-0")({ DOM: sources.DOM });
  const a2 = isolate(Test2, "article-1")({ DOM: sources.DOM });
  
  const stubDom$ = Rx.Observable.combineLatest(a1.DOM, a2.DOM, (a, b) => {
    return ul([
      li([
        a,
      ]),
      li([
        b,
      ])
    ])
  });
  
  const sinks = {
    DOM: stubDom$,
  };
  return sinks;
}
```

**Comment by hiroqn** [comment]
your problem may com from rx.
i didnt run, but you can check stream value like under code

```
  const sinks = {
    DOM: stubDom$.do(console.log),
  };
```
and printed vnode stream is expected one (maybe you get 4 log) -> isolate or dom driver problem
vnode stream is wrong (maybe you got 1~3 log ) -> isolate or dom driver problem

**Comment by datokrat** [comment]
Yes, I've already played around with logging and the output seems totally valid. I will extend the sample so that it is possible to reproduce the logging output - as far as I can decide, the output corresponds to what I expected.

**Comment by staltz** [comment]
@datokrat I highly recommend (before I try to debug deeper what's going on) that you migrate to RxJS v5. Soon in Cycle.js we will drop support for RxJS v4 now that v5 is officially released.

**Comment by datokrat** [comment]
Well, okay, I also tried it out with RxJs v5 and it did not help. Instead, xstream works like a charm!
So I seem to have mistaken suspecting Cycle.js to cause the problem. Here's the working snippet, it generates the correct output:

```ts
import { VNode, div, span, ul, li } from '@cycle/dom'
import isolate from '@cycle/isolate';
import { DOMSource } from '@cycle/dom/xstream-typings'
import xs, { Stream } from 'xstream'

export type Sources = {
  DOM: DOMSource
}

export type Sinks = {
  DOM: xs<VNode>
}

function Test1({ inner }: any) {
  return {
    DOM: xs.of(span(["Article 1a"]), div(["Article 1b"]))
  }
}

function Test2({ inner }: any) {
  return {
    DOM: xs.of(span(["Article 2a"]), span(["Article 2b"]))
  }
}

export function App(sources: Sources): Sinks {
  const a1 = isolate(Test1, "article-0")({ DOM: sources.DOM });
  const a2 = isolate(Test2, "article-1")({ DOM: sources.DOM });

  const stubDom$ = xs.combine(a1.DOM, a2.DOM).map(([a, b]) => {
    return ul([
      li([a]),
      li([b]),
    ])
  });

  const sinks = {
    DOM: stubDom$,
  };
  return sinks;
}
```
