### ISSUE TITLE
Avoid CommonJS in Cycle DOM codebase

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#509]
To better support tree-shaking tools that assume ES2015 modules.

**Comment by thiagoarrais** [comment]
Can you provide some more context here? Maybe an instance of CommonJS usage that you want to get rid of...

**Comment by jvanbruegge** [comment]
basicly replace any `require` call with es6 imports

basicly just cloning the repo, grepping for require (i suggest `the_silver_searcher`), editing those files

**Comment by thiagoarrais** [comment]
Thanks, @jvanbruegge! I did a quick grep and it seems like there are more than 14k occurrences.

I'll see if I can come up with a sed script or something and report back.

**Comment by thiagoarrais** [comment]
btw, I don't know if github allows it, but... Can you assign this issue to me?

**Comment by jvanbruegge** [comment]
you have to limit the search to `src` folders

**Comment by thiagoarrais** [comment]
Indeed: most occurrences were inside `dom/node_modules`. I couldn't find any occurrence under `dom/src`. Maybe this issue is already solved?

**Comment by thiagoarrais** [comment]
Indeed: most occurrences of `require` were inside `dom/node_modules`. I couldn't find any under `dom/src`, though.

Maybe this issue is already solved?

**Comment by thiagoarrais** [comment]
Can't find any occurrences of `exports` either...

**Comment by thiagoarrais** [comment]
Did a git bisect and the last require statement went down with commit f459adaf51. This issue is probably stale.

**Comment by jvanbruegge** [comment]
did a quick ag search, this is the result:
```
ag require --ignore node_modules --ignore examples/ --ignore yarn.lock --ignore docs --ignore test --ignore lib --ignore package.json             
html/src/makeHTMLDriver.ts
5:const init: Init = require('snabbdom-to-html/init');
6:const modulesForHTML: ModulesForHTML = require('snabbdom-to-html/modules');

jsonp/src/index.ts
4:import jsonp = require('jsonp');

devtool/src/panel/view.ts
14:    p('This DevTool requires that your app is built using the following ' +

devtool/README.md
11:This DevTool requires that your app is built using the following packages:

dom/CHANGELOG.md
23:* **dom:** switch from require() to import statements for es6 map polyfill ([f459ada](https://github.com/cyclejs/cyclejs/commit/f459ada))

time/src/mock-time-source.ts
14:const combineErrors = require('combine-errors');

time/src/scheduler.ts
2:const makeAccumulator = require('sorted-immutable-list').default;

time/src/time-driver.ts
11:const requestAnimationFrame = require('raf');
12:const now = require('performance-now');

time/src/assert-equal.ts
3:const variableDiff = require('variable-diff');

time/src/run-virtually.ts
1:require('setimmediate');

http/src/index.ts
15: * - `url` *(String)*: the remote resource path. **required**
```

**Comment by thiagoarrais** [comment]
Oh, right... I thought the issue was limited to cycle dom...

Will take a look at that!

**Comment by thiagoarrais** [comment]
So far I've tried changing

    const combineErrors = require('combine-errors');

to

   import combineErrors from 'combine-errors';

As I understand, this is the equivalent CommonJS/TS syntax for importing the default export from `combine-errors` and naming it `combineErrors`. But I keep getting this error:

    Could not find a declaration file for module 'combine-errors'

I'm not sure what I'm supposed to do here. Judging [from the Typescript docs][1] it seems like one can add a `.d.ts` file to some kind of type definitions repo so that it becomes possible to say

    npm install --save @types/combine-errors

I'm still learning both ES6 and TS. Maybe I'll be able to come back to this once I level up some more.

If anyone else wants to grab this, please do.

 [1]: https://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html

**Comment by SteveALee** [comment]
@thiagoarrais 

To import a commonjs default export in typescript the format is actually neihter that you tired :) See the modules docs for TS

`import combineErrors = require('combine-errors')`;

The error indicate the file cannot be found and as you did't prefix your file path with `.\` I'm pretty sure it will be copying node lookup and it will looking for the file in node_modules. Perhaps that is not correct?

If the file is is plane js then yes, you will need to provide a .d.ts to give what they call "ambient declations" for the types. There are various approaches for doing that. but if it is a npm module try making `types@combine-errors` a dependency. If that is part of cycle (or extras) the types are there

**Comment by thiagoarrais** [comment]
In this specific case, `combine-errors` is an external npm module. [Here it is][combine-errors-npm]. I guess this is also the case for every other occurrence of CommonJS requires. I've also tried to install the corresponding @types depencency with no success...

:disappointed: 

[combine-errors-npm]: https://www.npmjs.com/package/combine-errors

**Comment by thiagoarrais** [comment]
How can I test the use of tree shaking tools with Cycle.js? I've found the [webpack guide][1], but I can't easily see how to use it.

[1]: https://webpack.js.org/guides/tree-shaking/

**Comment by jvanbruegge** [comment]
There is the bundleAnalyse plugin and the stats plugin. The stats can be used to see the module dependencies. See my polyfill WIP PR

**Comment by jvanbruegge** [comment]
But tree shaking is broken ATM, also see the PR

**Comment by thiagoarrais** [comment]
How can we demonstrate that tree shaking is broken? Can you give me a one-liner for that? (Remember I'm a JS/TS newbie)

**Comment by jvanbruegge** [comment]
Import the time driver from `@cycle/time`, webpack removes the `mockTimeSource` but still pulls in all dependencies of the `mockTimeSource`

**Comment by staltz** [comment]
So I guess this is done now?

**Comment by micahscopes** [comment]
@staltz I don't think this is fixed.  I'm having trouble with a very basic rollup project, even when using `rollup-plugin-commonjs`.  The culprits are those `require` calls.

**Comment by Widdershin** [comment]
@micahscopes: I have made a PR that removes all usages of `require` from the `@cycle/time` codebase. https://github.com/cyclejs/cyclejs/pull/761

After that is merged hopefully Rollup will work.

**Comment by Widdershin** [comment]
@micahscopes `@cycle/time@0.11.0` is now released with no more `require` calls, let me know if this solves your problem 😄
