### ISSUE TITLE
@cycle/rxjs-run imports all of RxJS, leaving no method for patching subsets of RxJS in imports

### ISSUE THREAD

**Issue by drewdeal** [cyclejs/cyclejs#510]
I confirmed that: `import {run} from '@cycle/rxjs-run';` imports all of RxJS

I have been going through my project to reduce bundles by changing imports like:
`import {Observable} from 'rxjs'`
to:
`import {Observable} from 'rxjs/Observable'`

Method for confirming...
1) When I comment out that line,  bundle size decreases  by 1.6MB.
2) After commenting rxjs-run, i do get desired bundle decrease, only importing {Observable}, etc.

Impetus from RxJS readme...
From https://github.com/ReactiveX/rxjs ::
> 
> To import only what you need by patching (this is useful for size-sensitive bundling):
> 
> import { Observable } from 'rxjs/Observable';
> import 'rxjs/add/observable/of';
> import 'rxjs/add/operator/map';
> 
> Observable.of(1,2,3).map(x => x + '!!!'); // etc

My versioning:

```
  "dependencies": {
    "@cycle/rxjs-run": "3.0.3",
    "rxjs": "5.0.0-beta.11",
    "@cycle/dom": "12.1.0",
    "@cycle/history": "^4.0.0",
    "@cycle/isolate": "1.4.x",
    "@cycle/storage": "3.0.0-rc2",
    "jquery": "^3.1.1",
    "history": "^3.0.0"
  },
```

**Comment by hiroqn** [comment]
update rxjs-run 3.3
https://github.com/cyclejs/cyclejs/blob/master/rxjs-run/src/index.ts

**Comment by staltz** [comment]
@drewdeal I don't understand how, because rxjs is just a peer dependency in `rxjs-run`, so we don't embed that dependency inside the latter. Use npm v3 and install `rxjs` as a separate dependency in your project.

This is what we do with rxjs: https://github.com/cyclejs/cyclejs/blob/master/rxjs-adapter/src/index.ts#L8-L11

**Comment by evenchange4** [comment]
I quick test `@cycle/rxjs-run@7` in my project with [source-map-explorer](https://www.npmjs.com/package/source-map-explorer):

## @cycle/rxjs-run 6.1.0

<img width="368" alt="2017-03-17 09 35 33" src="https://cloud.githubusercontent.com/assets/1527371/24025453/671692d4-0af5-11e7-85f7-e8515a32e5f4.png">

## @cycle/rxjs-run 7.0.0

<img width="258" alt="2017-03-17 09 28 08" src="https://cloud.githubusercontent.com/assets/1527371/24025458/6dbc5fd8-0af5-11e7-9b75-6c2d86ab5fe5.png">

@drewdeal You should try it. 🙌
