### ISSUE TITLE
How to access the real DOM ?

### ISSUE THREAD

**Issue by vimniky** [cyclejs/cyclejs#511]
Hi ! I'am new to cycle and I was wondering what's the best way to access the `real DOM`.

Say how can do the following in cycle  ?

```js

 var divHeight = $('.myDiv').height()

```

Thanks !

**Comment by mightyiam** [comment]
@vimniky:
https://github.com/snabbdom/snabbdom#hooks

**Comment by staltz** [comment]
Hi @vimniky. Check also `DOMSource.select('.myDiv').elements()`
https://github.com/cyclejs/cyclejs/tree/master/dom#-makedomdrivercontainer-options

**Comment by vimniky** [comment]
Thanks ^_^ !
