### ISSUE TITLE
Migrate browser tests to BrowserStack and/or Karma

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#514]
Issues:
- SauceLabs browser runs sometimes randomly fail
- Testem *might* be sensitive to history (refresh/back/etc) changes, Karma *might* not (because `history` repo uses Karma to test in browsers)
- Cycle History is not being tested in multiple browsers due to the item above
- Review which browsers should we be testing against

**Comment by TylorS** [comment]
I can attempt to tackle the switch to Karma, as I have some experience with it on some other projects.

**Comment by staltz** [comment]
Done by Tylor. Thanks!

(I think we could keep Testem for DOM and HTTP, for the time being. History was the critical one)
