### ISSUE TITLE
Make @cycle/isolate available in tricycle

### ISSUE THREAD

**Issue by anilanar** [cyclejs/cyclejs#519]
**Code to reproduce the issue:**
Try doing `import isolate from '@cycle/isolate` in tricycle

**Expected behavior:**
It should work.

**Actual behavior:**
`Error: Cannot find module '@cycle/isolate'`

**Comment by anilanar** [comment]
I made a PR to the relevant repo: https://github.com/Widdershin/tricycle/pull/20

**Comment by Widdershin** [comment]
Fix now live, thanks @anilanar
