### ISSUE TITLE
Migrate website to Flatdoc

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#520]
http://ricostacruz.com/flatdoc/

- It looks good and clean by default
- Responsive
- Has this nice side-by-side code and description
- Allows a long left-side table of contents (currently, we have a max limit!)
- Used by https://facebook.github.io/reason/ too

It might actually be a fairly easy transition since our existing docs are mostly markdown, and this Flatdoc is based on markdown. 

I'm interested in also embedding the docs for each package (cycle dom, http, etc) into the same webpage. Currently, you need to navigate to the README for each package

TODO list:

- [x] Start using flatdoc
- [x] Place docs in this monorepo under `/docs`
- [x] Generate html page for the API reference of each package
- [x] Generate documentation.html from all markdown chapters
- [x] Create releases.html
  - [x] Fix links to all issues
- [x] Redo frontpage
- [x] A bit bigger font for menu on mobile
- [x] Fix content for Cycle Unified
  - [x] frontpage
  - [x] documentation pages
  - [x] drivers.md: The sink given to the driver is of the same type as foo-run
  - [x] drivers.md: The source given to main() is the complex source class instance or just an xs stream
  - [x] Update badges on top-level README
- [x] Use `<base>` in `<head>` for links
- [x] Put CycleConf there temporarily
- [x] Update URLs to direct scripts in getting started, after release of unified
- [ ] Create community.html ?

**Comment by FeliciousX** [comment]
I would love to help here..

is this the source code of cyclejs website you're referring to? https://github.com/cyclejs/cyclejs.github.io

**Comment by staltz** [comment]
Great! Thanks for wanting to help :)

Yes that's the one I'm referring to. I suggest doing the migration in a new repo. We can then figure out how to merge it back in.

**Comment by FeliciousX** [comment]
:+1:

**Comment by staltz** [comment]
Work on this is happening on branch unified-docs https://github.com/cyclejs/cyclejs/tree/unified-docs
Thanks @FeliciousX for kick starting it!

**Comment by mightyiam** [comment]
I've just noticed that the latest flatdoc commit was December 2015. Is it so perfect that no changes are required for a whole year?
