### ISSUE TITLE
input() missing {attrs: } around {type: 'range', ...} in last BMI source code on basic-examples.html

### ISSUE THREAD

**Issue by davidmsvetlecic** [cyclejs/cyclejs#521]
**Code to reproduce the issue:**
Correct:   input('.weight', {attrs: {type: 'range', min: 40, max: 140}})
Incorrect: input('.weight', {type: 'range', min: 40, max: 140, value: weight})

**Expected behavior:**
input slider

**Actual behavior:**
input field.

**Versions of packages used:**
?

**Comment by staltz** [comment]
Thanks for solving it :)
