### ISSUE TITLE
useCapture not behaving as intended

### ISSUE THREAD

**Issue by FeliciousX** [cyclejs/cyclejs#522]
`useCapture` is not behaving as intended. Comparing with vanilla javascript `useCapture` behavior

**Code to reproduce the issue:**
https://esnextb.in/?gist=d6e1d3ae7c686cc51e294f9247910548

**Expected behavior:**
clicking on any element inside the `div` will trigger `focus` and `blur` event of the `div`

**Actual behavior:**
`div` focus event is not triggered

**Versions of packages used:**

```json
{
  "name": "esnextbin-sketch",
  "version": "0.0.0",
  "dependencies": {
    "@cycle/run": "1.0.0-rc.9",
    "@cycle/dom": "15.0.0-rc.2",
    "xstream": "10.2.0"
  }
}
```

**Comment by FeliciousX** [comment]
i tried creating a `gist` from `esnextb.in` but there's an error while doing so.. :(

**Comment by staltz** [comment]
I'm still not sure what is going on, so I labeled it as "labels pending", because technically `focus` will always use `useCapture:true` in Cycle DOM.

**Comment by FeliciousX** [comment]
i updated it to use esnextb.in so it's easier to see

**Comment by staltz** [comment]
I think this is working as expected according to this Webpackbin I just set up with the latest versions https://www.webpackbin.com/bins/-KlIeoh9fSVUTAFhPjZG

**Comment by FeliciousX** [comment]
@staltz doesn't seem like it

https://gyazo.com/eb5dad0e193c72212560184494786d27

this is a gif of the behavior from your webpackbin

clicking directly on the input element doesn't trigger the focus event. you still have to click on the div itself

Frikki did ask about motorcycle if they face the same problem. if you check the [issue](https://github.com/motorcyclejs/motorcyclejs/issues/33) and the [bin](https://esnextb.in/?gist=3b64c64a95090381e6aa41ef92ea5fbc) their's behave like vanilla still

😕

**Comment by staltz** [comment]
> clicking directly on the input element doesn't trigger the focus event. you still have to click on the div itself

But the vanilla one also behaves like this.

**Comment by staltz** [comment]
Oh, okay, I saw the gif now. Sorry

**Comment by mazamachi** [comment]
I faced the same bug. Has anyone found the reason for this bug?
My environment is 

Google Chrome: 63.0.3239.84 (Official Build)
Mac OS: 10.13.1
@cycle/dom: 20.1.0
