### ISSUE TITLE
Good time for a component library/repository?

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#523]
Is it a good time to start a Cycle.js component library/repository?

Myself and @yarom82 are considering it.

**Comment by Widdershin** [comment]
I think this is a great idea.

If you wanted to put it somewhere central with visibility, you would be very welcome to create your repository in the [Cycle.js Community](https://github.com/cyclejs-community/) organization.

That way you might attract more users, contributors and maintainers.

I have invited you and @yarom82 to be community members 😄

**Comment by mightyiam** [comment]
https://mightyiam.github.io/cyclejs-web-components/

I'll be happy to transfer it into the community repository when it starts looking promising.

**Comment by mightyiam** [comment]
Update:
I got some styling in there. I've discovered http://bulma.io/.

Seems suitable for Cycle.js components.

But I'm not talking about styling them. No... the components are to be only JavaScript (source is TypeScript (thanks, @staltz!)).

I have automatically generated documentation in place. Parsed from the source code of each component, using the TypeScript parser.

There are only three example components. I hope they're in the right direction, though.

No tests, so far.

I put up a basic readme...

And now it is confirmed that this project will be participating in the third Goodness Squad event:
https://www.meetup.com/JavaScript-Israel/events/237750614/

Expect exposure to Cyclje.js in Israel!

I would like ya'll to take a look at this and propose general API guidelines. If people are going to contribute something meaningful (components) then I better get my head around what it means to be a good Cycle.js component.

So how about some contributions from ya'll, before the 15th?

An accordion, tabs, a drop-down menu, a type-ahead... I'm not even sure what's worth making into a Cycle.js component. do you?
