### ISSUE TITLE
@cycle/http wrong error handling (not every exception has .response)

### ISSUE THREAD

**Issue by Alex0007** [cyclejs/cyclejs#524]
**Code to reproduce the issue:**

Node.js code:
```js
HTTP: Observable.of({
    url: 'http://localhost:9999', // <- no webserver here
    category: 'coreStatus'
  })
```

**Expected behavior:**
Some sort of connection error that can be handled

**Actual behavior:**
```
/home/alex/Development/projects/proj/node_modules/@cycle/http/lib/http-driver.js:82
                        err.response.request = reqOptions_1;
                                             ^

TypeError: Cannot set property 'request' of undefined
    at /home/alex/Development/projects/proj/node_modules/@cycle/http/lib/http-driver.js:82:46
    at Request.callback (/home/alex/Development/projects/proj/node_modules/superagent/lib/node/index.js:615:12)
    at ClientRequest.<anonymous> (/home/alex/Development/projects/proj/node_modules/superagent/lib/node/index.js:567:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:189:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at emitErrorNT (net.js:1280:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

**Versions of packages used:**
```
    "@cycle/http": "^11.3.0",
    "xstream": "^10.2.0",
    "@cycle/rxjs-run": "^3.3.0",
    "rxjs": "^5.0.2",
```

**Comment by staltz** [comment]
Thanks for reporting.

**Comment by mightyiam** [comment]
This line:
https://github.com/cyclejs/cyclejs/blob/a96243e3bf78ed4d43b14dc35e72128579bc6bde/http/src/http-driver.ts#L92

`err.response` can be undefined.

Reproduce in the browser by simply being offline.

Unlike what the title could suggest, this seems to be in the browser, as well, from my experience.

**Comment by staltz** [comment]
HTTP v13.2 is being released with this fix.

As an interesting note, the culprit in this issue was the `any` type, which puts trust on the developer instead of the compiler. I believe the more we use strong TypeScript types, the less of these kinds of issues we will have.
