### ISSUE TITLE
'use strict' causing error deep in dependency chain

### ISSUE THREAD

**Issue by dobrite** [cyclejs/cyclejs#53]
[This commit](https://github.com/Raynos/error/commit/b23da9c82bdad8c45acd9e36bee56c30619ad4e1) of `error` in 4.3.0 causes an error when in strict mode: 

``` javascript
Uncaught TypeError: Cannot assign to read only property 'name' of function createError(opts) {
            var result = new Error()... <more>
```

The line is [here](https://github.com/Raynos/xtend/blob/master/mutable.js#L9).

Assigning the `name` property of a function is usually a no-op (non-standard though) but in strict mode it throws.

`error` is a dependency of `virtual-dom`.

This is an error that happens when trying to run the example code in the README under chrome with webpack.

I'm thinking the issue might lay with `error` but am unsure. I filed an issue there too. :smile:

**Comment by sunwukung** [comment]
Just for posterity, I raised this [issue](https://github.com/Raynos/xtend/issues/25) after encountering the same error.
