### ISSUE TITLE
Update Tricycle to use Cycle Unified

### ISSUE THREAD

**Issue by Widdershin** [cyclejs/cyclejs#534]
I intend to do this, just opening an issue so here so it can be tracked for OpenCollective.

@staltz as part of this shall I move tricycle into this organization? I could keep a fork hosted at the old repository and have a banner redirecting to the new URL.

**Comment by staltz** [comment]
Sure, let's do it. Do you have rights for transferring the repo?

**Comment by Widdershin** [comment]
I've updated tricycle for unified and pushed to this organization. It's now online at https://cyclejs.github.io/tricycle/. We can update the docs to point there and I'll update the old repo to reflect that future development will be on the new one.

I'll keep the old URL online and up to date so we don't have dead links.
