### ISSUE TITLE
Bad call to matchesSelector (second arg empty string)

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#545]
DOM exception in call to `Element.prototype.matchesSelector` (or whatever flavor gets selected there).
Because the second argument is an empty string.

This line:
https://github.com/cyclejs/cyclejs/blob/0789c082266326bf74211e6658b1cb9da6b19ed4/dom/src/matchesSelector.ts#L16

Notice that the commit above many not be correct because there are no tags (probably since multi-package repo).

**Code to reproduce the issue:**

`git clone`, `git checkout repro.0`, `npm i`, `npm run dev` and then try the demo of the click sink of the link component. Try to click on the link.

For reference, this is the commit:
https://github.com/mightyiam/cyclejs-web-components/commit/6071ba61ff9caeaa15a7acee24b11ddaf257f396#diff-799846bd6de8d46b58d81c5f7d164aecR31

**Versions of packages used:**

```
├── @cycle/dom@16.0.0
├── @cycle/isolate@2.1.0
├── @cycle/run@3.0.0
```

**Comment by TylorS** [comment]
Here's a reproducible example that @Frikki made a few months back 
https://esnextb.in/?gist=4d38605258041d71702b65107a194b61

**Comment by jvanbruegge** [comment]
This is now fixed in `@cycle/dom` v21 :tada:
