### ISSUE TITLE
HTTP driver's exported Response type incomplete

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#549]
The interface `Response` from the HTTP driver doesn't seem to reflect all of [what superagent provides on the response object](http://visionmedia.github.io/superagent/#response-properties).

This results in type errors like `Property 'ok' does not exist on type 'Response'.`.

To best reflect what is on superagent's response, perhaps it would be best to import the type from superagent, correct?

But superagent does not seem to contain type definitions.

Is it possible to import from [its @types package](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1c80f69f6e13770589b3d549b556c1529dd7b085/superagent/index.d.ts#L57-L81) and use that, instead of our current `Response` type?

Or is it the case that the HTTP driver does not provide the superagent response object as a whole? It seems that it is indeed the response from superagent, with the addition of the `.request`.

So, how about it?

**Comment by staltz** [comment]
> Is it possible to import from its @types package and use that, instead of our current Response type?

Yes this would be the correct way to proceed. Thanks for raising this issue.

**Comment by staltz** [comment]
HTTP v13.2 is being released with this fix.
