### ISSUE TITLE
Monorepo makes it impossible to temporarily `npm install` a fork from git

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#550]
Let's say I submit a pull request on cyclejs/cyclejs and then I can't wait for a release with that fix to be made. If it wasn't a monorepo, I would have used `npm install` with a git url of my fork, with the commit where the issue is fixed. Since it is a monorepo, I can't seem to be able to do that.
Se perhaps npm can install from subdirectory of git url? Nope:
https://github.com/npm/npm/issues/2974
So, perhaps there's an API somewhere to get a tarball of a subdirectory of a repo in github? I couldn't find it.

What would you do?

**Comment by Steelfish** [comment]
Npm link your local copy of the fork's package?

**Comment by whitecolor** [comment]
I would suggest build and publish your own version of the package.

**Comment by mightyiam** [comment]
@Steelfish thanks. Thoughts: if this is a project that I'm doing all by myself this is plausible. There isn't a system in place to reproduce that environmental factor. That's why I (we all) use npm, right? Even moving between a desktop and a laptop, for example, would require doing this over again. Oh, and what about CI? How would that work in CI?

@whitecolor Thanks. I don't have a private npm repo. Spamming the npm registry like that seems reasonable to you? I know it contains a lot of half-baked/unfinished/experimental or otherwise immature code anyway. Yeah, maybe I'll do that.

But! There must be a way to do it with npm. And I'm not saying that breaking this monorepo apart would be the correct move. I think that https://github.com/npm/npm/issues/2974 would be the correct move, is how I would prefer things go.

Any more ideas?

Anyway, this is an actual issue, isn't it? Should remain open until a clear workflow is.. clear. Is how I see it.

**Comment by ntilwalli** [comment]
This is not a cyclejs issue, it's a deployment issue.  This is how I've handled it in the past...
1) Fork the repo, 
2) make the change
3) Submit PR
4) Install the forked repo as a git submodule of your project
5) Change package.json to install relevant packages locally from the submodule until the release is made
6) When release is made, change back to using npm registry directly
7) Delete submodule.

**Comment by whitecolor** [comment]
> spamming the npm registry like that seems reasonable to you? 

You may publish in npm under you scoped username like `@mightyiam/cycle-http` whatever, they can be public, no need in npm paid account.

**Comment by whitecolor** [comment]
@mightyiam btw I've opened the issue in `yarn` on this a while ago https://github.com/yarnpkg/yarn/issues/1570

**Comment by staltz** [comment]
Yeah this is an npm/yarn/package.json/git issue, not a cyclejs one, and we couldn't give up our monorepo simply because of this issue. The suggestions above seem good.
