### ISSUE TITLE
History interface does not allow exposing createHref, incompatible with cyclic-router

### ISSUE THREAD

**Issue by ntilwalli** [cyclejs/cyclejs#551]
I'm trying to update to Cycle Unified and while trying to update cyclic-router I noticed that the updated @cycle/history interface does not allow me access to `createHref` which sits on the raw `history` object.  My inclination is to submit a PR which adds a new driver function called `makeInjectHistoryDriver` which looks like:
```
export function makeInjectHistoryDriver(history: History | MemoryHistory): HistoryDriver {
  return function injectHistoryDriver(sink$: Stream<HistoryInput | string>) {
    return createHistory$(history, sink$);
  };
}
```
This new driver function is compatible with the way the history driver worked previously and will make porting cyclic-router more straightforward.  Any objections?

@staltz @TylorS

**Comment by staltz** [comment]
Let's try to discuss here and not in the PR (unless it's about the code submitted). I'm starting to understand the motivations here, after I looked at what exactly does `createHref(location)` do. It basically just returns ``${basenameFromHistoryObj}${createPath(location)}``. Basically a way of serializing pieces of location data into one string.

Your proposal is a driver factory that takes the history obj as argument. Currently, we can pass history obj **build options** as argument.

I would propose that we change the signature

```ts
function makeHistoryDriver(options?: BrowserHistoryBuildOptions): HistoryDriver
```

to

```ts
function makeHistoryDriver(options?: BrowserHistoryBuildOptions | History): HistoryDriver
```

Which would solve your case. It would build upon the idea that `makeHistoryDriver` is the most generic driver factory, while `makeServerHistoryDriver` and `makeHashHistoryDriver` are specialized driver factories.

**Comment by ntilwalli** [comment]
@staltz I've updated the PR according to your proposal

**Comment by staltz** [comment]
Got a thumbs up from Tylor (in private), so let's do it.

**Comment by ntilwalli** [comment]
Just FYI, The PR is ready to go.
