### ISSUE TITLE
Is it possible/useful to switch stream adapter dynamically?

### ISSUE THREAD

**Issue by ntilwalli** [cyclejs/cyclejs#553]
Is it possible to switch the stream adapter dynamically?  This came up while trying to update `cyclic-router` to Unified.  There are tests written for both rxjs and xstream and the are imported from one file: https://github.com/cyclejs-community/cyclic-router/blob/master/test/index.js

As far as I understand, the `setAdapt` call happens when the `@cycle/___-run` module is loaded and it applies globally once and there is no way to to dynamically change which `adaptStream` function gets called once it's set.  One could argue that testing both stream libraries like this is redundant/superfluous, and the need to switch stream adapters mid-app is not an important use case.  I just wanted to get some feedback on this use-case or whether I'm missing a possible approach...

**Comment by Widdershin** [comment]
You can achieve this by calling `setAdapt` in a `before` block in your tests.

See this example from [redux-cycles](https://github.com/cyclejs-community/redux-cycles/blob/master/test/createCycleMiddleware.test.js#L156) 

@cycle/time uses [this approach](https://github.com/cyclejs/time/blob/master/test/most.ts#L7) as well.

One caveat with this approach is that you will also need to call `setAdapt(stream => stream)` for your xstream tests.
