### ISSUE TITLE
HTTP: Bad request URL throws uncaught TypeError

### ISSUE THREAD

**Issue by wyqydsyq** [cyclejs/cyclejs#554]
It seems that when passing a request with a URL that can't be requested (invalid or nonexistent host) the HTTP driver still assumes that the `err` it gets has a `.response` property, I'm guessing that in some cases the underlying `request` libary returns a plain error if it was unable to construct the request to begin with.

I feel like the HTTP driver should be gracefully catching errors like this and passing them back via the `sources` so they can be handled the same way as normal response errors (e.g. with `xs.replaceErrors()`).

I've had a quick peek at the source and I think a possible easy solution would be to wrap the assignment on https://github.com/cyclejs/cyclejs/blob/master/http/src/http-driver.ts#L92 with a check for the presence of `err.response` before trying to assign `err.response.request`, and either not doing it or converting the plain error into a request error before trying to do that assignment.

Backstory if it helps:

In setting up an Isomorphic Cycle app where I want the initial page render to contain resolved HTTP responses (I'm wrapping my `Main()`'s `DOM` sink with `.take(1)`, responses that should resolve on server render aren't given a `.startWith()` making the app wait for them to emit before responding) I ran into a roadblock where relative URLs I had been previously using without issue on the client-side broke on the server (because `{url: '/api/hello'}` doesn't make sense in server context) so I decided to wrap my `Main()`'s `HTTP` sink with a `.map()` that appends the server hostname to relative URLs, at the time I was running this via an `ngrok` proxy using HTTPS and at the time doing `https://${ctx.host}${request.url}` worked until I tried it via `localhost` using just `HTTP` and my app would crash on each request with the following error:
```
TypeError: Cannot set property 'request' of undefined
     at /app/node_modules/@cycle/http/src/http-driver.ts:92:33
     at Request.callback (/app/node_modules/superagent/lib/node/index.js:672:3)
     at ClientRequest.<anonymous> (/app/node_modules/superagent/lib/node/index.js:600:10)
     at ClientRequest.g (events.js:291:16)
     at emitOne (events.js:96:13)
     at ClientRequest.emit (events.js:188:7)
     at Socket.socketErrorListener (_http_client.js:310:9)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at emitErrorNT (net.js:1278:8)
```

**Expected behavior:**
Requests to bad URLs are catchable using usual error handling

**Actual behavior:**
Requests to bad URLs throw an error

**Versions of packages used:**
```
    "@cycle/dom": "^16.0.0",
    "@cycle/history": "^6.0.0",
    "@cycle/http": "^13.1.0",
    "@cycle/run": "^3.0.0",
```

**Comment by raquelxmoss** [comment]
Hey 😄  is this the same things as #549?

**Comment by mightyiam** [comment]
Related to #524?

**Comment by wyqydsyq** [comment]
I believe it's a different issue, #549 seems to be about the exported TypeScript typings from Cycle HTTP not matching those of the underlying Request library.

My issue appears to be caused by the Cycle HTTP driver assuming that when it catches an error from the Request library the error object has a `response` property when it seems that isn't always the case. It looks like in my case `err` is something other than the expected error object.

**Comment by wyqydsyq** [comment]
Ah yep this is indeed a duplicate of #524 which for some reason I couldn't find when searching the repo issue history 🤷‍♂️
