### ISSUE TITLE
Restore our SauceLabs tests to normality

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#556]
They've been breaking because of recent changes in SauceLabs infrastructure.

Related: https://github.com/bermi/sauce-connect-launcher/issues/115

**Comment by mightyiam** [comment]
I see an array of fully passing SauceLabs browsers as an impressive feat.

**Comment by staltz** [comment]
The Continuous Integration Gods have shown favor towards the mortals https://travis-ci.org/cyclejs/cyclejs/builds/212052766

**Comment by mightyiam** [comment]
Pretty green browser support is pretty. Good job.
![screenshot_2017-03-17_13-37-37](https://cloud.githubusercontent.com/assets/635591/24041609/f2ed7e6e-0b16-11e7-8bd7-343805a4afa4.png)
