### ISSUE TITLE
Could you upgrade snabbdom in @cycle/dom

### ISSUE THREAD

**Issue by MidnightWonderer** [cyclejs/cyclejs#557]
I was affected by  
https://github.com/snabbdom/snabbdom/issues/252  
Could you upgrade the library in question to a newer version?  
Should I send you a PR for that?

**Comment by staltz** [comment]
Hi @MidnightWonderer , we already updated snabbdom version. Can you update your Cycle DOM version?

**Comment by MidnightWonderer** [comment]
Oops, I missed the major version.  
Pretty sure I have the latest but it is actually 15.0.0  
Sorry
