### ISSUE TITLE
CHANGELOG commit links are broken

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#558]
I believe it is everywhere, links like:
https://github.com/cyclejs/cyclejs/tree/master/packages/dom/commit/13cb6bc
instead of:
https://github.com/cyclejs/cyclejs/commit/13cb6bc

**Comment by staltz** [comment]
Fixed

**Comment by whitecolor** [comment]
@staltz check the latest link in https://github.com/cyclejs/cyclejs/blob/77f97b1deba51d9353210dbbf5b891f8597f5379/dom/CHANGELOG.md
dom: remove HTML driver from Cycle DOM (8a5aac7)

**Comment by staltz** [comment]
Yeah, that's the only broken link. I'll see what went wrong

**Comment by staltz** [comment]
Fixed
