### ISSUE TITLE
Sinks typing for `run` issue with interface

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#560]
```ts
interface MainSources {}

interface MainSinks {
  log: Stream<string>
}

const Main = (sources: MainSources): MainSinks => {
  return {
    log: xs.of('message')
  }
}

run(Main, { // is not ok
  log: () => ({})
})
```
The error is:

```
Argument of type '(sources: MainSources) => MainSinks' is not assignable to parameter of type '(sources: MainSources) => Sinks'.
  Type 'MainSinks' is not assignable to type 'Sinks'.
    Index signature is missing in type 'MainSinks'.
```
This is because of https://github.com/cyclejs/cyclejs/blob/master/run/src/index.ts#L276 

It is due to MainSink should satisfy `{[name: string]: FantasyObservable}` signature.

[We need to use `type` instead of `interface`](https://github.com/Microsoft/TypeScript/issues/14736#issuecomment-287817665) Though I alway before used `interface`s everywhere.

```ts
type MainSinks = {
  log: Stream<string>
}
```

But it is also possible to make it work with an `interface`, need to modify run typings, replace:

```ts
export function run<So extends Sources, Si extends Sinks>(
```
with
```ts
export function run<So extends Sources, Si extends FantasySink<Si>>(
```
where
```ts
type FantasySink<Si> = {[S in keyof Si]: FantasyObservable}
```

@staltz what do you think?

**Comment by staltz** [comment]
> But it is also possible to make it work with an interface, need to modify run typings, replace:

If it's possible to make it work with an interface, without bringing breaking changes, then great, I agree we could change it. A PR for this would be nice. The tricky corner cases to be careful with are https://github.com/cyclejs/cyclejs/blob/87228167c22751a7e8aa3f2892891f9b74d2fe52/run/test/index.ts#L57-L116

In general I'll try to teach using `type` instead of `interface`, though.

**Comment by staltz** [comment]
run v3.1 will be released with this. Thanks whitecolor
