### ISSUE TITLE
Runtime error with isolated DOM sink emitting `undefined`

### ISSUE THREAD

**Issue by chadrien** [cyclejs/cyclejs#563]
When using an isolation, the code will crash when the dom sink emits `undefined`. Emitting `undefined` in a non-isolated sink will just lead to nothing being rendered. So either it's a bug with dom isolation, either we maybe should make it so non-isolated dom also blarf on `undefined` emit so we would have a consistent behavior.

**Code to reproduce the issue:**
* https://www.webpackbin.com/bins/-Kg0-G3bhJREVL4uMkYj
* open dev tools
* click on the button
* watch the world burn

**Expected behavior:**
Depending on your opinion, either it should not crash on `undefined` being emited by isolated dom sink, either non isolated dom sink should throw on `undefined` emit as well

**Actual behavior:**
Runtime crash (happens in [`totalIsolateSink`](https://github.com/cyclejs/cyclejs/blob/master/dom/src/isolate.ts#L30), `Cannot read property 'data' of undefined`)

**Versions of packages used:**
* `@cycle/dom`: 16.0.0
* `@cycle/isolate`: 2.1.0
* `@cycle/run`: 3.1.0
* `xstream`: 10.3.0

**Comment by staltz** [comment]
This is quite a corner case, but given that snabbdom accepts null and undefined as a virtual node to be diffed, I think we should handle null and undefined, specially since non-isolated sink supports it.

Thanks.

**Comment by staltz** [comment]
Fixed and will be released in dom v17.1

**Comment by chadrien** [comment]
Sorry for the eventual useless and annoying github notification, but it's probably more important to say: thanks! :tada: :heart:
