### ISSUE TITLE
Handling HTTP response errors is unclear?

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#566]
This is my attempt to handle errors in a response stream:
![screenshot_2017-03-26_21-47-46](https://cloud.githubusercontent.com/assets/635591/24334149/dda8eb70-126d-11e7-8c1a-b07d2f3142d8.png)

And I get this:
![screenshot_2017-03-26_21-49-00](https://cloud.githubusercontent.com/assets/635591/24334157/0d4ad80c-126e-11e7-9bca-2fd49aa601f0.png)

But, this doesn't make any sense to me, because, I do think that I wish to have a `null` there, in place of an error.

And I do not wish to provide a hand-crafted object that is compatible with [`Response`](https://github.com/cyclejs/cyclejs/blob/3701efa730c5eac0130442dba0b6d4d322bae715/http/src/interfaces.ts#L43-L46). It extends from [superagent's `Response`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/superagent/index.d.ts#L57-L81).

But this is seemingly what [the docs](https://cycle.js.org/api/http.html) suggest I do:
![screenshot_2017-03-26_21-53-39](https://cloud.githubusercontent.com/assets/635591/24334179/b141b2be-126e-11e7-830b-37a8f05eeac1.png)

This seems to work, but it took a while to get it:
![screenshot_2017-03-26_21-58-08](https://cloud.githubusercontent.com/assets/635591/24334216/7ccb25f0-126f-11e7-9760-8ccb9140e17e.png)

Perhaps this could be made easier? Perhaps better documentation?

What's the correct solution?

**Comment by staltz** [comment]
Hi :)
Thanks for letting us know. Yes, the solution is a TypeScript cast. I think this is mostly a TypeScript issue (since it would work with JavaScript). I know we could make it more clear in the docs, but there are so many corner cases related to TypeScript casting, maybe it's out of scope for Cycle.js documentation.

**Comment by sveinburne** [comment]
@staltz I think the `replaceError` signature could be enhanced. Actually it is :
``` typescript
replaceError(replace: (err: any) => Stream<T>): MemoryStream<T>;
```
But I don't see why it should depends on the `MemoryStream` type parameter `T`. Why not replacing with :
``` typescript
replaceError<U>(replace: (err: any) => Stream<U>): MemoryStream<U>;
```
Now, no need to cast :-)
