### ISSUE TITLE
Is there a driver that can change the `document.title`?

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#570]
Or should I just make this in my own project code, because it is trivial?

Or should there be an `@cycle/document-title` driver?

Or what?

**Comment by staltz** [comment]
@mightyiam I think you can just make a one-line driver. Since this is so small I don't think it's worth making it an official driver, and there are many of these cases under the window and document API.
It might work well as a small npm module, like sindresorhus has many small ones.

**Comment by staltz** [comment]
By the way:

```js
run(main, {
  title: sink => sink.subscribe(t => document.title = t)
})
```
