### ISSUE TITLE
Cyclejs and "DOM affecting third party components"

### ISSUE THREAD

**Issue by cluelessjoe** [cyclejs/cyclejs#573]
Hi 

First of all thanks a lot for cyclejs: at least a clear and correct way to do UI !

However, I'm wondering how to integrate some not so clean third party components, like for example jquery ones, with properties to be given, callbacks and which manipulate the DOM themselves.

Is the right way to handle such code to do a dedicated driver? If so, any advice on the integration between the DOM driver and these drivers?

Thanks in advance

:)
cluelessjoe
NB : I created an issue for future reference on the topic

**Comment by staltz** [comment]
Hi!

Your question is pretty common, and the answer is usually [snabbdom hooks](https://github.com/snabbdom/snabbdom/#hooks), check them out.

We should probably write about this in our docs. :)

**Comment by cluelessjoe** [comment]
Thanks a lot, the answer was unexpected :)

I'll do a PR for the docs soon then.

**Comment by staltz** [comment]
> However, what do you do for the callback through these hooks ?

Can you be a bit more specific? I don't understand
:)

**Comment by cluelessjoe** [comment]
Hi André

Thanks again for your quick answer. Sorry for my delay: I prefered to check before.

It turns out I've an unresolved point. For example, fullcalendar.io provides a callback when something specific is clicked upon (https://fullcalendar.io/docs/mouse/navLinkDayClick/).

How to "wire this back" to cycle? I don't see a way with snabbdom's hooks to handle this.

Cheers!

**Comment by staltz** [comment]
Quick suggestion (right now I'm busy): how about emitting a custom event on the `vnode.elm` from within that callback? Custom events can have any name, and then you can catch that through `domSource.select().events()`

**Comment by TylorS** [comment]
Elaborating on what @staltz mentioned, it could look something like this. 

Disclaimer: I didn't run this code and have no idea if it works.

```typescript
import { VNode, div } from '@cycle/dom'
import xs from 'xstream'

const CALENDAR = '.calendar'
const NAV_LINK_DAY_CLICK = 'navLinkDayClick'

export interface NavDayLinkClickEvent extends Event {
  date: Date,
  jsEvent: Event
}

function Calander (sources) {
  const { DOM } = sources

  const dayClick$ = DOM.select(CALENDAR).events(NAV_LINK_DAY_CLICK)
  
  // do stuff with dayClick$
 
  const view$ = xs.of(view())
 
  return {
    DOM: view$,
    // ... whatever else
  }
}

function view() {
  return div(CALENDAR, { hooks: { insert } })
}

function insert({ elm }: VNode) {
  $(elm).fullCalendar({
    navLinks: true,
    navLinkDayClick: function(date, jsEvent) {
      const event = new CustomEvent(NAV_LINK_DAY_CLICK, { date, jsEvent })
      elm.dispatchEvent(event)
    }
  })
}
```

**Comment by jvanbruegge** [comment]
I'm using Custom events for https://github.com/cyclejs-community/cyclejs-sortable and it works flawless.
You might have to add a polyfill, because IE does not have the CustomEvent constructor

**Comment by cluelessjoe** [comment]
Events should do it indeed. And cyclejs-sortable looks pretty handy too.

I will do a PR tonight regarding the documentation.

So thanks a lot, you all rock!

**Comment by staltz** [comment]
Yeah and we're talking IE8, because IE9 seems to have support http://caniuse.com/#feat=customevent

**Comment by jvanbruegge** [comment]
Yes, it has support, but as seen in the annotations:

> While a window.CustomEvent object exists, it cannot be called as a constructor. Instead of new CustomEvent(...), you must use e = document.createEvent('CustomEvent') and then e.initCustomEvent(...)

**Comment by cluelessjoe** [comment]
I summed up this discussion in the [FAQ](https://github.com/cyclejs/cyclejs/wiki/FAQ), I hope you don't mind it.

**Comment by fuunnx** [comment]
Hi,

The example provided totally makes sense to me =)
However I'd like to know how could we go the other way around and send a message to the components (eg: Web component) without involving a driver ?
