### ISSUE TITLE
Outdated docs piece in HTTP example with xstream-run

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs/cyclejs#574]
With unified, this should be `@cycle/run`.
https://cycle.js.org/api/http.html

I would do the PR myself, but I'm not sure if the HTML is not autogenerated, because I was not able to find a markdown version

**Comment by staltz** [comment]
@jvanbruegge `docs/content`. I'm glad to merge a PR from you and get your name in the contributors for this repo :)

**Comment by staltz** [comment]
Actually that was wrong, it's `http/.scripts/docs-template.md`

I agree this is quite hidden from sight, we should ideally move it to elsewhere where it's more obvious.
