### ISSUE TITLE
Update examples to use @cycle/time

### ISSUE THREAD

**Issue by Widdershin** [cyclejs/cyclejs#575]
Now that @cycle/time is quite stable, we should update the examples to use it.

I plan on doing this, opening an issue so I can log against it for OpenCollective.

**Comment by staltz** [comment]
Yes, go ahead!

**Comment by staltz** [comment]
Here is a link as an example of `http-search-github` with Cycle Time https://github.com/cyclejs/cyclejs/tree/fc218cf894cd374fde8a18b678752daa6f23c958/examples/http-search-github
