### ISSUE TITLE
Put @cycle/time in the monorepo

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#578]

**Comment by staltz** [comment]
I started doing this. It's a tedious process of moving git repos, adjusting the typescript files to follow the same format, etc.

One question to @Widdershin, though: the current version is `0.x`, do you think we should bump it to `1.0` once it's in the master branch here? Do you think it's mostly ready? (I see some TODO comments here and there but there's are those just improvement vectors or actual showstoppers?)

**Comment by Widdershin** [comment]
I'd quite like to address the issue about extra operators before 1.0, as it
might have a decent impact on the design. hold off on bumping the version
for now :)

**Comment by staltz** [comment]
Okay. As soon as this is in good shape (tests passing, `make` workflow working) I'll let you know but I'll keep it in the `time` branch in git. We can do normal development there. Then we can synchronize v1.0 release with the branch merging to master. (Or do you think there will need to be a lot of development on the `time` branch? In that case people might miss a README easily accessible etc)

**Comment by staltz** [comment]
@Widdershin `markdown-doctest` fails but this also happens in the cyclejs/time repo after a git clone and clean install:

```
....................

Passed: 20
Skipped: 5

Success!
dist/mock-time-source.js:16
        throw err;
        ^

Error:
Expected

---{"foo":1,"bar":4}---{"foo":2,"bar":5}---{"foo":3,"bar":6}---|

Got

---{"foo":0,"bar":4}---{"foo":5,"bar":5}---{"foo":8,"bar":6}---|

Failed because:

 * Expected value at time 60 but got different value at 60

Expected {"foo":1,"bar":4}, got {"foo":0,"bar":4}
 * Expected value at time 140 but got different value at 140

Expected {"foo":2,"bar":5}, got {"foo":5,"bar":5}
 * Expected value at time 220 but got different value at 220

Expected {"foo":3,"bar":6}, got {"foo":8,"bar":6}

Unexpected error:
 Error: 0 should be the same as 1
    at comparator (evalmachine.<anonymous>:13:11)
    at dist/assert-equal.js:35:40
    at Array.forEach (native)
    at checkEqual (dist/assert-equal.js:12:29)
    at Object.complete (dist/assert-equal.js:112:17)
    at Stream._c (node_modules/xstream/index.js:828:18)
    at CombineListener._c (node_modules/xstream/index.js:168:19)
    at MemoryStream.Stream._c (node_modules/xstream/index.js:828:
18)
    at Object.complete (dist/record.js:16:25)
    at Stream._c (node_modules/xstream/index.js:828:18)

 Error: 5 should be the same as 2
    at comparator (evalmachine.<anonymous>:13:11)
    at dist/assert-equal.js:35:40
    at Array.forEach (native)
    at checkEqual (dist/assert-equal.js:12:29)
    at Object.complete (dist/assert-equal.js:112:17)
    at Stream._c (node_modules/xstream/index.js:828:18)
    at CombineListener._c (node_modules/xstream/index.js:168:19)
    at MemoryStream.Stream._c (node_modules/xstream/index.js:828:
18)
    at Object.complete (dist/record.js:16:25)
    at Stream._c (node_modules/xstream/index.js:828:18)

 Error: 8 should be the same as 3
    at comparator (evalmachine.<anonymous>:13:11)
    at dist/assert-equal.js:35:40
    at Array.forEach (native)
    at checkEqual (dist/assert-equal.js:12:29)
    at Object.complete (dist/assert-equal.js:112:17)
```

I guess I could turn off markdown-doctest for now until this is figured out?

**Comment by staltz** [comment]
Nevermind, I fixed it, I renamed `comparator` to `mycomparator` in the last example. It seems the definition of `comparator` was being shared between examples, and there was another definition of `comparator`.

**Comment by staltz** [comment]
Okay, it's in the branch `time`. All yours @Widdershin

**Comment by Widdershin** [comment]
@staltz I think my preference is that we release `v1.0` further down the track from merging into master. I want to make sure there are no breaking changes planned before releasing `v1.0`, https://github.com/cyclejs/time/issues/37 is currently an outlier there.

So if you're happy you can go ahead and merge 😄

**Comment by staltz** [comment]
@Widdershin Okay. When we merge, you'll have to be careful with our release pipeline because it only supports major and minor bumps, not patches. Either you'll have to do the release manually or use minor bumps.

**Comment by Widdershin** [comment]
I'm fine with minor bumps, not overly attached to that aspect of semver.

**Comment by staltz** [comment]
@Widdershin, `time` is now in `master`. I'll make another issue to track progress until cycle/time is v1.0. It could be a good idea to track issues in this monorepo so people looking at the previous repo don't get confused where to discuss versus where is code.
