### ISSUE TITLE
Travis failing with new Makefile setup

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#584]
Apparently my macOS Makefile might differ from what Makefile Travis CI has.

**Comment by whitecolor** [comment]
There where docker helps, or authoring scripts in js/ts, js scripts are much more flexible and less error prone (esp in case of TS) though seem at first to be more verbose in shell related tasks.

**Comment by staltz** [comment]
PR for Makefile => JS would be nice.

**Comment by Widdershin** [comment]
Shall we open another issue to get a genuinely cross platform solution? It would be nice to accommodate Windows users, even though the Windows subsystem for Linux exists it seems a lot of Windows devs aren't using it.

**Comment by staltz** [comment]
We can, but it's a nice to have type of thing

**Comment by Widdershin** [comment]
👍
