### ISSUE TITLE
Total HTTP isolation

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#585]
**Code to reproduce the issue:**

No code, yet. Maybe soon. But for now, I'll just say that it is totally reasonable to isolate a component in terms of HTTP. For example, I'm making a GitHub button component. It makes some GitHub API requests. The point is that it uses the response itself, alone. No other component is interested in that response. I would like to completely isolate it, therefore.

**Expected behavior:**

Should be able to isolate HTTP components completely.

**Actual behavior:**

Only *siblings isolation* is possible.

**Versions of packages used:**

@cycle/http@13.2.0

**Comment by staltz** [comment]
Can you suggest a suitable and idiomatic API?

**Comment by mightyiam** [comment]
The trouble is that `isolate` acts for all sources, isn't it? That makes it difficult to design an API that means the same thing for different sources, with the same signature, without doing something like `isolate(Component, { DOM: 'foo', HTTP: 'bar' })`.

But why is HTTP not totally isolated by default, anyway? I bet there's a discussion on that somewhere here.

I can argue that the pattern of declaring requests in a child component and then reading their responses in a parent is an anti-pattern. Shouldn't we pass the values of responses around via streams instead of doing that? I have only begun to use the HTTP driver, so perhaps I don't realize how complex the passing of values of responses around might get. Even so, isn't it the role of libraries like onionify to make this complexity easier?

**Comment by staltz** [comment]
Unlike in the DOM case, the lack of sibling-only HTTP isolation has not yet been a problem (no one opened an issue of an actual real code that confused them) and often it's a feature. You may want to alter a response in the parent scope before passing it to the child as a source. And you may want to alter a request in the parent after getting it as a sink from the child, a real example being adding some request fields, like for auth.

Onionify has nothing to do with this. Its role is state management only and can use a different isolation scope than HTTP uses.

**Comment by mightyiam** [comment]
So, I think I have a piece of info that might solve two issues for me, here.

In the open source Cycle.js components library that I'm working on, each component's default export is an isolated "version" of itself.

Now that I'm reading this, I'm thinking that perhaps I should leave isolation entirely up to the users. Thoughts?

**Comment by aronallen** [comment]
@mightyiam i think leaving isolate out of your component library is the right approach, that way the developer has direct access to your component function, and they can do with it what they want.

In general I think one should only compose where the function is being consumed, not where it is being created. With that said I do force isolate in @cycle/sandbox, but there is a very specific reason for that, you don't want 3rd party code to attach listeners on your other elements in your main thread.

**Comment by staltz** [comment]
Yeah I agree with Aron, to usually not exported a component already isolated.

**Comment by mightyiam** [comment]
Thanks.
