### ISSUE TITLE
_delegators keeps reference to past EventDelegator instances

### ISSUE THREAD

**Issue by aronallen** [cyclejs/cyclejs#587]
```typescript
function component (sources) {
  const vdom$ = sources
    .select('div')
    .events('click')
    .startWith(null)
    .map(() => h('div', {}, []));
  return {
    DOM: vdom$
  }
}

function main (sources) {
  const components$ = periodic(1000)
       .map(() => Array(4).fill(null).map(() => isolate(component)(sources)))
  components$
    .map(components => components.map(({ DOM }) => DOM))
    .map(DOM => combineArray(Array, DOM))
    .switch()
    .map(children => h('div', children))
  return {
    DOM: 
  }
}
```

**Expected behavior:**
When the isolated module is no longer in use, I would expect the event delegators to be dereferenced.

**Actual behavior:**
The event delegators remain referenced, causing a memory leak.

**Versions of packages used:**

"@cycle/dom": "^17.1.0",
"@cycle/isolate": "^2.1.0",
"@cycle/most-run": "^7.1.0"
"most": "^1.2.2",

**Comment by michalvankodev** [comment]
Hey @aronallen ! Have you also tried this with `@cycle/run` and xstream?

**Comment by aronallen** [comment]
No I haven't tried that yet, but looking through the code I couldn't find
anywhere where elements where removed from _delegators.

**Comment by aronallen** [comment]
I think a solution could be to pass a reference to _delegators to each EventDelegator upon initialization, and in EventDelegator stop method, to remove the reference from there.

**Comment by staltz** [comment]
Thanks Aron, seems legit.

**Comment by jvanbruegge** [comment]
This is now fixed in `@cycle/dom` v21 :tada:
