### ISSUE TITLE
Publishing of styles for open source Cycle.js components

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#596]
I'm developing an open source component library for Cycle.js.

It is a design decision that there will be no CSS included—only logic.

One of the components that I'm working on is a GitHub button, such as this:
![screenshot_2017-04-30_11-07-10](https://cloud.githubusercontent.com/assets/635591/25562666/2a83a98e-2d95-11e7-87b7-d0b94412e9d2.png)

It can be star/follow/fork, etc..

For each component I make a demo in the library's documentation site. For the purpose of this demo, I wish to style this GitHub button component. It makes a lot of sense when it is styled, because it is familiar to developers and it won't be very pretty without any styles.

And this makes me rethink whether I should publish the style declarations that I write for it. So, the question is in what format should I publish it?

SASS? CSS? Or maybe pseudo-css JavaScript object, like those consumed by the snabbdom css module and [styletron](https://github.com/rtsao/styletron)?

I like the idea behind styletron. It seems like a brilliant implementation. But it is a hack. So I'm not sure which route to turn.

Also, should I publish whatever I come up in the same package as the component or in a separate, unrelated package?

**Comment by Frikki** [comment]
I suggest you take a look at [TypeStyle](http://typestyle.io), which is built on top of Blake Embrey’s FreeStyle. I’m sure @staltz would tip in on that.

**Comment by jvanbruegge** [comment]
I'm personally against any kind of CSS-in-JS. As @Frikki mentioned you cannot use the benefits of HTTP/2, but also your content depend on your JS, which is parsed and executed last. So if you have server-side rendering, you are presenting the user with a FOUC.

**Comment by staltz** [comment]
@jvanbruegge You can compile the CSS from JS beforehand and send it from the server, with e.g. TypeStyle. Just saying that it's possible

**Comment by mightyiam** [comment]
Would anyone like to schedule a brainstorming session about this?
