### ISSUE TITLE
HttpDriver cannot handle binary response

### ISSUE THREAD

**Issue by maskinoshita** [cyclejs/cyclejs#602]
HttpDriver cannot handle binary response.
 
Superagent can handle binary response, so it should be changed to handle binary.
http://visionmedia.github.io/superagent/#parsing-response-bodies 

Maybe, it can be done with small change: 
* add blob option to RequestOptions interface
https://github.com/cyclejs/cyclejs/blob/master/http/src/interfaces.ts#L15
* add handle blob options in optionsToSuperagent 
https://github.com/cyclejs/cyclejs/blob/master/http/src/http-driver.ts#L21

**Comment by Widdershin** [comment]
@maskinoshita sounds very reasonable.

Would you be interested in making a pull request for this issue?

I'll help you get it ship shape for merging. 😄
