### ISSUE TITLE
Replace uglifyjs with Google Closure Compiler in all packages

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#619]
We've done this in xstream recently and it was a good idea. Uglifyjs isn't being maintained that well and GCC is potent. Seems like an easy win.

**Comment by jvanbruegge** [comment]
I was confused by gcc :D
Just so used to writing C/C++

**Comment by maximilianmikus** [comment]
I would like to try to help with this issue. Have not committed to cyclejs before, but I figure this might be a good starting point.

**Comment by staltz** [comment]
Yes, it would be a good starting point, if you can navigate through our custom monorepo setup. Thank you for volunteering! Here's a reference https://github.com/staltz/xstream/commit/ed6f79360eb527d38a25aa26efc01c7970961a0c

**Comment by maximilianmikus** [comment]
Thanks for the reference! Should this replacement be applied to all packages or to the dom package only? Since this issue has a label "scope:dom" I assume the later, correct?

**Comment by staltz** [comment]
All packages where we use uglify. :)

**Comment by maximilianmikus** [comment]
ok thanks, just wasn't sure ;)

**Comment by maximilianmikus** [comment]
Ok, I think I got it set up, but how would you go about testing all these minified files? I think the test-suite does not cover them.
