### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by nyarly** [cyclejs/cyclejs#621]
**Code to reproduce the issue:**

Not sure exactly: I'm filtering a list that goes into a view - when the filtering updates is when this triggers.

**Expected behavior:**

New set of values in the list displayed

**Actual behavior:**

"Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node." appears in the console, and the main loop appears to stop. Periodic network requests continue to fire, but no processing happens as a result.

**Versions of packages used:**

```
    "@cycle/dom": "^17.3.0",
    "@cycle/http": "^13.3.0",
    "@cycle/isolate": "^2.1.0",
    "@cycle/run": "^3.1.0",
    "@cycle/time": "^0.8.0",
    "cycle-onionify": "^3.3.0",
    "xstream": "^10.8.0"
```

**Comment by staltz** [comment]
@nyarly I recall seeing that issue long time ago, too, but can't remember why it happened. This report also misses some details, so I'll close it for the time being. If you figure out an example reproduction case, let me know.
