### ISSUE TITLE
[discussion] Add links to packages in README?

### ISSUE THREAD

**Issue by SteveALee** [cyclejs/cyclejs#630]
The READ me is an exceptionally good project landing page!

A posible tiny improvement is to make each package name in the table a link to the packages source. At least I just wanted to do, even though it's easy to find the package (especially when you realise it's a monrepo layout)

**Comment by staltz** [comment]
Seemed easy to do, so I just did that. Thanks for suggesting!

**Comment by SteveALee** [comment]
Thanks. I quite forgot to do it if I got no negative response :(
