### ISSUE TITLE
[discussion] Dom, isolation and functional

### ISSUE THREAD

**Issue by 3n-mb** [cyclejs/cyclejs#631]
#### Context: main and result of main are two distinct things
`main` function is run once to produce a circuit of interconnected streams, memory streams, signals (future). `main` should be given things that allow it to built a circuit instance. But it shouldn't be given anything unnecessary.

Result of main is a circuit. Circuit has this nice properties of data flow direction, etc. Circuit's activity depends on things that push it from boundary sources, and circuit output comes out of its boundary sinks.

#### Isolation should come, when using functions
When `main` is called, it creates circuit instance. When it is called second time, it creates another circuit instance. This is obvious, except it doesn't work with current approach to dom: a special isolate module is needed. Why is it? Shouldn't a function produce independent outputs :thinking: 

#### Consider example of counter
Original is
```typescript
function main(sources) {
  const decrement$ = sources.DOM
    .select('.decrement').events('click').mapTo(-1);

  const increment$ = sources.DOM
    .select('.increment').events('click').mapTo(+1);

  const action$ = xs.merge(decrement$, increment$);
  const count$ = action$.fold((x, y) => x + y, 0);

  const vdom$ = count$.map(count =>
    div([
      button('.decrement', 'Decrement'),
      button('.increment', 'Increment'),
      p('Counter: ' + count)
    ])
  );
  return { DOM: vdom$ };
}
```
Note how in the beginning `main` uses argument, given from outside, to get actual sources that it cares about, by selecting them via string that it will introduce itself!
`main` selects from *external* argument by classes `.decrement` and `.increment`, that it will introduce *itself*.

Again, `main` presupposes existence of things outside, while it will create these things itself. Is this functional?
More generally, dom is a global pinboard for sticking ids and classes. Current `select()`-ing from dom is a time shifted use of global variable, nothing else. It is hardly an example of being purely functional.

Can we make `main` that doesn't use globals even in dom's hidden and time-delayed form? How can such API look like?

`main` creates a section of dom, to which some sources should be attached that feed created circuit. Yes, `main` creates a (almost) cyclic circuit. It even correlates with frameworks' name.
Let's make this cycle creation explicit. Let's not be ashame of making cycles in a cycle framework.

We cannot expect outside to give `main` things that it will create in the first place. Hence, we need to create a bending part of the cyclic circuit inside the `main`.

First, we'll need something that is called subject in rxjs (I think). XStream doesn't have subject. What if it has, for the purpose of initial presentation, the following
```typescript
type Subject<TofEvent> = Listener<TofEvent> & Stream<TofEvent>;
```
that is created by
```typescript
const sub = xs.subject<TofEvent>();
```

Secondly, dom object should use `Listener` side of a `Subject` to feed real events. Let's assume that (v?)dom object accepts `Subject` in a desired by `main` position, and for desired dom event(s).

Then we can write original example as follows:
```typescript
function main(sources) {
  const decrementUserAction = xs.subject();
  const decrement$ = decrementUserAction.mapTo(-1);

  const incrementUserAction = xs.subject();
  const increment$ = incrementUserAction.mapTo(+1);

  const action$ = xs.merge(decrement$, increment$);
  const count$ = action$.fold((x, y) => x + y, 0);

  const vdom$ = count$.map(count =>
    div([
      button('Decrement', { click: decrementUserAction }),
      button('Increment', { click: incrementUserAction }),
      p('Counter: ' + count)
    ])
  );
  return { DOM: vdom$ };
}
```

There are a few things to note about this code:
1. `main` cleanly produces (almost) cyclic circuit. No shame. We explicitly set user actions, and attach them to excreted section of dom. `main` knows what actions should be in resulting circuit, so it creates these actions *itself*.
2. Every call of `main` produces isolated dom sections. There is no need for a separate isolate module!
3. Dom, the global pinboard, is not polluted with classes and ids, whose sole purpose is to identify elements. Better use classes for css.
4. Incoming `sources` are things that come from parent. Note that in a given example there is either no parent, so, no externally given sources are used.
5. There is no dom driver with a global reach. This is simpler. May be even dom machinery can be simpler.
6. In original code, placement of user actions on the dom happens not at the place of formulating dom section. In a new code, actions are placed in dom at the moment of formation. Dom becomes simpler to read, as all connected things are present at one spot.

#### Questions
1. What do you think about this?
2. Do you prefer code flow without `select()`-ing?
3. Was this discussed before? If so, was there a reason for not taking this route? May be time has changed the context?

**Comment by staltz** [comment]
Hi @3n-mb.

This has been discussed multiple times before (most recent example https://github.com/cyclejs/cyclejs/issues/501) and the subject `send` API breaks the reactive principle, which we want to keep everywhere in order to have full reactivity as a guarantee on which we can depend on. For more context on why we did that, this talk explains it https://vimeo.com/album/4578937/video/216787869

If you're interested in this approach anyway, there are many other frameworks similar to Cycle.js that do this.

> XStream doesn't have subject.

Actually every xstream Stream is a subject, the API `shamefullySendNext` allows that.

**Comment by 3n-mb** [comment]
Wow! So, this is a sour point to many. Ok, ok, I am not alone :face_with_head_bandage: 

@staltz you know code better.
How, with minimal effort, with less envasion, can a dom-absorbing part be changed, so as to allow `button('Decrement', { click: decrementUserAction$ })`?
Can it be done so that components with both styles can be mixed together?
What if?

**Comment by 3n-mb** [comment]
@staltz applying approach from [this comment](https://github.com/cyclejs/cyclejs/issues/579#issuecomment-306789490), I can replace words "*breaks the reactive principle, which we want to keep everywhere in order to have full reactivity*" with ChupaCabra, and it will make the same sense.
I can see, that there should be value, but I am at a loss. Yet, I'll try to guess out of my current understanding.

Reactivity is the property of a resulting circuit, which is produced by main. Main itself isn't particularly reactive. Its a function. Circuit, object, subsystem can be reactive or non-reactive.
Hence, it seems that how main assembles circuit, as long as the circuit is the same, is irrelevant to reactivity of the circuit.

It is better to have main function that uses no globals, to be a nice function. I argue that select-through dom smells global, and a subsequent need for isolation highlights that.

May be, you want all dom sources to come as argument into main for testing. This should be changed with an added step to expect produced circuit for presence of correctly inserted sources (user intent sources, as dom events are due to user, usually), cause these intents circuit uses directly from dom, and test should, therefore, use them. Parent sources still stay in main's argument.

May be, having component's own user intentions produced for user by component's main will not make glorious expression `view(model(intent))` totally true. But it is an abstract expression. The circuit is real. And the circuit (model) still uses sources attached to dom (user intents), and sends resulting things downstream for display (view).

In your video, I have seen that select has always been done, like an echo from React. I also saw a will to question existing state of affairs, as future is not linear.

**Comment by 3n-mb** [comment]
@staltz looking at picture in [components dos](https://cycle.js.org/components.html) I see picture that says "*dataflow component (a function)*". We both know that *dataflow component* is a circuit of connected streams.
Main function creates these streams, nothing more. Am I missing here something?

**Comment by 3n-mb** [comment]
I'll quote from [comment from 501](https://github.com/cyclejs/cyclejs/issues/501#issuecomment-268809786):

> (1) it would change central ideas in Cycle.js related to dataflow and separation of concerns in MVI style,

I detailed that mvi doesn't disappear. i - sinks from dom, m - circuit created by main, v - sink for dom. And circuits of streams stay circuits of streams. The actual runtime entity doesn't change.

> (2) it would remove selectors as names, but add stream names, so -1+1==0,

Raw string and variable names are not the same for Typescript. Strings are pain for refactoring. Hence, it is `-2+1`, hence, a reduction in pain.

> (3) it would mean a huge breaking change to Cycle.js,

This is a quote from other issue, and, may be, currently suggested approach can coexist with selectors.

> basically becoming a different framework.

This is just not true, cause cycle is use of streams. This statement, I sense as a emotionally loaded. Do you really believe that with all streams, visualization, cycle will fundamentally change due to mere change of how a tiny aspect is addressed? I don't think so.

**Comment by 3n-mb** [comment]
Looking at [thing](https://github.com/cyclejs/cyclejs/releases/tag/v0.12.1) that was mentioned in #501, the **before** part doesn't even look like what I suggest here.
