### ISSUE TITLE
preventDefault doesn't respect cmd+clicks

### ISSUE THREAD

**Issue by ulitiy** [cyclejs/cyclejs#651]
**Code to reproduce the issue:**
`sources.DOM.select("a").events("click", { preventDefault: true }).map((e) => handle_link(e))`
**Expected behavior:**
It would be useful to have an option not to prevent clicks with a `e.shiftKey || e.metaKey || e.ctrlKey` condition.
**Actual behavior:**
It prevents all of them.
**Versions of packages used:**
`    "@cycle/dom": "^17.6.0",`

Maybe we could send an eventsToPrevent stream to a driver?

**Comment by jvanbruegge** [comment]
This is not a bug, it is ecpected behavior.
I prepares a PR which would allow this, but because of an unresolved discussion it is currently on hold.
You can write your own preventDefault driver that does this for you

**Comment by ulitiy** [comment]
Okay, so basically it's duplicating #611

**Comment by staltz** [comment]
Yeah, what @jvanbruegge said. This is tough problem to solve (for all the use cases required).
