### ISSUE TITLE
Unable to see what's being typed in CLI during `make commit`

### ISSUE THREAD

**Issue by johnrees** [cyclejs/cyclejs#654]
Using iTerm2 and ohmyzsh on OS X 10.11.2

![screen shot 2017-07-27 at 13 05 18](https://user-images.githubusercontent.com/601961/28669947-58f79d06-72ce-11e7-8a5c-216be35ef329.png)

**Expected behavior:**

Read letters as they're being typed in the SHORT and LONG commit descriptions

**Actual behavior:**

Nothing is shown until the return key is pressed

**Versions of packages used:**

master https://github.com/cyclejs/cyclejs/commit/8ba6c14666e300e52fe6b418b5d947f8dc55040e

**Comment by staltz** [comment]
@johnrees can you try the original `Terminal` in Mac? I use also ohmyzsh and macOS, but I use Terminal. This might be a bug in `git-cz` or in our script `.scripts/commit.sh` (maybe the shebang)

**Comment by johnrees** [comment]
@staltz I have the same issue with Terminal. I'll try and help with debugging it over the weekend.

**Comment by johnrees** [comment]
![screen shot 2017-07-28 at 18 34 44](https://user-images.githubusercontent.com/601961/28729194-78e69a90-73c3-11e7-830d-25458e21976a.png)

I just made a test project with https://github.com/commitizen/cz-cli and that worked OK

**Comment by johnrees** [comment]
It also have the typing problem if I change
```
# Do the commit
$(dirname $0)/../node_modules/.bin/git-cz
```

to `/usr/local/bin/git-cz`

but it works fine if I run `git-cz` directly inside the directory, without using `make commit`

**Comment by johnrees** [comment]
It also works ok if I run `./.scripts/commit.sh` directly. Getting closer!

**Comment by staltz** [comment]
@johnrees It's probably your installed make

**Comment by jvanbruegge** [comment]
@johnrees is this resolved by now?

**Comment by johnrees** [comment]
Yes thanks, @staltz called it

```bash
› which make
make: aliased to colourify make
› make commit
# fails as described above
```

```bash
› alias make=make && make commit
# works correctly
```
In this case `colourify` was an alias for `/usr/local/bin/grc -es --colour=auto`

and the `s` flag `-s --stdout    redirect stdout, even if -e is selected` was what was causing the problem.

I haven't looked for where the alias is being set yet, but incase anyone runs into this issue in future omitting the `-s` flag also works
```
/usr/local/bin/grc -e --colour=auto make commit
```

Thanks!
