### ISSUE TITLE
Question about imperative pattern

### ISSUE THREAD

**Issue by niahoo** [cyclejs/cyclejs#659]
Hello, 

I'm sorry not to use Gitter but I can't really chat at the moment :S

(By the way It should be great to have a forum or a sub-reddit to have some async discussion about cycle :) )

I try to implement a simple game and I want to try Cyclejs to do so. It looks fun, but I need your help to implement a pattern.

In the game, the user is able to start tasks which have different durations. Whenever a task completes, I want to recompute the new state of the game (the task yields stuff, and with this stuff we can complete quests or start pending tasks).

So, I think the state sink (maybe use onionify/@cycle/state ?) should provide a nextCompletingTaskTimestamp, and with that value I would use setTimeout (in a driver ?) to send a new event to Cycle. But that sound imperative, no ? What is the Cycle way for that ?

There is more : at any time, the player can cancel the next completing taks (or any other task), or add a fast task that will complete sooner, so I'll have to recompute the time of the next completing task, cancel my timeout and create another one.

I think this should be easy with stuff like shamefullySendNext, but how to do that otherwise ?

Thank you for reading.

**Comment by Widdershin** [comment]
@niahoo one option is to use `@cycle/time`, https://github.com/cyclejs/cyclejs/tree/master/time.

You can get a stream of that emits every frame with `sources.Time.animationFrames()`.

Each event in this stream is an object with three properties:

```js
    time - the elapsed time in millseconds since application start
    delta - the time in milliseconds since the last frame
    normalizedDelta - the delta divided by the expected frame length (16ms). Useful for game development
```

So in your case, you could fold over this stream of animation frames, and subtract the `delta` value from each of your timers, or you could simply check if `time > nextCompletingTaskTimestamp`.

This allows you to write code in a relatively imperative style while operating within Cycle's constraints, without needing to manage timeouts or use `shamefullySendNext`.

**Comment by niahoo** [comment]
Hi,

I will definitely look into `@cycle/time` to see what is there. But my game is more kind of management/incremental than animations, I think checking everything in each animation frame is kind of heavy. I'm more inclined to use delays because if I know there is no work to do for the next two seconds, I don't want the app to work.

Thank you.

**Comment by Widdershin** [comment]
Fair enough, you could achieve this with a more stream oriented approach as well.

> In the game, the user is able to start tasks which have different durations. Whenever a task completes, I want to recompute the new state of the game (the task yields stuff, and with this stuff we can complete quests or start pending tasks).

> There is more : at any time, the player can cancel the next completing taks (or any other task), or add a fast task that will complete sooner, so I'll have to recompute the time of the next completing task, cancel my timeout and create another one.

So if I understand this right:

A player can:
 * Add tasks to the end of the queue
 * Cancel tasks
 * Add tasks to the start of the queue?

You can create streams of actions from interactions the players would perform to start tasks.

```js
const startTask$ = sources.DOM.select('.start-task').events('click').map(() => ({time: 2000, type: 'DO_A_THING'});

const task$ = xs.merge(
  startTask$,
  ...
)
```

Then we can delay the result with `sources.Time.delay()`, and process one at a time with `flattenSequentially`.

```js
import flattenSequentially from 'xstream/extra/flattenSequentially';

const delayedTask$$ = task$.map(task => xs.of(task).compose(sources.Time.delay(task.time)))

const taskResult$ = delayedTask$.compose(flattenSequentially);
```

We can then fold over the `taskResult$` to update our state when a task completes.

```js
const initalStates = {
  points: 0
}

const state$ = taskResult$.fold((state, task) => {
  if (task.type === 'DO_A_THING') {
    state.points += 1;
  } else {
    // handle other tasks
  }

  return state;
}, intialState)
```

To cancel tasks early you could use `endWhen`. So `delayedTask$$` might look more like this:

```js
const cancelTask$ = sources.DOM.select('.cancel-task').events('click');

const delayedTask$$ = task$.map(task =>
  xs.of(task)
    .compose(sources.Time.delay(task.time))
    .endWhen(cancelTask$.filter(event => event.target.dataset.taskId === task.id))
)
```

Adding tasks to the front of the queue seems more difficult but probably possible, but I think I'd need to understand the game a bit more before I spend time thinking about how it could be done.

Hope this is helpful 😄

**Comment by niahoo** [comment]
Hey, thanks, this gives me some ideas.

Actually the tasks are not really a simple queue :
> First, the user creates a task, which is put on a priority queue, but does not start if the ressources are not met.
Imagine 3 tasks set in this priority (first one : more priority): Cook a cake, Cook some bread, each one requiring 500g of flour ; and Crush wheat that gives you 1kg flour.
Now each task requires 1 worker, and you currently have 0 workers. (The may require also other materials but imagine we have them already).

> Then, another task terminates, giving back 10 workers, here is what the game will do :

> By priority, "Cook a cake" is first, so we try to start it, but we are missing flour. The sames goes for "Cook some bread". So we start "Crush wheat". It mobilizes 1 worker and longs 1 second. We start this task.

> After 1 second, we give back the worker and 1kg flour. We try again to start tasks. Now, both cooking tasks can start. They have different durations, so we want to run new tasks whenever the first one terminates, because there may be another tasks waiting for a cake or some bread.

So, tasks are not really events : when the user creates a task, we store the task in state, and we try to start it.
Starting a task is just setting a flag and calculating the finish datetime.

So looking a time and xtstream I would come up with something like that :

But I still must learn how to handle state :)

```javascript
const taskFinishes$ = state$
  .map(s => nextFinishingTasks(s.tasks))
  .map(task => sources.Time.delay(task.finishAt - now).map(_ => task.id))
  .flatten() // Keep only the last *set* delay

const releaseTaskReducer$ = taskFinishes$.map(id => (state) => releaseTask(state))

const reducer$ = xs.combine(releaseTaskReducer$, ...)

// sink reducer
```

What do you think ?

Thanks for your help
