### ISSUE TITLE
@cycle/time: cjs bundle means lodash deps for mocking are pulled in on production apps

### ISSUE THREAD

**Issue by willheslam** [cyclejs/cyclejs#660]
**Code to reproduce the issue:**
mock-time-source.ts uses package combine-errors, which uses package lodash.uniqby which then pulls in a bunch of extra lodash stuff which bloats the bundle considerably if you're not already using lodash.

lodash.uniqby brings in lodash.iteratee (56kb) among others - all in all it adds up to almost 100kb of extra code that won't be used:
![extralodashdeps](https://user-images.githubusercontent.com/5377213/28967477-328a756c-7913-11e7-8db3-f52373cc5d3b.png)

This wouldn't be a problem if we were able to use ES module versions of the packages (rather than bundled cjs) and a treeshaking/dead code eliminating bundler as in theory it could remove the unused modules.

My solution is to split the mock vs non-mock timesource files so in your tests you can pull in the mock time source (including any dependencies needed, e.g. lodash) but your app can pull in the skinnier time driver alone.
Here's an example:
https://github.com/cyclejs/time/compare/master...willheslam:separate-test-deps?expand=1

**Expected behavior:**
No lodash deps in production bundle that does not use mock sources

**Actual behavior:**
lodash.iteratee and other deps are included even  when not using mock sources

**Versions of packages used:**
cycle/time: ^0.8.0

**Comment by jvanbruegge** [comment]
Can you try this now with the newest version?

**Comment by willheslam** [comment]
Hi @jvanbruegge - thanks for this. :) Apologies for the delay, I was away on holiday!

It looks like this has not been fixed as although https://github.com/cyclejs/cyclejs/blob/master/time/package.json#L11 has the new 'module' key and in https://github.com/cyclejs/cyclejs/pull/662 @staltz says all packages have new versions, it looks like cycle/time wasn't given a new release - and installing the latest version from https://www.npmjs.com/package/@cycle/time (0.8.0) doesn't include the module key in the package.json and the expected files inside lib/es6/ aren't there.

When there's a new release of cycle/time I'll install it and give it a go - please let me know if I'm missing anything!

**Comment by Widdershin** [comment]
Ah woops, hadn't realised this was on me. I'll have a look at releasing a new version tonight.

**Comment by willheslam** [comment]
@Widdershin Can I help at all with this? We're using [patch package](https://github.com/ds300/patch-package) at the moment to patch around the problem.

**Comment by jvanbruegge** [comment]
In theory @Widdershin just has to publish a new version. I already did the change when I updated the other packages

**Comment by Widdershin** [comment]
I've published v0.9.1, which should address this issue. 

Apologies for the delay, this is the first release time has had since moving into the monorepo, so I had to get up to speed with the release tooling and conventions that the monorepo uses.

Please let me know if this release solves your issue 😄 

Thanks for your patience.

**Comment by willheslam** [comment]
@Widdershin Sorry about the late reply!

Thank you so doing this, I appreciate that it's a difficult bit of work porting a codebase over to a new infrastructure. The cycle time package now definitely works with an ES module-compatible bundler.

Oddly enough I'm still having trouble getting rid of the lodash dependencies when using webpack and a minifier like uglifyjs or closure compiler - however when using rollup *and* turning this line:
https://github.com/cyclejs/cyclejs/blob/master/time/src/mock-time-source.ts#L14
`const combineErrors = require('combine-errors');`
into
`import combineErrors from 'combine-errors'`
then it works beautifully with rollup's proactive, selective dependency fetching - no need for a minifier. Hopefully in time as webpack / uglifyjs / closure compiler get better it'll work for them too.

I can raise a merge request for this - is there a specific reason why `require` is used for combine-errors?

**Comment by Widdershin** [comment]
I think `require` was used just because there were no type definitions for `combineErrors` and `require` returns `any`.

We'll change that. To be honest I'm tempted to just write `combineErrors` out of this project, if I had realized it pulled in parts of lodash I never would have included it.

**Comment by Widdershin** [comment]
Actually yeah, if you want to make a pull request that would be fantastic!
