### ISSUE TITLE
How to use other ui library after view render.

### ISSUE THREAD

**Issue by dashng** [cyclejs/cyclejs#663]
Stream coding is amazing. 
Like Cyclejs programming is a trend in the future, I think.
Cyclejs just provide basic http, dom render, and, event binding, after the investigation.
My questions is how to use other modern ui library like jquery ui, sweet js, d3js, highcharts and others ...
If using cyclejs, everything thinking with stream is okay, but if every web ui plugins must be coded by self, it will take too many efforts.

**Comment by jvanbruegge** [comment]
For d3 you can take a look at my blog article: https://dev.to/supermanitu/using-cyclejs-to-view-real-time-satellite-test-data
For the others, you can ise snabbdom hooks: https://github.com/snabbdom/snabbdom/blob/master/README.md#hooks

**Comment by dashng** [comment]
Oh! I memoried the cycle dom was based on snabbdom. I didn't check snabbdom.
The solutions in snabbdom.
Thanks a lot.
