### ISSUE TITLE
@cycle/dom elements lose their EventListener when moved in another part of the DOM

### ISSUE THREAD

**Issue by atomrc** [cyclejs/cyclejs#667]
**Code to reproduce the issue:**
Here is a bin that reproduces the bug https://www.webpackbin.com/bins/-KrjXqknNMZskaEo273r
Step to reproduce:
- Button 1 and Button 2 should update state when clicked ;
- click the `sort` button ;
- Button 2 still works ;
- Button 1 doesn't react to clicks anymore.

**Expected behavior:**
The button moved to the bottom should update state

**Actual behavior:**
The button moved to the bottom doesn't do anything when clicked

**Versions of packages used:**
@cycle/dom v18.1.0
@cycle/run v3.2.0
cycle-onionify v4.0.0-rc-14

I think this bug has to do with the way the `EventDelegator` cleans vnodes when they are treated by snabbdom https://github.com/cyclejs/cyclejs/blob/b482e206b1425dda95c63ad1ca872189b5c0d93e/dom/src/IsolateModule.ts#L135. One fix could be to batch the removal of listener once snabbdom has completely finished its work?

Here is a gif that illustrate what happens 
![bug](https://s3-eu-west-1.amazonaws.com/atomrc-random/out.gif)

**Comment by Widdershin** [comment]
Yes, we absolutely should fix this. Thanks for the reproducer.

If anyone is interested in making a pull request, please comment in here. 😄

**Comment by atomrc** [comment]
I might be interested in patching this. 
The idea I have in mind is to: 
- whenever a node is removed, add its key to an array of vnodes to clean ;
- if a removed vnode is added latter on, just remove it from the array of vnodes to clean ;
- when snabbdom has finished its work, actually trigger the vnodes cleaning.

I am not really familiar with snabbdom, but it seems that the `post` hook seem perfect for that use case, isn't it? https://github.com/snabbdom/snabbdom#hooks

**Comment by atomrc** [comment]
@Widdershin so I was able to write a test that reproduce the error. Can you give me some feedback on it? https://github.com/atomrc/cyclejs/commit/7e6a15a793201fad533e7913d650cb35b1c7dc77

Next step would be actually fixing it :)

**Comment by Frikki** [comment]
Maybe you can draw some inspiration from [Motorcycle](https://github.com/motorcyclets/motorcycle), which [doesn’t have that bug](https://www.webpackbin.com/bins/-KsrH7tkqwwerDFy3ZMW).

**Comment by staltz** [comment]
I'll close when a new cycle/dom version is released.

**Comment by staltz** [comment]
Released version 18.3
