### ISSUE TITLE
Change cycle/http API to treat HTTP errors with status codes as normal responses

### ISSUE THREAD

**Issue by bbarker** [cyclejs/cyclejs#669]
This follows some recent discussion on the gitter channel. HTTP error status are quite normal in the web, and should by default be considered normal responses where filters can be easily made to filter by status code. Currently, they are treated as "exceptional" and require `replaceError`, which seems a bit too heavy handed.

As can be seen in [this example](https://www.webpackbin.com/bins/-KsJjaOfTGP9noKY_PV7), the `Error in response` console log message indicates that http errors with 4xx status codes (e.g.) are being treated as "serious" errors that require the use of `replaceError`, rather than as normal http response, when you click on "bad server page" (assuming you have changed the url `https://some.server.com/with/open/CORS/access` to something that won't give you a CORS error but will give you e.g., a 404).

**Comment by Widdershin** [comment]
One option if we don't want to make a breaking change is to make this a mode that is passed as an option to `makeHTTPDriver`.

This is comparable to how, say https://github.com/request/request-promise works (with the `simple` option).

**Comment by staltz** [comment]
I think this issue deserves a bit more discussion. Does anyone have a link to the relevant gitter discussion that started it?

I understand the argument from the perspective of convenience of filtering, but there is also the semantic perspective. HTTP status codes 4xx and 5xx are "errors" according to HTTP, respectively, client errors and server errors.

It's still possible to use `filter` operator after `replaceError` is applied. For instance, you could make a helper function `detect` (perhaps with a better name) used as `replaceError(detect)` where we sort out 4xx and 5xx and make them be normal values in the output stream that `detect` returns, while other errors would pass through as simple errors. From that point onwards, you can use `filter` operator to catch 4xx or 5xx.

**Comment by geovanisouza92** [comment]
@staltz I think it started [here](https://gitter.im/cyclejs/cyclejs?at=5994878a2723db8d5eae78a6)

**Comment by whitecolor** [comment]
One should always look how underlying driver library behaves.

From [superagent docs](http://visionmedia.github.io/superagent/#error-handling):
> Note that a 4xx or 5xx response with super agent are considered an error by default. For example if you get a 500 or 403 response, this status information will be available via err.status. Errors from such responses also contain an err.response field with all of the properties mentioned in "Response properties". The library behaves in this way to handle the common case of wanting success responses and treating HTTP error status codes as errors while still allowing for custom logic around specific error conditions.

> Alternatively, you can use the .ok(callback) method to decide whether a response is an error or not. The c allback to the ok function gets a response and returns true if the response should be interpreted as success.
```js
request.get('/404')
  .ok(res => res.status < 500)
  .then(response => {
    // reads 404 page as a successful response
  })
```

So probably it is just worth to add `ok` property to requests that will define a function that will be passed to `ok` of supeagent request.

**Comment by staltz** [comment]
Good suggestion. I made issue #681 for that, and it's easy to support.

**Comment by jvanbruegge** [comment]
As #684 is merged I will close this now. If someone thinks the PR is not enough for their use case, please state that use case here and I will reopen
