### ISSUE TITLE
Make DOMSource.elements() always return array, create .element() for single element

### ISSUE THREAD

**Issue by Widdershin** [cyclejs/cyclejs#677]
Currently, in the DOM driver, `DOM.select('.foo').elements()` has a type of `Element | Element[]`.

This is because when selecting the root element, the document or the body, there is only one possible result.

However, this has poor user experience, as it means users have to coerce the type depending on what they are selecting, which means we might as well not have types for this usecase.

Additionally, it is common to want to take the first item from the resulting array, in which case you must do `DOM.select('.foo').elements().filter(elements => elements > 0).map(elements => elements[0])`.

I propose to instead have `.elements()` always return an `Element[]`, and to create an alternative `.element()` function that always returns an `Element`.

This means that users would not have to coerce the type, and could instead use the function appropriate for their use case.

`.element()` would be effectively equivalent to `.elements().filter(elements => elements > 0).map(elements => elements[0])`, which would save having to include that relatively nasty looking code.

I don't think this would make the user experience worse in any way, but would make our type information more useful and our code elegant and more readable.

The biggest downside is that this is a breaking change, as I am proposing that when selecting root, document or body, and using `.elements()`, we return a single item array.

**Comment by staltz** [comment]
Yes, I think we should just do this. In the case of `.elements()` for the document or body, it's okay to return an array with one entry.
