### ISSUE TITLE
Implement `ok` field in request objects

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#681]
Cycle/HTTP should support an `ok` field to determine that some responses like 4xx or 5xx should be treated as normal responses, not errors:

```js
{
  url: 'http://.......',
  method: 'GET',
  category: 'mycat',
  ok: res => res.status < 500,
}
```

See comment https://github.com/cyclejs/cyclejs/issues/669#issuecomment-329949712

**Comment by jvanbruegge** [comment]
Will see if I can do that later
