### ISSUE TITLE
Polyfills

### ISSUE THREAD

**Issue by Sinewyk** [cyclejs/cyclejs#700]
I've seen packages saying

> _insert lib here_ depends on the collection types Map and Set. If you support older browsers and devices which may not yet provide these natively (e.g. IE < 11), consider including a global polyfill in your bundled application, such as core-js or babel-polyfill.

But cyclejs does not actually give you a choice and bundles everything by default. I've just started doing a small application, and I just [webpack-bundler-analyzed it](https://github.com/webpack-contrib/webpack-bundle-analyzer) ... and this is what I got

![cyclejs_polyfills](https://user-images.githubusercontent.com/1826366/31151478-f5f278ca-a897-11e7-898f-a8d6572afaa2.jpg)

There's xstream, snabbdom(-jsx too), the dom driver, everything looks normal. Then on the right (everything circled in red) I see actually a tons of polyfill I didn't ask for.

Anyway we could work on pushing them out of the core so that users can decide whether to include them or not ?

**Comment by jvanbruegge** [comment]
i think this would be a good thing, we could additionally publish a library that bundles all required polyfills, so the users that do want polyfills can simply use `import '@cycle/polyfills'`.

On a side note, `snabbdom-jsx` js very buggy, especially with svg, you might want to look into `snabbdom-pragma`

**Comment by geovanisouza92** [comment]
Why there is two xstream?

@Sinewyk just for curiosity, how did you created this app? Using create-cycle-app or manually?

**Comment by whitecolor** [comment]
Currently one may use WebpackIgnorePlugin or `alias` to exclude from the bundle. But I'm too would exclude polyfills from modules. And just would give the instructions, how to include them if needed.

**Comment by Sinewyk** [comment]
Wow, I thought it was just the xstream cycle/run adapter. But no, well spotted.

[@cycle/run has a hard dependency on xstream 10.x](https://github.com/cyclejs/cyclejs/blob/41d7759302d474779ce8888a3b9cc09924681966/run/package.json#L33) , I pulled xstream 11 when installing recently, and yarn locked it down correctly. So I'm pulling both 10.9 and 11.0 into my bundle.

That sucks too. It must be the same for almost anyone using a bundler with current package versions.

**Comment by staltz** [comment]
> @cycle/run has a hard dependency on xstream 10.x , I pulled xstream 11 when installing recently, and yarn locked it down correctly. So I'm pulling both 10.9 and 11.0 into my bundle.

That's clearly wrong, I'm fixing it and I'll release cycle/run v3.2 soon with a fix. Thanks for mentioning.

**Comment by Sinewyk** [comment]
@staltz created another issue https://github.com/cyclejs/cyclejs/issues/701 to stay on topic for this one =)

**Comment by Sinewyk** [comment]
and it was manual @geovanisouza92

**Comment by staltz** [comment]
cycle/run v3.3 published

**Comment by Sinewyk** [comment]
Updated with upgraded packages, everything in red is polyfill related:

![cyclejs_polyfills](https://user-images.githubusercontent.com/1826366/31183544-2fa64350-a927-11e7-9481-526af9bcd9b6.jpg)

It's `event-emitter`, `d` and `symbol-observable` in the bottom left

<details>

  - `es6-map` is required by `@cycle/dom`
  - `es6-symbol` is required by `es6-map`
  - `es6-iterator` is required by `es6-map`
  - `event-emitter` is required by `es6-map`
  - `d` is required by `es6-map`
  - `es5-ext` is required by `es6-map`
  - `symbol-observable` is required by xstream (among others ?)

</details>

**Comment by jvanbruegge** [comment]
It still has two xstreams... did you upgrade to `@cycle/run` 3.3?

**Comment by Sinewyk** [comment]
Nah, I'm stupid, I fu**** up saving my image, I reused the same -.-', will update previous post with correct image

**Comment by staltz** [comment]
So the issue is mostly related to `es6-map`, right? Is this now solved since cycle/dom is now doing `import 'es6-map/implement'`?

And yes `symbol-observable` is needed everywhere until ES Observable becomes official ES and implemented at least in one browser. Anyway it's a super tiny polyfill.

**Comment by jvanbruegge** [comment]
@staltz `import 'es6-map/implement'` still bundles the polyfill. You would have to remove any import of the package for it to be not bundled. As I said, I would remove all polyfill imports from the official packages and add a meta packages that bundles the necessary polyfills. So if you are only concerned with new browsers (my client only uses newest Chrome/Firefox). You simply not import this meta package. For all other users they can either hand-pick the packages listed in this meta packages according to their requirements, or simply dont bother and import the whole metapackage with all polyfills.

**Comment by staltz** [comment]
@jvanbruegge Right, I misunderstood it regarding bundling. And yes I agree that now would be a reasonable year to declare that ES2015 is required, otherwise people using the framework need to polyfill explicitly. We can add simple instructions how to do that.

**Comment by jvanbruegge** [comment]
This is now done in `@cycle/dom` v21 :tada:
