### ISSUE TITLE
Duplicate xstream bundled because @cycle/run dependency on 10.x

### ISSUE THREAD

**Issue by Sinewyk** [cyclejs/cyclejs#701]
Extracted from https://github.com/cyclejs/cyclejs/issues/700#issuecomment-334149809

[@cycle/run has a hard dependency on xstream 10.x](https://github.com/cyclejs/cyclejs/blob/41d7759302d474779ce8888a3b9cc09924681966/run/package.json#L33) and most recent xstream is v11. Installing them both on your system will result in xstream v10.9 being installed in `node_modules/@cycle/run/node_modules` and xstream v11 just in `node_modules`.

Which should result in both being bundled, even though apparently v11 is just a breaking change related to the ts typing.

Anyway we could fix that ?

It's 7 days old by the way. So, no problem for people having started before that AND did not upgrade their package (maybe that's why no one spotted it, usually no one start looking at their dependency tree when they are not even in prod ?)

**Comment by staltz** [comment]
I already have a commit in master for this.

**Comment by SteveALee** [comment]
Can I suggest we have some guidelines on how to handle xstream as peer dependency (or what ever is best practive these days)? I hit a similar issue with the auth0 driver/wrapper package. We need to ensure it is up to the 'user' to choose which version they use

**Comment by Sinewyk** [comment]
Well, `@cycle/run` seems to be the odd one out, it's the only one specifying xstream as a dependency. All the others have it as a peerDependency and with `x`, but also have `@cycle/run` as a direct dependency (also with a `*`).

So ... I would keep it as is ... it seems to be working, just keep an internal wiki to not forget to relax @cycle/run dependency when updating xstream or something (and also see about updating all devDependencies which are still locked on 10.x almost on all packages.)

**Comment by SteveALee** [comment]
Agree for core packages, but was also thinking of 3rd party drivers etc.
