### ISSUE TITLE
Update superagent dependency

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#703]
Currently it's red. https://david-dm.org/cyclejs/cyclejs?path=http
We should also check their changelog and see if there is any breaking changes or if there is any feature to give support in cycle/http.

**Comment by staltz** [comment]
I'll release a new minor version once Travis CI tests it.

**Comment by jvanbruegge** [comment]
Test are passing for HTTP

**Comment by staltz** [comment]
cycle/http v14.5 released
