### ISSUE TITLE
Add big example app

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs/cyclejs#705]
In the coming month I will be developing a big cyclejs app as example how to build and structure a larger cycle app. The development will be accompanied by a blog series and an egghead.io video course. To set the scope of the app, I will outline the basic requirements. If you have anything to add, feel free to leave a comment.

The app will be a chat app, similar to gitter. It will feature:
+ definitely
    - Live messaging
    - Multiple rooms
    - Keeping track of read/unread messages
    - Login/Auth
    - Mark all read (@geovanisouza92)
    - Presence indicator (@geovanisouza92)
    - Timestamps (@raquelxmoss)
+ most likely
    - " is typing..." (@geovanisouza92)
    - Notifications (@geovanisouza92)
    - @mentions (@geovanisouza92)
    - pinned messages (@geovanisouza92)
    - `@cycle/time` tests
    - async user data loading (@dmitriid)
+ maybe
    - offline usage (PWA)
    - form validation (editable user profile)
    - Server side rendering + hydration
    - Save specific messages as bookmarks (@geovanisouza92)
+ most likely not
    - Embedding link previews (@geovanisouza92)

This means under the hood it will use:
+ definitely
    - `@cycle/dom`
    - `@cycle/http`
    - `@cycle/time`
    - `cycle-onionify` with lenses (@siassaj)
    - `cyclic-router`
    - a custom websocket driver
    - cyclic-router (@brucou)
+ maybe
    - custom validator wrapper (will be published as seperate package)

I'm interested to hear additional requirements :)

**Comment by geovanisouza92** [comment]
Nice to have:
- Mark all read
- Presence indicator
- "<name> is typing..."
- Notifications?
- @mentions?
- Embedding link previews? (Let me dream high :rofl:)
- Save specific messages as bookmarks (as well pinned messages on a room)

**Comment by brucou** [comment]
If you implement `Save specific messages as bookmarks` you will probably also use some form of routing. That could go in your `definitely` section.

**Comment by raquelxmoss** [comment]
Not sure if you had already planned for this, but displaying timestamps on messages might be good -- that would probably introduce Cycle Time. It would also be good to see tests.

**Comment by nspaeth** [comment]
I'd like to point to [this comment](https://github.com/tastejs/TasteApp/issues/1#issuecomment-125764362) again as examples of other things to consider. Although the chatting cats app is a little different from what I had in mind there (issue tracker), many of the features might still be useful to have examples of.

**Comment by SteveALee** [comment]
Is this designed to be a learning tool or a usable app?

If the former, then I don't think we need every possible feature - just enough to demonstrait all usefull patterns in code.

**Comment by staltz** [comment]
This is a great initiative, we've been talking about it for a while, so it's good to see it becoming concrete. :)

Jan, I noticed you had some difficulty labeling this issue ("discussion", "scope examples", "large"), and I'm also scratching my head about it. What will be the outcome? Will it be one example in those among the `/examples` directory, or its own repository? Given how fast it will be updated, I would imagine it's better as its own repository, but could still live in the `cyclejs` github org. What do you think?

**Comment by jvanbruegge** [comment]
I'm not completely sure either ^^
For development I would put it in a different repo, because it's easier to develop from scratch. Afterwards we can still put it in the `examples/` directory

**Comment by siassaj** [comment]
small technical concern, i'd like to see how you guys resolve message passing with onionify lenses. Basically parents/children 'talking' to each other. I have my way, but I'd love to see yours :)

**Comment by dmitriid** [comment]
I think one more thing to go along with presence indicator could be async loading of user data and displaying it in multiple places. See [chatting cats](http://tonsky.me/datascript-chat/). 

When a new "user" joins the chat, their avatar is displayed as a grey circle with three dots ("loading"). 

Once the user data has been loaded, the avatar is updated with user avatar, and it is immediately displayed in several places: in the chat list on the left (if it was the last user to type a message), in the current message list (if the user had any messages there).

Other than that, 
![](https://i.pinimg.com/564x/11/92/5c/11925cc1cc1df1fd0303e5b9610f3700--jake-the-dogs-adventure-time-finn.jpg)

**Comment by mightyiam** [comment]
I would put the large app in its own repo and keep it there. Use common
tools on it like Travis CI and GreenKeeper. GreenKeeper does not support
monorepos.

**Comment by jvanbruegge** [comment]
Closing this in favor of #851
