### ISSUE TITLE
Handle error inside `makeHtmlDriver`

### ISSUE THREAD

**Issue by desfero** [cyclejs/cyclejs#710]
Errors should always be handled, as it may be difficult to debug when "something is not yes". 
In my case i had `undefined` in one of my children noted, and without any logging it was really hard to find what was broken.

By adding error loggin to `makeHtmlDriver` i found from what place error is thrown, in my case it was thrown form `snabbdom-to-html` package: (probably i fill also an issue there to handle `undefined` nodes)
```
TypeError: Cannot read property 'sel' of undefined
at renderToString (C:\Projects\cyclehn\node_modules\@cycle\html\node_modules\snabbdom-to-html\init.js:31:15)
```

The place where error logging should be added:
https://github.com/cyclejs/cyclejs/blob/8deedf9c91f187f77b2506a0e859e472526b7056/html/src/makeHTMLDriver.ts#L46

If any of maintainers agree with this issue i can submit a PR to fix it ;)

**Comment by staltz** [comment]
Good discovery! You're right, this is a bug. We should have error reporting like cycle/dom has.

**Comment by desfero** [comment]
@staltz i will submit PR today to fix it, thanks :)
