### ISSUE TITLE
Provide higher level API constructs to reduce boilerplate in typical websites

### ISSUE THREAD

**Issue by benalbahari** [cyclejs/cyclejs#717]
I'm writing a website that's composed of many Cycle.js components. I'm really enjoying learning about Cycle.js and the project is going well, but following the patterns in the samples yielded a great deal of boilerplate. To get rid of this boilerplate, I wrote some helper interfaces and functions, some of which I've described here:

https://github.com/benalbahari/cyclejssample#thoughts-on-component-wiring-in-cyclejs

The ComponentBuilder interface enables the ToComponent function to create a Cycle.js component, and perform inter-component and intra-component wiring. Before using the interface, I was essentially repeating the implementation of ToComponent in each component in my application. I now have nearly 20 components in my application, and it's trivial for me to create / refactor / re-nest any of them, generally without even needing to touch an xstream operator.

Cycle.js seems unusual to me in that it provides some very clean core concepts, yet doesn't actually allow those concepts to be programmable in a generic way.

So for example, one of its core concepts is component composability, yet the parent/child relation is not expressed in the API, which means I can't abstractly write a function that operates on a component tree. Most UI frameworks provide provide an API for expressing parent/child relations - e.g. get the children from the parent, or get a parent from the child. The ComponentBuilder interface provides the former.

Or to take another example, I can't generically program the V or I in the MVI model. ComponentBuilder allows the ToComponent function to actually realise the MVI model in a generic fashion. So ToComponent will feed the actions of a ComponentBuilder's intent into the ComponentBuilder's update function, the output of which will then be fed into the ComponentBuilder's view. I could still do this without ComponentBuilder, but I'd be repeating that same wiring logic for each component.

Now I like that Cycle isn't too prescriptive - it provides low level primitives and lets you define your own layer on top to reduce boilerplate/repetition for your own application needs. But I'm writing a pretty generic website, and I expect others will encounter exactly the same problems with boilerplate that I did. Which means some form of code duplication must be occuring because either: 1) people are writing lots of boilerplate, or 2) people are independently writing similar layers to reduce that boilerplate.

I also wrote helpers to manage input element boilerplate, that you can see if you browse the source code in the sample in the link provided. Using the patterns in the Cycle.js samples, I was repeating the element name of each form element *9* times. Specifically:

1) In the state object
2) In the interface name for the action type
3) In the interface type as a string for the action type
4) In the union type across all action types for that component
5) In the intent, to create the correct action type from the raw payload
6) In the intent, to assign the correct type field for the action type
7) In the reducer, to check for an action of the correct type and if so create a new state
8) In the reducer merger, to merge all the reducers for that component
9) In the view, for that input control

For a sense of comparison, I also work on a project with some server side generated web forms, and have abstractions that are refined to the point I repeat each form element *once*. Through additional helper methods, typescript features, and javascript object API features, I managed to reduce the Cycle.js boilerplate per form element down to *3*. To be fair, I should mention I did sacrifice static typing on the action's payload to achieve that. I'm actually a huge advocate of static typing, but I view static typing as a tax that I'm going to avoid should that tax get overly high.

Anyway, the code I provided is obviously quite simple and would have to be generalised further (e.g. it's currently hard coded to DOM/onion sources/sinks). Also, let me apologize in advance if I'm wrongheaded about any of this as I'm new to Cycle.js. I certainly feel like my understanding of Cycle.cs is insufficient to justify such a long schpeel. However, I figure that even if I'm wrong, my perspective might still be useful feedback to the Cycle.js team purely on a usability level.

**Comment by whitecolor** [comment]
Here is my current simplified perspective on making UI components:

1) All of my UI components have only two sources/sinks - state and DOM.
2) I don't use isolation (which for DOM is replaced by unique values for classes/attributes generated on runtime start, so parents/children/siblings won't mess up), this allows to avoid a little implicit magic that comes with isolation, which in some cases causes issues.

The component logic reflects causal relationships between state and DOM:
1) state changes -> DOM
2) DOM events/changes -> state reducers

Quite maintainable and simple. I can find abstraction useful if it really reduces inner logic size and complexity needed for each component, but often abstractions lead to opposite result.

**Comment by brucou** [comment]
@benalbahari I am of a similar mind. I found my productivity increased after advancing the [componentization framework](https://github.com/cyclejs-community/component-combinators) I am working on. What is clear to me is that whatever works for you is good for you. The next question is whether what works for you can be useful to others, or possess a level of generality that can have it raised at the level of a good practice.

On the specific subject of componentization in the context of functional programming, there seems to be two schools : 

- *monolithic* : Fat components/Small component tree, and to the extreme only one big fat component 
  - for instance, that is what pux (a purescript framework from writing apps) seems to [recommend](http://purescript-pux.org/docs/components/). I quote :

> If you have React or Elm experience, you're taught to think of your application as self-contained, inter-locking components that encapsulate business logic and presentation. But that object-oriented perspective is unnecessary when working with a purely functional language like PureScript. Components are just one of the many ways you could organize your Pux application, because an application is really a single foldp and view function. They can be split into smaller functions however best fit your needs.
> Instead of designing your application around components, design it around data flow: Events change state (foldp), and state changes HTML (view). The most basic application (a todo list) could have a simpler architecture without components, just a foldp and view function in their own files. This is how the Pux TodoMVC example is organized.

  - The aforementioned thesis is that, actually, componentization CREATES boilerplate : you have to wire your components together don't you. The way this is done in pure functional languages is through lenses and prisms, which are specific to each component being wired (they carry the specific type information with them), meaning you need to write them every time if you want to keep type safe. That also means anytime you change your component structure, you have to unwire/rewire the whole thing, and rewrite your boilerplate : error-prone, productivity loss.

- *polylithic* : Fat component tree/Light component. Of course, some functional frameworks for writing application disagree. That is the case for [purescript-thermite](https://github.com/paf31/purescript-thermite), which provides a `focus` function to wire components into a component tree. State is passed down the component with lenses, actions bubble up with prisms, and it is all type safe at every level. Boilerplate is significantly reduced due to helper functions such as `focus` (to wire up parent and children), `split` (for dynamic component), `foreach` (for list of children components), `withState` (to inject state in component) but is still there. I mean at a minimum you will always have to tell which is the parent and which are the children and then the types. 
  - The thesis here is that boilerplate can be reduced to a minimum, and the typical componentization advantages appear : increased productivity (assuming you can make use of a component library), increases reliability (supposing your imported components have been thoroughly tested by a third party), reduced complexity (assuming you reached a component tree with is highly cohesive and loosely coupled)
  - The benefits of (a good) componentization are real, documented, and it is an active subject of research to evaluate what makes a good componentization. Because just breaking down a reactive system into smaller pieces does not provide in and of itself the aforedescribed benefits. Some decompositions are better than others (high cohesion, loose coupling...), and there is where comes into play the software ENGINEER.

I personally prefer a vision made of component libraries written by UI/UX/domain experts, component wiring methods written by framework experts, and programmers extracting specifications from end-users and quickly whipping up prototypes (and well... debugging). This is actually already the reality of whoever uses abundantly microservices. which are nothing else than components in a service-oriented architecture.

Coming back to the value of a componentization framework for cycle, I believe the jury is still out there. It is about us going out and writing large scale apps and seeing what worked best. In any case, I think your attempt at reducing boilerplate through abstractions is valuable, thanks for caring and thanks for sharing.

**Comment by staltz** [comment]
Hi folks :)

Boilerplate reduction of this type often makes sense in a specific project where many components end up following the same pattern, and as third-party helpers/utils such as [cycle-utils](https://github.com/sunny-g/cycle-utils) and [cyclejs-utils](https://github.com/cyclejs-community/cyclejs-utils). In the general case, it can become very hard to find those patterns, as the framework is used in different ways that a specific application may use. Also, I think it's still valuable to teach the low-level approach first, for two reasons: (1) it's less magic, requires less mental effort for beginners to follow and trust (*it's just a function, it's just streams*), (2) the low-level style doesn't have that much boilerplate. You mentioned the following duplication

> 1) In the state object
> 2) In the interface name for the action type
> 3) In the interface type as a string for the action type
> 4) In the union type across all action types for that component
> 5) In the intent, to create the correct action type from the raw payload
> 6) In the intent, to assign the correct type field for the action type
> 7) In the reducer, to check for an action of the correct type and if so create a new state
> 8) In the reducer merger, to merge all the reducers for that component
> 9) In the view, for that input control

A lot of this is related to action type and strings, which was an idea we picked from Redux, aiming at making reducers/actions in Cycle.js look familiar to Redux users. In hindsight I regret doing that recommendation as action type strings add little benefit to the app, just bring a lot of duplication. Check this commit where I refactored an app to remove them: https://github.com/staltz/matrixmultiplication.xyz/commit/f246e4e0ce22191d271a7460b8731c876778b6da

**Comment by benalbahari** [comment]
@staltz

On "magic"... there's good magic and bad magic. Types of bad magic:

1) Black-box magic - the magic makes it impossible to access the lower layer
2) Leaky magic - the magic leaks so many concerns of the lower layer that it's easier to just directly use the lower layer
3) Rare magic - the magic is used so rarely that in absolute terms (# of developer hours saved vs cost to produce the magic) that there's no benefit over the lower layer
4) Obfuscating magic - the magic obfuscates the mental model of the lower layer
5) Unlawful magic - the magic breaks laws/principles of the lower layer
6) Redundant magic - the magic can just as easily be achieved by the lower layer

Good magic, OTOH, is really just good abstraction.

I'd paraphrase your argument against a general-use component layer, as the asserion that it's bad magic of types '3' and '4', and '6'.

Regarding '3', rare-magic: I'd suggest that the distribution of framework requirements across applications isn't even/random as you suggest, but way more 80/20ish. Angular, for all its faults, seems to be very good at catering to common needs - e.g. they have a story for parent/child relationships, form inputs, validation, out of the box. Cycle.js doesn't, which hampers its adoption.

Regarding '4', obfuscating-magic: I don't see how ComponentBuilder obfuscates understanding streams. There's little indirection between ComponentBuilder and streams, so it's easy to see the translation. The obfuscation argument works much better against Cycle.Js itself: streams massively obfuscate the underlying understanding of events; the virtual DOM massively obfuscates the actual DOM.

Regarding '6', redundant-magic: I'm still seeing way too much boilerplate in the code you sent. For example, this file:

```
import xs, {Stream} from 'xstream';
import {State, Reducer, Measurements} from '../index';

export function updateMeasurementsReducer$(measurements$: Stream<Measurements>): Stream<Reducer> {
  return measurements$
    .map(measurements => function (prevState: State): State {
      return {...prevState, measurements};
    });
}
```
Ironic the word 'reduce' is in there so many times.

I honestly think this sort of boilerplate stream logic puts off a lot of developers, who'll just use something else like React that they more readily understand. Then, when their application gets more complex and they could really reap the benefits of Cycle, they're not using Cycle.

Anyway, thanks for the reply and for the links. And cool matrix app!

@brucou - very insightful thoughts on component design. It's taking me some time to digest it all.

> Because just breaking down a reactive system into smaller pieces does not provide in and of itself the aforedescribed benefits.

Agreed. Composability is a necessary but not sufficient condition for a good component model. You mention high cohesion / low coupling as another condition. The excessive wiring of Cycle.js components seems a form of high coupling. Kyle Cordes mentioned at one point in one of his Cycle.js videos:

> There's really no way to use a component at a single point in the code. Inevitably you are making the component, and passing wiring to it in multiple directions

That exactly mirrored my experience using Cycle.js, which convinced me the problem isn't specific to my application at all. Yes, it's sometimes critical to control wiring explicitly. But it's reasonable for a single API to support both manual and semi-automatic wiring.

I briefly looked at the code in the link you sent. How does it relate to onionify?

**Comment by brucou** [comment]
@benalbahari which one of the link are you referring to ? I am generally agree with you with two caveats :

- I don't think there is *excessive* wiring of cycle components. I mean it is not like you have an extra `subscribe` somewhere that you don't need.  Now the wiring can end up looking like a lot of code, for sure, but it is not excessive, it is just what it is. If you package it out in a nice utility function, you still have the same wiring code even if you don't see it, and none of it was useless.

- Coupling is necessary, that is the point of using components in the first place, to couple them into a component tree. The idea is to have them loosely coupled, as loosely coupled as possible. Cf. https://en.wikipedia.org/wiki/Coupling_(computer_programming) : 7 types of coupling ; no coupling = `Modules do not communicate at all with one another.` I'll argue wiring components is `Message coupling (low)` or `Data coupling`, which are the lowest form of coupling.

For instance, look at an html file without listeners in one file, and setting up the listeners in another file. Those two pieces of code are actually highly coupled (through the DOM selectors). Using again the classification mentioned in the wikipedia article, this would be `Content coupling` or `Common coupling`, which are the highest forms of coupling. That is why there is a trend towards putting those two pieces of code together (same goes for the style file which is also coupled through DOM selectors), whatever that together means (same directory, same file, same function, etc.).

So wiring is not in my opinion a form of strong coupling, but still, writing the same thing 10 times, yes, it makes sense at the minimum to have an utility function to offload the repetitive tasks, as @staltz mentioned with the two libraries he gave. I went a level farther in the abstraction (after toiling through a very large (hard to read, hard to maintain) cycle app) and I am writing a reasonably sized app (which is already written in Angular2, cf. `Mastering Angular2 components` book by `Packt`) to show the benefits/disadvantages of that approach ; and along the way gives a direct comparison of Angular2 vs. Cycle. I anticipate to you upfront that the advantage of cyckle vs Angular2 is cristal-clear.

@staltz is definitely right that is valuable to explain the basic approach to beginners. One should always strive to understand one level of abstraction below BUT also one level above to master one given level. For intermediate-level users I believe it is rather useful to have the level of abstraction above streams (i.e. components) and the corresponding componentization framework which naturally includes wiring. I hope to finish the application I am working on to make that case with less words and more code.

Last, I like very much your taxonomy of magic. First time I see it. Does that come from some article or from your extended experience?

**Comment by whitecolor** [comment]
> I honestly think this sort of boilerplate stream logic puts off a lot of developers, who'll just use something else like React that they more readily understand. Then, when their application gets more complex and they could really reap the benefits of Cycle, they're not using Cycle.

If not typings issues the code could be with `ramda`:
```ts
const updateMeasurementsReducer$ = R.map(R.assoc('measurements')) // add some typings to your taste =)
```
(though this would definitely scare people even more)

> I honestly think this sort of boilerplate stream logic puts off a lot of developers,

Really? How about redux actions/reducers boilerplate?

> There's really no way to use a component at a single point in the code. Inevitably you are making the component, and passing wiring to it in multiple directions

> That exactly mirrored my experience using Cycle.js, which convinced me the problem isn't specific to my application at all. Yes, it's sometimes critical to control wiring explicitly. But it's reasonable for a single API to support both manual and semi-automatic wiring.

You will still have wiring, just with another specific API. And the wiring is the essential piece of functional programming paradigm. All functions are "wired" through inputs and outputs, this what makes it compatible and reliable.

I'm not saying that you are not correct that it is often possible and need to reduce a boilerplate in many cases. But I agree with @staltz:

> Boilerplate reduction of this type often makes sense in a specific project where many components end up following the same pattern

It is very hard to come to the right balanced abstraction that will satisfy everyone even for very specific tasks. But you always may try, just should remember: are you discovering or creating? Discovering is a right way to go, and *creative creating* leads to the world full of ~shit~ nonsense.

**Comment by benalbahari** [comment]
@brucou - just came up with the "magic" taxonomy reflecting on experience (note that 'leaky' is obviously a direct reference to Joel Spolsky's leaky abstractions). I'll ask you some questions later on your component combinators project - I'm just very busy this week and really need to spend more time understanding your approach. I broadly agree with your comments here.

Thanks for everyone's help.

**Comment by brucou** [comment]
@benalbahari sure please do.
