### ISSUE TITLE
@cycle/http 14.5.0 isolation issue (a regression from 14.2.0)

### ISSUE THREAD

**Issue by VasilioRuzanni** [cyclejs/cyclejs#720]
Encountered an issue when upgrading `@cycle/http` to `14.5.0`. The HTTP responses don't make it to a response stream. This turned out to be isolation issue appeared after this commit: https://github.com/cyclejs/cyclejs/commit/e0dea73

**Code to reproduce the issue:**
https://jsbin.com/hinifocufu/edit?html,js,output

**Expected behavior:**
HTTP responses should work just fine through multiple levels of `isolate`ion

**Actual behavior:**
HTTP response stream never emits when `isolate`d more than 1 once with different isolation scopes.

**Versions of packages used:**

- `xstream@11.0.0`
- `@cycle/run@3.3.0`
- `@cycle/dom@18.3.0`
- `@cycle/http@14.5.0`
- `@cycle/isolate@3.1.0`

**Some insights:**
The problem is that [`arrayEqual`](https://github.com/cyclejs/cyclejs/blob/2aec2d3a0ad1db7dddc5017b23e63af574587220/http/src/isolate.ts#L4) assumes the 2 arrays of namespaces (the one in `request` and that in `isolate`d source) are exactly the same - i.e., absolutely identical, with elements going in exactly the same order, while this `request._namespaces.push(...)` [here](https://github.com/cyclejs/cyclejs/blob/2aec2d3a0ad1db7dddc5017b23e63af574587220/http/src/isolate.ts#L43) actually makes the array reverse (perhaps, because it happens in `isolateSink` and sinks are "outputs" and are collected on the way back, thus resulting in the reverse order of the `request` namespaces).

Looks like it should either:
- be a `req._namespaces.unshift(...)` [here](https://github.com/cyclejs/cyclejs/blob/2aec2d3a0ad1db7dddc5017b23e63af574587220/http/src/isolate.ts#L43); OR
- `request.namespace` should be passed in a reverse order [here](https://github.com/cyclejs/cyclejs/blob/2aec2d3a0ad1db7dddc5017b23e63af574587220/http/src/isolate.ts#L24)

The issue obviously doesn't appear when there's no `isolate` or when there's only one `isolate(...)` call (because in that case there's just one element in the `_namespaces` array).

Hopefully, I'm not missing something important, guys!

**Comment by staltz** [comment]
Looks like a legit bug. Thanks for the detailed report!

**Comment by whitecolor** [comment]
@staltz maybe replace `_namespaces` Array with a Map (or better with simple object) and then assign props to it instead of `push`, checking presence also will be quicker than `indexOf` and other array methods.

**Comment by jvanbruegge** [comment]
@whitecolor, the order of namespaces is important. I introduced this bug with the fix of a bug that was exactly this: Wrong isolation due to ignoring of order

**Comment by whitecolor** [comment]
> the order of namespaces is important.

Why? I don't get it.

**Comment by whitecolor** [comment]
> the order of namespaces is important.

I see that issue https://github.com/cyclejs/cyclejs/issues/685 about the same scope value passed to `isolate`. Why not just make it unique (by adding to the string something)? And get rid of a little bit complicated array-based logic. Just as a variant.

**Comment by jvanbruegge** [comment]
Adding to the string would have to be random, and this random can be the same. Thus it doesnt fix the bug, it just makes it very unlikely. I'd rather do a proper fix and avoid nondeterminism

**Comment by whitecolor** [comment]
> Adding to the string would have to be random, and this random can be the same. 

No, you may just check if the key already exists in `_namespaces` object, you prefix it with just say `_`, no need to use anything random. or you may add innter isolate counter value, and increment it as it is done for implicit scope.

**Comment by jvanbruegge** [comment]
Still not a nice solution. I would avoid `Math.random()`. The data structure that suits the best here is a stack. You push the inner namespaces on top, and pop on the exit

**Comment by whitecolor** [comment]
@jvanbruegge 
No need to use random, though you probably right about a stack here.
