### ISSUE TITLE
Update dependencies and devDependencies for all packages

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#723]
Some dependencies are important to update, like `snabbdom-selector` in cycle/dom and `superagent` in cycle/http, but there are also important devDependencies like Mocha.

Once in a while these packages should be updated.

I'm working on this right now.

**Comment by mightyiam** [comment]
For the record, [Greenkeeper](https://greenkeeper.io/) is awesome. It even [handles `package-lock.json`](https://github.com/greenkeeperio/greenkeeper-lockfile).

It can't handle monorepos, as far as I know.

**Comment by mightyiam** [comment]
Oh, but maybe if the various projects are git submodules? Does anyone know about git submodules to think whether this would work?

**Comment by staltz** [comment]
We tried Greenkeeper long ago, it didn't work plus (as a bug) it abused my personal account to send random PRs elsewhere.

I don't mind manually updating dependencies myself once in a while. There are subtle issues involved that I don't think Greenkeeper handles.

**Note to self: wait for snabbdom-selector PRs to get merged and released, before releasing new cycle/dom version.**

**Comment by whitecolor** [comment]
@staltz probably it is better to move most of the common dev dependencies (test, stream libs) in the root package.json to share across all packages.

**Comment by TylorS** [comment]
@staltz I can highly recommend https://renovateapp.com/ it's highly configurable and capable of handling all of the `package.json`s in a monorepo. You can handle more complex workflows like "schedule PRs for 2am on Monday" with additional setup and the author is super receptive of new ideas and improving existing functionality.

**Comment by jvanbruegge** [comment]
@TylorS that looks promising

**Comment by whitecolor** [comment]
Also may try if [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) can work out.

**Comment by staltz** [comment]
New versions have been released. And yes, that renovateapp looks very good, thanks @TylorS !
