### ISSUE TITLE
DOM: `readyState` fires `complete` without `interactive`

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#730]
https://github.com/cyclejs/cyclejs/blob/master/dom/src/makeDOMDriver.ts#L84

```
if (document.readyState === 'interactive') {
   rootElement$.addListener(listener);
}
```

I faced situation (on latest chrome) where `readyState` is `complete` on the first fire time without firing `interactive`. 

Also it is known that IE 10 (which is still a target browser), has problems with firing `interactive` too early. So possible solutions:
1) check `complete` event instead of `interactive`
2) check first event and drop other, for IE check `completed` event.

**Comment by staltz** [comment]
@whitecolor do you think this will fix it? https://github.com/cyclejs/cyclejs/pull/719/files#diff-bb656acbfe74e1759e3753244ac3b5dfR60

**Comment by whitecolor** [comment]
I believe it should.

**Comment by staltz** [comment]
I'll release an `rc` and then you can test it out and see if it fixes the issue.

**Comment by staltz** [comment]
Try out `@cycle/dom@20.0.0-rc.1` and `@cycle/run@4.0.0-rc.4`

**Comment by whitecolor** [comment]
Think can be closed.
