### ISSUE TITLE
Update the cjs/mjs packaging

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#740]
Currently, we package both CommonJS and ES modules.

The way we do it is out-of-date.

We transpile twice:

1. to `lib/cjs`
1. to `lib/mjs`

And we specify a `module` field in `package.json`.

To be up-to-date with the proposal, we should:

1. Transpile twice into `lib`.
   1. ES modules with `.mjs` extension
   2. CommonJS with `.js` extension
2. Remove the `package.json` `module` field.
3. Set the `package.json` `main` field to `./lib/index` (no extension).

Regarding the `.mjs` extension: there is [no support for that in TypeScript](https://github.com/Microsoft/TypeScript/issues/18442). So, we'd have to set up renaming, it seems.

https://github.com/nodejs/node-eps/blob/6eef91d4ab4544ee5ed01df86dd7d055e90e130e/002-es-modules.md#44-shipping-both-esm-and-cjs

**Comment by jvanbruegge** [comment]
Support for .mjs is not very good. Only new node versions and the upcoming (!) webpack 4 support it. Therefore this change would break a lot of tooling.

**Comment by jvanbruegge** [comment]
Closing this because mjs is mostly for nodejs. For frontend bundlers using the `module` field in the package.json is still the preferred way
