### ISSUE TITLE
`time` hyperscript helper is missing, previous PR merge lost

### ISSUE THREAD

**Issue by ntilwalli** [cyclejs/cyclejs#748]
I submitted a PR in June to add a `time` hyperscript-helper.  It was merged but was overrwritten by the following merge for that file.

The PR which was merged, then overwritten is: https://github.com/cyclejs/cyclejs/pull/639

Can that PR be re-applied?

**Comment by staltz** [comment]
Hi @ntilwalli. Are you sure it was missing? It's right now in `master`: https://github.com/cyclejs/cyclejs/blob/5be4faa0eac6f93470a25281bd6167a61bb0de93/dom/src/hyperscript-helpers.ts#L222

Which version were you using?

**Comment by ntilwalli** [comment]
Odd.  I thought the `time` lines were missing in the file.  I must have checked the wrong version when I posted the issue.  Disregard.
