### ISSUE TITLE
Please update `@cycle/http` package in registry

### ISSUE THREAD

**Issue by mauroporrasp** [cyclejs/cyclejs#776]
Please update `@cycle/http` package in registry.
Yarn is downloading a version which has outdated dependencies.

**Comment by mauroporrasp** [comment]
@staltz would you take a look please?

**Comment by staltz** [comment]
Hi! :)
Could you give us a bit more information on how to reproduce this? For instance, versions of tools used, expected outcome versus actual outcome.

**Comment by mauroporrasp** [comment]
Hi @staltz, sure: Please download the .tar.gz that is currently on the npm registry, and compare it's dependencies with the latest Github version. They don't match.
