### ISSUE TITLE
MainDOMSource.element calls xstream specific methods on adapted streams

### ISSUE THREAD

**Issue by siliconbrain** [cyclejs/cyclejs#785]
**Code to reproduce the issue:**
```
const {makeDOMDriver} = require('@cycle/dom');
const {run} = require('@cycle/rxjs-run');
run(
  function({DOM}) {
    DOM.select('#some-element').element()  // --> 'remember' is not a function
  },
  {
    DOM: makeDOMDriver('.container')
  }
)
```

**Expected behavior:**
Returns stream of selected element.

**Actual behavior:**
An error is thrown. The problem is caused by [this line](https://github.com/cyclejs/cyclejs/blob/4bdb8ddf9e890a4771a3f6d26cf79708d211d2f0/dom/src/MainDOMSource.ts#L137) reusing `MainDOMSource.elements`'s return value which has been adapted to the target library (in this case, RxJS).

**Versions of packages used:**
`@cycle/dom`: 20.1.0
`@cycle/rxjs-run`: 8.0.0

**Comment by staltz** [comment]
Hi :)
Thanks for letting us know. Looks legitimate. I'll try to fix it asap.

**Comment by staltz** [comment]
DOM v20.2.0 released
