### ISSUE TITLE
@cycle/dom package size bloated in v19.3 onwards

### ISSUE THREAD

**Issue by vrobinson** [cyclejs/cyclejs#787]
Something happened in version 19.3 that caused the /dist folder package size to more than double in size.

Version 19.2 (https://unpkg.com/@cycle/dom@19.2.0/dist/) had file sizes of 131/58kB while version 19.3 (https://unpkg.com/@cycle/dom@19.3.0/dist/) had files sizes of 310/126kB. The larger file sizes continue in later versions.

**Comment by fuunnx** [comment]
I agree, it happens to me too

**How to reproduce :** 
Write this and build :
```
import {run} from '@cycle/run'
import {makeDOMDriver} from '@cycle/dom'

run(() => ({}), {DOM: makeDOMDriver('#sinimo-app')})
```

**Resulting bundles :**
v19.2 
![capture d ecran 2018-04-20 a 14 40 41](https://user-images.githubusercontent.com/5963805/39051407-ddb6f1b6-44a8-11e8-8128-f115eec1ffbb.png)

v19.3 
![capture d ecran 2018-04-20 a 14 35 55](https://user-images.githubusercontent.com/5963805/39051308-8f48ce14-44a8-11e8-9795-518aca971c5a.png)


**Detailed reports for v19.2, v19.3 and v20.1** :
[bundleAnalyzerReport.zip](https://github.com/cyclejs/cyclejs/files/1932102/bundleAnalyzerReport.zip)

According to the changelog there was an update to cssauron2, could this be the the culprit ?
