### ISSUE TITLE
Request for feedback on my popular "Cycle.js vs React" Medium article

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#799]
This article of mine titled "[Cycle.js vs React](https://medium.com/@mightyiam/cycle-js-vs-react-ec04aa8eb723)" gets upwards of 100 views per month. Perhaps some of you Cycle.js experts would like to review it and let me have some feedback and I will act on that feedback to the benefit of the readers?
![image](https://user-images.githubusercontent.com/635591/38502125-4a30b31c-3c17-11e8-91e8-a5f202e42163.png)

**Comment by Widdershin** [comment]
Overall I like this post, it's a good high level overview of what React and Cycle are and how they differ.

> the growth is interesting because it is apparently powered by smart people (I desire to be as smart as them when I grow up)

I'm not sure that this is the best way to tell this story.

I think it plays into a larger phenomena where technologies closer to the statically typed/functional side of the spectrum are regarded as sitting on an ivory tower, and that you need to be really smart to write them.

Without getting into the notion that "smart" is a linear spectrum, I think this myth is damaging in all sorts of ways.

The biggest one is that it might scare off potential users and contributors, especially if it seems like you have to be super technical to get involved. Impostor syndrome is real, and impacts people from marginalized communities the most.

The next is that it implies that React is not powered by smart people, when the React team clearly has their share of amazing, brilliant people, and the same is true of the React community.

It also implies that React is worse than Cycle, when in reality they are very different technologies with different goals and tradeoffs.

I'm not sure what I would replace that sentence with, but that was what came to mind while reading it.

Hope this is helpful feedback 😺

**Comment by mightyiam** [comment]
@Widdershin thanks. I wouldn't like to encourage those notions. I just removed that whole paragraph.

It seems that this article is a doorway, a fork in the road for many who are deciding whether to give Cycle.js a try. So if anyone else has any feedback or additions, please come forth.
