### ISSUE TITLE
Make `isolate` return a HOC instead of a Component

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs/cyclejs#800]
Currently, isolate has type `isolate :: (component, scope) -> component`
If you have to isolate multiple times or you want to use other HOCs this gets a bit tedious. Example from my code (currently working on an update to `cyclejs-sortable`):
```js
const Navbar = isolate(
  makeSortable(sortableOptions)(
    isolate(
      makeCollection({
          //...
      }),
      scope1
    )),
  ),
  scope2
);
```
This code would be a lot more readable if isolate had the type `isolate :: Scope -> Component -> Component`
That way I could write this code like this:
```js
const Navbar = pipe(
    isolate(scope1),
    makeSortable(sortableOptions),
    isolate(scope2)
)(makeCollection({ /* ... */ }));
```
Or if I'm using the new pipe operator:
```js
const Navbar = makeCollection({ /* ... */ })
  |> isolate(scope1)
  |> makeSortable(sortableOptions)
  |> isolate(scope2)
```

**Comment by staltz** [comment]
Thinking that instead of a breaking change, why not make another function that uses the current isolate? Functional programming allows composable non-breaking evolution of software

**Comment by jvanbruegge** [comment]
Then the question is how to name it. One possibility would be to rename the current isolate to _isolate and name the new one a named export.
So `import isolate from ...` is the old one and `import { isolate } from ...` is the new one, but thats awefully confusing

**Comment by staltz** [comment]
Yep, agreed that naming would be the only complication. I think we should aim for an actually different name, to avoid confusion. E.g. `toIsolated` ?

**Comment by jvanbruegge** [comment]
I like `toIsolated`

**Comment by staltz** [comment]
So let's go with that. :) This should be easy to implement

**Comment by staltz** [comment]
isolate v3.3.0 released!
