### ISSUE TITLE
Add FAQ section in the docs

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs/cyclejs#809]
A few questions keep popping up from time to time, most of the time related to snabbdom usage. Two current examples are #808 and #807 .
I think we should add a section in the docs where we can provide solutions for those common problems.
Problems to include:
- hooking into the element creation/update/deletion (#807)
- Using props for attrs that change (except for svg) (#808)
- Execute code when DOM is loaded ([Stackoverflow](https://stackoverflow.com/questions/36530485/running-js-code-after-all-dom-rendered-in-cycle-js#answers))
- Lenses with `makeCollection` ([Stackoverflow](https://stackoverflow.com/questions/50828271/cycle-js-how-to-get-collection-length-in-a-collection-item))

**Comment by staltz** [comment]
Agreed! We could put it as a "chapter" in the Guide, after "Drivers" chapter.

**Comment by staltz** [comment]
#810

**Comment by jvanbruegge** [comment]
Added a few FAQ entry to the top post (to be extended)

**Comment by jvanbruegge** [comment]
Added lenses with `makeCollection`

**Comment by staltz** [comment]
Where are you adding these things?

**Comment by jvanbruegge** [comment]
Oh, just to the top comment, to keep track of them. I havent started (or have the time to start) a proper FAQ yet

**Comment by jopek** [comment]
### TypeScript Problem
`HTTP.select('XX').flatten()` returns a `MemoryStream<Response> & ResponseStream` type. when assigning it to a Stream<Response> one gets a typescript error:
```
Type 'MemoryStream<Response> & ResponseStream' is not assignable to type 'Stream<Response>'.
  Types of property '_prod' are incompatible.
    Type 'import("/Users/alex/dev/learn/cyclejs/playground/node_modules/xstream/index").InternalProducer<import("/Users/alex/dev/learn/cyclejs/playground/node_modules/@cycle/http/lib/cjs/interfaces").Response>' is not assignable to type 'import("/Users/alex/dev/learn/cyclejs/playground/node_modules/xstream/index").InternalProducer<Response>'.
      Type 'import("/Users/alex/dev/learn/cyclejs/playground/node_modules/@cycle/http/lib/cjs/interfaces").Response' is not assignable to type 'Response'.
        Property 'headers' is missing in type 'Response'.
```

_TypeScript probably thinks you mean this Response https://developer.mozilla.org/en-US/docs/Web/API/Response_

### Solution
```
import { Response } from '@cycle/http';
```

**Comment by bemayr** [comment]
Great idea, when showing _cycle.js_ to programmers I often experienced that resetting state (e.g. reset the Counter Example to 0) requires a different thinking. Maybe we could add this as well.

**Comment by jvanbruegge** [comment]
I am closing this in favor of #851
