### ISSUE TITLE
Move from yarn to pnpm

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs/cyclejs#818]
pnpm is faster, uses less disk space and has amazing monorepo commands. The architecture is a lot better than yarn or npm.
This will allow us to get rid of our Makefile and will improve speed.
Furthermore we can use `pnpm recursive link` in CI to test against the git HEAD of each package

**Comment by staltz** [comment]
👍

**Comment by jvanbruegge** [comment]
Done with #821
