### ISSUE TITLE
Updating to rxjs6 

### ISSUE THREAD

**Issue by theJian** [cyclejs/cyclejs#820]
[PR #819](https://github.com/cyclejs/cyclejs/pull/819)

I would like to update `rxjs-run` to be able to use rxjs6. Here are some problems I think we need to address.

I am just starting learning cyclejs and trying to getting involved to cyclejs development few weeks ago, so I am not sure if there any breaking changes were introduced I didn't notice. 

If it's ok to drop rx5 support? People couldn't upgrade to rxjs6 for any reason have to stick with the current version(`8.x.x`) of `rxjs-run`. rxjs6 compitible version will start with `9.x.x`. Or any possible better roadmap?

**Comment by staltz** [comment]
> If it's ok to drop rx5 support?

Yes! It's okay, people can still freely use cycle/rxjs-run 8.x. And rxjs6 support can be released on cycle/rxjs-run 9.x. But you can leave publishing concerns to me, just make sure to use `make commit` so that the commit message will have all the necessary info for showing up in the changelog.
