### ISSUE TITLE
setupReusable's dispose is wrong

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#824]
**Code to reproduce the issue:**

```js
import {setupReusable} from '@cycle/run';
const {sources, run} = setupReusable(drivers);
// ...
const sinks = main(sources);
const dispose = run(sinks);
// ...
dispose();
```

**Expected behavior:**

`dispose()` should not dispose all resources, it should dispose only what was *exclusively* used by `main`.

**Actual behavior:**

`dispose()` disposes everything, essentially making the engine not reusable.

**Versions of packages used:**

cycle/run 4.3.0

**Comment by staltz** [comment]
I know how to fix this, the unfortunate thing is that it would be a breaking change (changes behavior of setupReusable).

**Comment by jvanbruegge** [comment]
Dont think that is a big deal, as it was released yesterday and was not announced. I hightly doubt that anyone is using this new API
