### ISSUE TITLE
HTTP isolation expects 'map' by default, Rxjs6 does not provide it by default

### ISSUE THREAD

**Issue by ntilwalli** [cyclejs/cyclejs#826]
in Rxjs6 all operators are applied through pipe. When not importing ‘rxjs-compat’ the map operator is not available on the base observable. Isolation currently assumes map exists on the streams sent as sinks. This means importing ‘rxjs-compat’ is effectively required to ensure the map operator exists on the sink observables... is the best approach to fork cycle/isolate for myself and apply via pipe? Is there something more elegant?

**Comment by jvanbruegge** [comment]
I think the cleanest approach would be to `adapt` in `@cycle/isolate`

**Comment by staltz** [comment]
Are you sure this is a problem in cycle/isolate? I can't even find the map operator in the source code of isolate

**Comment by ntilwalli** [comment]
Ah, I saw that isolation was the issue and jumped to the broadest conclusion, my bad, it's in HTTP: https://github.com/cyclejs/cyclejs/blob/master/http/src/isolate.ts#L38

**Comment by jvanbruegge** [comment]
Yeah, I would assume the driver is written with xstream, so `@cycle/isolate` should `adapt` before calling into a driver

**Comment by ntilwalli** [comment]
Are you suggesting that a second function, lateral to `adapt` be registered?   Like a function indicating how to apply a 'map' operation so `isolate` can apply that registered function instead of calling 'map' directly?  

In this case the HTTP driver does `request$.map(someFn)` but in the case of Rxjs6 it should import the `map` operator from `rxjs/operators` and call `request$.pipe(map(someFn).  So I guess in the registeration approach it would do something like `applyMapFromAdapt(request$, someFn)`?  Do I understand correctly?

**Comment by staltz** [comment]
To be more accurate, `@cycle/isolate` should `adapt` *after* calling into a driver's isolateSink.

Reminder: `adapt` is xstream=>others. `xs.fromObservable` is others=>xstream.

HTTP driver is written internally with xstream. So when `@cycle/isolate` call's HTTP's isolateSink, it must pass an xs stream as the `innerSink` to it, *or* HTTP driver itself converts using xs.fromObservable, then uses map, and returns an xs stream. `@cycle/isolate` gets that xs stream, calls `adapt` on it and gets the `outerSink` usable by your application.

**Comment by jvanbruegge** [comment]
I would say `@cycle/isolate` should use `xs.fromObservable` and `adapt` as our current polocy regarding drivers is: Write them with xstream (as the official ones) or you will have to convert. It would be weird to have to adapt for isolation only

**Comment by staltz** [comment]
cycle/isolate 3.4.0 released. Thanks @ntilwalli !
