### ISSUE TITLE
Create Cycle.js sanbox type at codesandbox.io

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#828]
I believe it would be nice to have `Cycle.js` among others here: https://codesandbox.io/s/

**Comment by staltz** [comment]
Would be really great indeed

**Comment by achou11** [comment]
Created this super barebones one that just uses Codesandbox's vanilla template (so it uses Parcel), in case anyone's interested!

https://codesandbox.io/s/cycle-basic-dy2j3
