### ISSUE TITLE
rxjs-run with TypeScript: property 'scan' does not exist on type 'Stream<Event>'.

### ISSUE THREAD

**Issue by mxhllnn** [cyclejs/cyclejs#829]
The return value of `DOMSource.events` is [typed](https://github.com/cyclejs/cyclejs/blob/master/dom/src/DOMSource.ts#L18) as `Stream<Event>`, where `Stream` is an xstream stream. @cycle/rxjs-run [adapts](https://github.com/cyclejs/cyclejs/blob/master/rxjs-run/src/index.ts#L20-L22) the xstream stream to an RxJs Observable. The return value of the `adapt` function is typed `Observable<any>` but I believe this value is [assigned](https://github.com/cyclejs/cyclejs/blob/05011896ef15876c10fe7c9aa86e5cf275c9e8fd/dom/src/MainDOMSource.ts#L250) to a variable typed `DevToolEnabledSource & Stream<Event>`. TypeScript seems to resolve the value to type `Stream<Event>`. This causes compilation to fail when Rx.Observable methods are called on the value. Compilation fails with a similar error if I cast `Stream<Event>` to `Observable<Event>`. Oddly enough, compilation succeeds if I trigger it a second time without new changes. Here is a test case. Most of the code is generated by create-cycle-app. 

I'm not sure what to make of this. It seems likely to be a user error on my part. Thanks for taking a look.  

**Code to reproduce the issue:**

index.ts 

```typescript
import {run} from '@cycle/rxjs-run'
import {makeDOMDriver} from '@cycle/dom'

type Component = (s : Sources) => Sinks;

import {App} from './app'

const main : Component = App

const drivers = {
  DOM: makeDOMDriver('#root')
}

run(main, drivers)
```

app.tsx

```typescript
import * as Rx from 'rxjs'

type Sources = {
  DOM : DOMSource;
}

type Sinks = {
  DOM : Observable<VNode>;
}

const add = (x1: number) => (x2: number): number => x1 + x2;

const addOne = add(1);

export function App(sources : Sources) : Sinks {
  const clickCount$ = sources.DOM
    .select('.button')
    .events('click')
    .scan(addOne, 0);

  const vtree$ = Rx.Observable.of(
    <button className="button">Button</button>
  );

  return {
    DOM: vtree$
  }
}
```

**Expected behavior:**

The code compiles.

**Actual behavior:**

Compilation fails with: 

```
[at-loader] Checking finished with 1 errors
[at-loader] ./src/app.tsx:12:6
    TS2339: Property 'scan' does not exist on type 'Stream<Event>'.
```

**Versions of packages used:**

```json
"dependencies": {
	"@cycle/dom": "18.3.0",
	"@cycle/rxjs-run": "7.1.0",
	"awesome-typescript-loader": "3.2.3",
	"rxjs": "5.4.3",
	"typescript": "2.5.3"
}
```

**Comment by staltz** [comment]
Hi! I believe in app.tsx you should do

```typescript
import {DOMSource} from '@cycle/dom/rxjs-typings'
```

(Let's reopen this issue if that doesn't solve it)

**Comment by mxhllnn** [comment]
Unfortunately not. The value still resolves to the xstream types.

```typescript
import {DOMSource} from '@cycle/dom/rxjs-typings'

// ...

const button$: DOMSource = sources.DOM.select('.button');
const click$ = button$.events('click');
const clickCount$ = click$.scan(addOne, 0);
```

```
[at-loader] Checking finished with 1 errors
[at-loader] ./src/app.tsx:10:9
    TS90010: Type 'DOMSource' is not assignable to type 'DOMSource'. Two different types with this name exist, but they are unrelated.
  Types of property 'elements' are incompatible.
    Type '() => MemoryStream<string | Element | Document | Element[]>' is not assignable to type '() => Observable<Element | Element[]>'.
      Type 'MemoryStream<string | Element | Document | Element[]>' is not assignable to type 'Observable<Element | Element[]>'.
        Property '_isScalar' is missing in type 'MemoryStream<string | Element | Document | Element[]>'.
```

```typescript
import {DOMSource} from '@cycle/dom/rxjs-typings'

// ...

const button$: DOMSource = sources.DOM.select('.button') as DOMSource;
const click$ = button$.events('click');
const clickCount$ = click$.scan(addOne, 0);
```

```
[at-loader] Checking finished with 1 errors
[at-loader] ./src/app.tsx:10:19
    TS2352: Type 'DOMSource' cannot be converted to type 'DOMSource'.
  Types of property 'elements' are incompatible.
    Type '() => MemoryStream<string | Element | Document | Element[]>' is not comparable to type '() => Observable<Element | Element[]>'.
      Type 'MemoryStream<string | Element | Document | Element[]>' is not comparable to type 'Observable<Element | Element[]>'.
        Property '_isScalar' is missing in type 'MemoryStream<string | Element | Document | Element[]>'.
```

**Comment by staltz** [comment]
Can you give more details? Like what is `Sources` in index.ts?

**Comment by mxhllnn** [comment]
Oh good question. I simplified the examples a little from the create-cycle-app file structure but tested your suggestion with the original code. I understand now why you said the type needed to be imported. create-cycle-app creates a src/interfaces.ts file where those types are defined. That is where `DOMSource` should be imported from '@cycle/dom/rxjs-typings' but is imported from '@cycle/dom'.  So I think this is a bug in create-cycle-app. The steps to reproduce are:

1. `create-cycle-app foo`
1. Select TypeScript
1. Select RxJS
1. Open src/interfaces.ts.

Sorry for the run-around and thanks for the help!

**Comment by staltz** [comment]
Good! Open an issue with create-cycle-app then :)

**Comment by mxhllnn** [comment]
Thanks again for the help. I moved the discussion here: [create-cycle-app/issues/123](https://github.com/cyclejs-community/create-cycle-app/issues/123)
