### ISSUE TITLE
rxjs-run@8 is broken for rxjs@5 users

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs/cyclejs#830]
Users, who have not switched to rxjs 6 should use rxjs-run v8. But this will break their setup:
https://github.com/cyclejs/cyclejs/blob/8f8fd53987fefaa1fde1f53f962be4a8111f4a24/rxjs-run/package.json#L35
We have to release a patch with the dependency on rxjs set to `< 6.0.0`

**Comment by jvanbruegge** [comment]
This is actually blocking me with #821

**Comment by jvanbruegge** [comment]
pnpm is amazing, was able to work around this with a `pnpmfile.js`, thanks @zkochan!
```js
module.exports = {
    hooks: {
        readPackage
    }
};

function readPackage(pkg, context) {
  if(!pkg.dependencies) return pkg;

  if(pkg.dependencies.rxjs === '*') {
    pkg.dependencies.rxjs = '^5.5.11'
    context.log('rxjs@* => rxjs@5 in ' + pkg.name);
  }

  return pkg;
}
```

**Comment by staltz** [comment]
Wow, didn't know there was such a thing as pnpmfile.js.

> We have to release a patch with the dependency on rxjs set to `< 6.0.0`

Did you mean `>=6.0.0`?

**Comment by staltz** [comment]
Oh no, sorry, now I get it, the latest rxjs-run is v9.

**Comment by jvanbruegge** [comment]
Yeah, it's the old version that needs a patch

**Comment by jvanbruegge** [comment]
@staltz could you do this? I was able to work around this, but everyone that uses rxjs 5 is screwed...

**Comment by staltz** [comment]
Sure

**Comment by staltz** [comment]
Done. cycle/rxjs-run 8.1.0 released that supports rxjs 5

**Comment by jvanbruegge** [comment]
I think you accidently set the latest version to 8.1.0

**Comment by staltz** [comment]
Urgh, indeed, completely forgot about dist-tags. Will fix
