### ISSUE TITLE
Capture clicks isn't working for history driver

### ISSUE THREAD

**Issue by janat08** [cyclejs/cyclejs#840]
**Code to reproduce the issue:**
https://github.com/janat08/makpal/tree/17916c23b3ffd4c68fe5f7bed350061c8670e027

**Expected behavior:**
<a> in jsx to not reload page.

**Actual behavior:**
reloads page on href

**Versions of packages used:**
    "@cycle/history": "^6.10.0",
    "@cycle/run": "^4.1.0",

**Comment by jvanbruegge** [comment]
Can you try with `<a attrs-href="..." />`?

**Comment by janat08** [comment]
I can't tell what commit I was referencing to, but it works now.
