### ISSUE TITLE
npm rxjs-run v 9.2.0 is invalid, needs to be retranspiled/published

### ISSUE THREAD

**Issue by ntilwalli** [cyclejs/cyclejs#842]
I'm not clear on how this happened, but the lib files posted to npm for rxjs-run are out of sync with the source code.  It just needs to be retranspiled and republished to npm.

To check: 
1) Install a fresh copy of @cycle/rxjs-run
2) Check lib/es6/index.js and you'll see that it still refers to Observable.from which is from Rxjs 5

**Comment by am-a** [comment]
+1

**Comment by jvanbruegge** [comment]
@staltz had to republish a v8 version because of a bug and most likely forgot to rebuild after changing back to the current version

**Comment by ntilwalli** [comment]
Is that why v9.2.0 was published in the first place?  Was it meant to be published as a v8 version? I couldn't see any code changes between 9.1 and 9.2 so I'm not clear on what motivated it...

**Comment by jvanbruegge** [comment]
Yeah, because by accident v8 was made latest

**Comment by ntilwalli** [comment]
Ah got it

**Comment by am-a** [comment]
What is the status of this? It seems like a serious issue if the latest NPM release is broken. Is it a simple fix?

**Comment by jvanbruegge** [comment]
@staltz is currrently in Barcelona, and my publish rights do not work at the moment, so expect one or two days more.

**Comment by jvanbruegge** [comment]
now fixed with `9.3.0`
