### ISSUE TITLE
Typings (e.g. run and dom but probably others) don't work as expected

### ISSUE THREAD

**Issue by texastoland** [cyclejs/cyclejs#847]
I was reviewing the [egghead course](https://github.com/eggheadio-projects/cyclejs-fundamentals) and tried to add typings since the files are `*.ts`. Starting with the latest dependencies, `"strict": true` in `tsconfig.json`, and the [counter example](https://github.com/cyclejs/cyclejs/blob/master/examples/basic/counter/src/main.js):

```js
function main(sources) {
  // see link for full implementation
  return {
    DOM: vdom$
  };
}

run(main, {
  DOM: makeDOMDriver('#app')
});
```

My intuition was it should just work with a single annotation on `main`:

```ts
function main(sources: {DOM: DOMSource}) {
```

The first problem is `run`'s types don't match because `makeDOMDriver` returns its concrete type (`MainDOMDriver`) instead of interface. I ran into this with with XStream's `MemoryStream` as well. Not ideal but easy to fix.

```ts
function main(sources: {DOM: MainDOMSource}) {
```

The next problem is `run` expects `main` to handle `undefined`. The signature is easy to fix.

```ts
function main(sources?: { DOM?: MainDOMSource }) {
```

How `main` should recover from missing sources is less clear. Not ideal but fixable with non-null assertions e.g. `sources!.DOM!.select`.

The final problem is `main` returns `Stream<VNode>` but `run` expects the driver's stream to be either `FantasyObservable | undefined | void | null`. `null` seems like a logic error. `void` and `undefined` are synonyms already inferred by `Driver`. `Stream` is not a `FantasyObservable` because the latter expects `subscribe` to handle `undefined`. Not easy to fix.

The typings look impressive. They just appear underused. Converting the existing examples to TypeScript with as minimal annotations as possible would reveal these usability issues.

**Comment by fasiha** [comment]
Possibly related: https://github.com/staltz/cycle-onionify/issues/69 I found that the `bmi-typescript` example fails to build with TypeScript 2.5 or newer.

**Comment by Sinewyk** [comment]
Code
```ts
import { run } from '@cycle/run';
import { makeHTTPDriver } from '@cycle/http';

function main() {
    return {};
}

const drivers = {
  HTTP: makeHTTPDriver(),
};

run(main, drivers);

```

Error
```
Argument of type '{ HTTP: Driver<Stream<RequestInput>, HTTPSource>; }' is not assignable to parameter of type 'MatchingDrivers<{ HTTP: Driver<Stream<RequestInput>, HTTPSource>; }, () => {}>'.
  Type '{ HTTP: Driver<Stream<RequestInput>, HTTPSource>; }' is not assignable to type 'Drivers'.
    Property 'HTTP' is incompatible with index signature.
      Type 'Driver<Stream<RequestInput>, HTTPSource>' is not assignable to type 'Driver<void | Stream<any>, any>'.
        Types of parameters 'stream' and 'stream' are incompatible.
          Type 'void | Stream<any> | undefined' is not assignable to type 'Stream<RequestInput> | undefined'.
            Type 'void' is not assignable to type 'Stream<RequestInput> | undefined'.
```

Had to read https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3114-assignment-compatibility to understand ...

There is an issue (I think) between

https://github.com/cyclejs/cyclejs/blob/79c65de5d0b00cd60b4657691ac7cc99d59ce22f/run/src/types.ts#L23-L25
and
https://github.com/cyclejs/cyclejs/blob/79c65de5d0b00cd60b4657691ac7cc99d59ce22f/run/src/types.ts#L29-L31

Not sure if real problem or Typescript bug but
```ts
export type Drivers = {
  [name: string]: Driver<Stream<any>, any | void>;
};
```
works

but
```ts
export declare type Driver<Si, So> = {
  (stream?: Si | void, driverName?: string): So;
};
```
may be better

**Comment by staltz** [comment]
To do list after merging #852:

- [ ] remove npm links from dependencies
- [ ] remove `rc` versions from dependencies
- [ ] release non-rc versions for each package
