### ISSUE TITLE
@cycle/time operators does not always complete properly

### ISSUE THREAD

**Issue by fuunnx** [cyclejs/cyclejs#848]
Hi !

I had a memory leak in my app and I found that the root cause were `Time` operators not completing properly (which remained active and triggered heavy computations multiple times). 

Adding this statement here https://github.com/cyclejs/cyclejs/blob/master/time/src/debounce.ts#L59 fixed it :
```js
stop() {
  stream.shamefullySendComplete()
},
```

I'll add a reproductible example later and would be glad to make a pull request to fix it of course

**Comment by fuunnx** [comment]
Hi, as promised here is a minimal reproducible example :

[![Edit yj4x45l4oz](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yj4x45l4oz)

**Expected behavior** : No more 'before' logs after 1200ms when using a `Time` operator

**Observed behavior** : They are still there. They disappear as expected when no more `Time` operator is in the chain.

**Comment by Widdershin** [comment]
@fuunnx thanks for your report and reproducer. I'm unlikely to have time to sort this out soon so if you do want to make a pull request that would be fantastic.

**Comment by fuunnx** [comment]
I'll do, I've already started :)
