### ISSUE TITLE
rxjs dependency in @cycle/dom?

### ISSUE THREAD

**Issue by wclr** [cyclejs/cyclejs#854]
The latest 22.0 cycle dom has rxjs dependency?

**Comment by jvanbruegge** [comment]
`dom/src/rxjs.ts`. Before we had rxjs-typings.d.ts, but now typescript (correctly) detects that the DomSource we return from `makeDOMDriver` is not the one from the rxjs-typings

**Comment by whitecolor** [comment]
Well, then I just don't get why TS should be unhappy and require RxJS to be present in node_modules if I don't require `dom/rxjs` in my code?
