### ISSUE TITLE
TypeScript (tsc) errors on MainFn signature

### ISSUE THREAD

**Issue by chikamichi** [cyclejs/cyclejs#863]
Hi,

While running `tsc` in strict mode, I recently got this error:

```
src/index.ts:29:5 - error TS2345: Argument of type 'MainFn<Forbid<Sources, "state">, Omit<Sinks, "state">>' is not assignable to parameter of type 'MatchingMain<{ dom: Driver<Stream<VNode>, MainDOMSource>; }, MainFn<Forbid<Sources, "state">, Omit<Sinks, "state">>>'.
  Type 'MainFn<Forbid<Sources, "state">, Omit<Sinks, "state">>' is not assignable to type 'Main & ((so: Sources<{ dom: Driver<Stream<VNode>, MainDOMSource>; }>) => Omit<Sinks, "state">)'.
    Type 'MainFn<Forbid<Sources, "state">, Omit<Sinks, "state">>' is not assignable to type '(so: Sources<{ dom: Driver<Stream<VNode>, MainDOMSource>; }>) => Omit<Sinks, "state">'.
      Types of parameters 'sources' and 'so' are incompatible.
        Type 'Sources<{ dom: Driver<Stream<VNode>, MainDOMSource>; }>' is not assignable to type 'Forbid<Sources, "state">'.
          Type 'Sources<{ dom: Driver<Stream<VNode>, MainDOMSource>; }>' is not assignable to type 'Omit<Sources, "state">'.
            Types of property 'dom' are incompatible.
              Type 'MainDOMSource' is not assignable to type 'DOMSource'.
                Types of property 'elements' are incompatible.
                  Type '() => MemoryStream<Element[]>' is not assignable to type '() => MemoryStream<string | Element[] | Document[] | HTMLBodyElement[]>'.

29 run(main, drivers)
```

**Code to reproduce the issue:**

The affected code is [available here](https://github.com/chikamichi/typometer/tree/v0.2.0). Demo runs at https://typometer.netlify.com/.

I believe it's fairly close if not par with the latest documentation as far as defining types (sources / sinks) goes. But I'm fairly new to TypeScript and this is my pet project, so after spending a few hours fixing loads of type checking errors and narrowing it down to that single one, I'm in for some expert insights :)

**Expected behavior:**

Not having this huge beast of an error message :D

**Actual behavior:**

`tsc` not happy with my CycleJS types.

**Versions of packages used:**

- @cycle/dom 22.0.0
- @cycle/http 15.0.0
- @cycle/isolate 4.1.0
- @cycle/run 5.1.0
- @cycle/state 1.0.0
- see [package.json](https://github.com/chikamichi/typometer/blob/v0.2.0/package.json#L17-L24)

**Comment by jvanbruegge** [comment]
I am closing this, because there is already an issue (#847) and I've also finished a PR yesterday (#852), so expect this to be released in the next few days
