### ISSUE TITLE
http `test` script do not run http `test-node`, only `test-browser`

### ISSUE THREAD

**Issue by Sinewyk** [cyclejs/cyclejs#865]
Since https://github.com/cyclejs/cyclejs/commit/fe3c5cedf69391bc052519534fc22ab6ca2fb1c9

They seem to be broken on master because they are not automatically ran anymore.

How it should be: https://github.com/cyclejs/cyclejs/blob/master/dom/package.json#L45
How it is: https://github.com/cyclejs/cyclejs/blob/master/http/package.json#L69

suggested labels: `issue is bug`, `help wanted`, `priority 3 (should)`, `scope: http`

**Comment by jvanbruegge** [comment]
@Sinewyk thanks for noticing, I've opened a PR to fix this
