### ISSUE TITLE
@cycle/state unecessary delay, probable race condition

### ISSUE THREAD

**Issue by Sinewyk** [cyclejs/cyclejs#878]
I think this piece of code https://github.com/cyclejs/cyclejs/blob/479f5566850de92ff3fcb35fb389044c534f48ec/state/src/withState.ts#L42-L46 may be introducing a non necessary possibility of a race condition.

I was playing around with sampleCombine to do multiple things when reacting to a http response (updating state and dispatching another http request) ... but the state inside the "outer" state from sampleCombine, and the inner state from the reducer I was sending back in the sink sometimes were out of sync, something like this:
```js
const responseHandler$ = sources.HTTP.select()
	.map(response$ => response$
		.replaceError(err => xs.of(err.response)) // Just passthru errors
	)
	.compose(flattenConcurrently)
	.compose(sampleCombine(sources.state.stream))
	.map(([res, outerState]) => {
		return {
			state: xs.of(prevState => {
				if (prevState !== outerState) {
					console.error(new Error('Race condition detected'));
					process.exit(1);
				}
				return someMutateFunction(prevState);
			}),
			HTTP: xs.of({
				url: // Using outerState here
			}),
		};
	);

// I use this to split event after that and feed it into sinks
const split = whatToSplit => stream =>
	stream
		.map(x => x[whatToSplit])
		.filter(x => !!x)
		.flatten();
```

I guess if two http responses come back "too quick" ... the reducer is called with the correct state, but because the event on the `reducerMimic$` is delayed (it's using `quicktask` which uses `process.nextTick` on node), then the [sampleCombine code responsible for updating the values](https://github.com/staltz/xstream/blob/master/src/extra/sampleCombine.ts#L61) is not being called before the second response handler is added. So I guess ...

Race condition:
Event loop: `[  Http response 1 available, Http response 2 available ]`
We start executing the first one, which schedules the _n
Event loop is then: `[ Http response 2 available, mimic._n ]`
So the response 2 sampleCombine is executed with "wrong" values.

I then used this patch and the race condition disappeared (and tests are still fully green):

```patch
diff --git a/state/src/withState.ts b/state/src/withState.ts
index 030084c1..aa91388f 100644
--- a/state/src/withState.ts
+++ b/state/src/withState.ts
@@ -39,11 +39,13 @@ export function withState<
         xs.fromObservable<Reducer<T>>(sinks[name]),
         xs.never()
       );
-      stream$.subscribe({
-        next: i => schedule(() => reducerMimic$._n(i)),
-        error: err => schedule(() => reducerMimic$._e(err)),
-        complete: () => schedule(() => reducerMimic$._c()),
-      });
+      schedule(() => {
+        stream$.subscribe({
+          next: i => reducerMimic$._n(i),
+          error: err => reducerMimic$._e(err),
+          complete: () => reducerMimic$._c(),
+        });
+      })
     }
     return sinks as any;
   };
```

With this patch the sampleCombine internal values are immediately updated as soon as possible, and so when handling the second one everything is good to go.

I guess the intent is still the same, ensure the first event happens off the main execution thread, asynchronously (unless I'm missing something). But with no possibility of sampleCombine and the inner state being off sync.

Thoughts ? (ping @jvanbruegge because gitter conv)

I also want to ping staltz because he's the only who probably knows why the `schedule` delay is there, but ...

**Comment by Sinewyk** [comment]
I avoided the error by reworking my code, there must be a race condition "somewhere", but I had no luck finding it. I don't know if it's a bug or I was just mis-using something.

So closing this.

**Comment by staltz** [comment]
Thanks @Sinewyk even though this is now closed, it still serves as a potential reproducible use case later.

There is certainly a race condition in cycle/state, and it should/will be fixed when we move from drivers to plugins, and make cycle/state a plugin not a wrapper. Then it can share the (supposedly) race-condition-free machinery inside cycle/run.

**Comment by Sinewyk** [comment]
Proof: https://github.com/Sinewyk/cycle_state_race_condition

**Comment by Sinewyk** [comment]
Now I will try to reproduce the race condition WITH my patch, because in my real project it also happened.
