### ISSUE TITLE
Add `withLocalState` to @cycle/state

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs/cyclejs#882]
A pattern that I regularily use in my code base when dealing with controlled inputs is local state. For example I want to capture the a search string as the user types, but this search string is only interesting to the component itself and should not be part of the global state. For this purpose I have created a combinator `withLocalState` that uses a second, locally scoped `withState` and some conversion functions to allow to mix and match global and local state. This looks something like this:
```ts
interface GlobalState {
    users: User[];
}
interface ComponentState {
    global: GlobalState;
    local: { searchString: string };
}

export const MyComponent: Component<GlobalState> = withLocalState(MyComponentInternal);

function MyComponentInternal(sources: Sources<ComponentState>): Sinks<ComponentState> { /* ... */ }
```

The implementation from my code base can be found [here](https://gist.github.com/jvanbruegge/9af17f4f5fca8bb3e6198ebe65afac55)

**Comment by sarimarton** [comment]
Isn't the search string accessible with `DOM.select(selector).events('change').map(ev => ev.target.value)`?

**Comment by staltz** [comment]
What I'm wondering is why couldn't you do `withState(comp, 'local')`:

```typescript
export const MyComponent: Component<GlobalState> = withState(MyComponentInternal, 'local');
```

This way it could have both sinks `local` and `state` (the default "global" channel for state).

**Comment by jvanbruegge** [comment]
@sarimarton of course this is how to get the value, what I mean is if I need itin the state, e.g. when combining with other data

@staltz that works in the example above, but if you take a look at the implementation, it allows to abitrarily merge the local and global state, possibly deriving data. That makes encapsulating the component easier, because it does not depend on the fact that it has local state, for all it knows it gets normal "global" state

**Comment by mightyiam** [comment]
How is this better than conventional local state, please? I seem to have no problem to solve regarding local state. It lives in an operator inside the component and never leaves. It is encapsulated. It can be tested. It is simple. Am I missing something? I can combine it with state from the global state using an operator inside the component, I can imagine. Although I've yet to try @cycle/state.

**Comment by brucou** [comment]
- I gonna say something everybody knows, but typescript makes this kind of code really hard to read.
- `delete sourcesCopy[localChannel];` maybe that is not true anymore or it does not matter, but I read somewhere that deleting properties from an object forced v8 deoptimization
- also not sure what that is : `StateSource`
- the implementation looks good, to build trust in it as much as clarifying/documenting use cases, tests would be good
- the idea is good, would it only be because it serves you
- the pattern itself could be generalized to handle source injection, which is something that often occurs in cycle code. Well it used to happen in mine anyways.

**Comment by staltz** [comment]
@jvanbruegge Okay, then two questions: (1) could we decouple "I need local state" from "I need to merge local and global state" and have two separate (hence composable) solutions? (2) How common would it be for cycle/state users to want simultaneously those two needs that it would be a strong enough argument to add the API? Usually we build these things as utilities outside of this monorepo (just like cycle-onionify was), to experiment with the API's usefulness and adequacy.

**Comment by jvanbruegge** [comment]
@mightyiam this would allow to hand the "local state" over to child components normally with lenses just as normal with global state, because the component itself does not know it is local state.

@brucou yeah, the code is directly from my code base and is not the prettiest. `StateSource` comes from `@cycle/state` and deals with the isolation. What do you mean with source injection?

@staltz I dont see it as "*I need local state*" because the component itself is not aware that it has local state. For all it knows it could be completely global state. So IMO this is just "merge global with local state". Yeah, no hard feeling where this lives, I can publish a small utility of course.

**Comment by brucou** [comment]
Source injection is, say, you have a component `C = f(s_1, ...s_{n-1})` then `injectSource(C) = C' = g(s_1, ..., s_{n-1}, s_n)` where `s_n` is the injected source.
An edge case of that is when the injected source is already is the set of sources, in which case(!) we get your `withLocalState` case.

I had lots of these patterns in a large codebase. A common reason it was occurring was to create derived state. Typically at the top level the remote state is accessed through some sources (http, firebase, whatever), and then a parent component would derive and format some piece of state for consumption by a child component. Some other times , the injected source was purely for interface adaptation reasons, say you consume a component which requires a Y instead of an X so you translate X to Y, and inject Y.

**Comment by staltz** [comment]
If I understand correctly what @brucou means with "source injection", it's when you wrap a (inner) component with an outer component which creates a source and passes that source to the inner component. So `withState` is a utility that does source injection.

> So IMO this is just "merge global with local state". Yeah, no hard feeling where this lives, I can publish a small utility of course.

@jvanbruegge Yes, what I meant with "two concerns" is that I believe that this feature suggestion is a composition (in Haskell notation) `withLocalState = mergeGlobalAndLocal . (withState "local")`, where `withState` is the current `@cycle/state` utility.

**Comment by jvanbruegge** [comment]
this is actually a pretty nice idea, `withLocalState merger = injectSource (localState merger) . withState "local"`
Shouldn't be too hard to build either. `localState` would just take the two sources and merge them in an abitrary way.
The question would just be: Where should `injectSource` live? Probably in `@cycle/run`.

**Comment by staltz** [comment]
I like that `@cycle/run` is pretty clearly scoped: it's only for *running*. E.g. even `isolate` which is pretty important, is not in `@cycle/run`. Also note that we could create `@cycle/____` package without having it in the monorepo, as is the case for `@cycle/react`.

**Comment by sarimarton** [comment]
I myself came to the conclusion that a single state channel is a best practice, because child components should not know about parents' local channels. So this is indeed very useful.

One suggestion perhaps... I would use a `[global, local]` return value instead of `{ global, local }`

**Comment by sarimarton** [comment]
Another thought... key conflict might be a problem here. I know, obviously the whole point of a `merger` is to contain the conflict risk, but still, a merger doesn't necessarily know which keys will come from 'the other side' - if the merger is defined on the inner component's side, it doesn't know what keys a parent might bring, and vice versa.

Channeling the two states into an { outer, inner } object (defaultMerger) is safe, but then the original problem comes up: the child component knows about the modified state structure. In a nested environment, it could lead to a need to use `outer.outer....` subkey repetition.

Maybe using prototypes would solve this problem:

```jsx
  const customMerger = {
    merge: (global, local) => Object.assign(Object.create(global), local)
    extract: (state) => Object.getPrototypeOf(state)
  }
```

**Comment by sarimarton** [comment]
Maybe this one?...

```jsx
  const customMerger = {
    merge: (global, local) => Object.assign(Object.create(global), local, { ___$global: global })
    extract: (state) => ({ global: state.___$global, local: omit(state, '___$global') })
  }
```

This way, child components don't _need to_ know about global/local separation, we're completely pretected against key conflicts (local keys overshadow global ones in child components, but global state keeps being intact), and we're also protected against reducers.
