### ISSUE TITLE
Superagent problem in HTTP Driver

### ISSUE THREAD

**Issue by ftaiolivista** [cyclejs/cyclejs#884]
**Code to reproduce the issue:**
```
import { xs, run, DOM, makeHTTPDriver, S } from './vendor.mjs'

function usersView (user) {
    return (
        <div className="users">
            <button type="button" className="get-random">
                XCarica
            </button>
            {user ? (
                <div className="user-details">
                    <h1 className="user-name" />
                    <h4 className="user-email" />
                    <a className="user-website" href={user.website}>
                        {user.website}
                    </a>
                </div>
            ) : (
                ''
            )}
        </div>
    )
}

function main (sources) {
    const getRandomUser$ = sources.DOM.select('.get-random')
        .events('click')
        .map(() => {
            const randomNum = Math.round(Math.random() * 9) + 1
            return {
                url:
                    'https://jsonplaceholder.typicode.com/users/' +
                    String(randomNum),
                category: 'users',
                method: 'GET'
            }
        })

    const user$ = sources.HTTP.select('users')
        .flatten()
        .map(res => res.body)
        .startWith(null)

    const vdom$ = user$.map(usersView)

    return {
        DOM: vdom$,
        HTTP: getRandomUser$
    }
}

const drivers = {
    DOM: DOM.makeDOMDriver('#app'),
    HTTP: makeHTTPDriver()
}

run(main, drivers)
```

**Expected behavior:**
Make HTTP request on button click

**Actual behavior:**

vendor.mjs:4606 TypeError: superagent[sanitizedMethod] is not a function
    at optionsToSuperagent (vendor.mjs:7343)
    at Object.startResponseStream [as start] (vendor.mjs:7404)
    at Object._start (vendor.mjs:113)
    at Stream._add (vendor.mjs:936)
    at Remember._start (vendor.mjs:731)
    at MemoryStream._add (vendor.mjs:1771)
    at Flatten._n (vendor.mjs:587)
    at Stream._n (vendor.mjs:860)
    at Filter._n (vendor.mjs:515)
    at Stream._n (vendor.mjs:866)

**Versions of packages used:**
Yarn lock file: https://gist.github.com/ftaiolivista/6c3dd9d04365e25c9dd1aba17590a959

**Comment by staltz** [comment]
Hi! What's this `vendor.mjs` file that you're using to import the libraries?

**Comment by ftaiolivista** [comment]
@staltz  sorry... it's a compilation of dependencies

Usually I compile all dependency in a valid ES6 module to not have to live transpile anything while developing on Chrome.

vendor.mjs

```
import xs from 'xstream'
import { run } from '@cycle/run'
import * as DOM from '@cycle/dom'
import { makeHTTPDriver } from '@cycle/http'
import Snabbdom from 'snabbdom-pragma'
const S = Snabbdom
export { xs, run, DOM, S, makeHTTPDriver }

```

**Comment by ftaiolivista** [comment]
I suspect is because the bundler is using the node version of superagent instead of browser version. So for now I close the bug.
