### ISSUE TITLE
duplication of non boubling events

### ISSUE THREAD

**Issue by ftaiolivista** [cyclejs/cyclejs#903]
I have a DOM element emitting a CustomEvent.

On cycle component I do

```
state$.map(
   state => DOM.select('[name=' + state.name + ']').events('myNonBEvent', {}, false)
).flatten().addListener(...)

```
Every time the state change DOM.select.events add a new listener without removing the old one.

If I use boubling events all works good

```
// Change DOM components to emit boub events and...
state$.map(
   state => DOM.select('[name=' + state.name + ']').events('myBEvent')
).flatten().addListener(...)
```

**Comment by jvanbruegge** [comment]
Solved by #906 
Feel free to reopen if the issue still persists after the release of the new version
