### ISSUE TITLE
which way to make a child component?

### ISSUE THREAD

**Issue by zppro** [cyclejs/cyclejs#911]
I want create child component in app main function.
i can choose make all sources and drivers needed by child component in app 

> run function

,and I also can make child component's 

> main function

 by create the source object,
which way should i used
@staltz

**Comment by jvanbruegge** [comment]
I am not completely sure what you want, but for child components, you would nest "main" function, like here: https://cycle.js.org/components.html

**Comment by jvanbruegge** [comment]
As this is neither a bug or feature request, I will close this. Feel free to keep commenting if this was not clear

**Comment by zppro** [comment]
> As this is neither a bug or feature request, I will close this. Feel free to keep commenting if this was not clear

here is question : all sources and drivers need by difference components  should create in top-levels run?

**Comment by zppro** [comment]
> As this is neither a bug or feature request, I will close this. Feel free to keep commenting if this was not clear

@jvanbruegge 
here is question : all sources and drivers need by difference components  should create in top-levels run?

**Comment by jvanbruegge** [comment]
yes, you would thread them through. There are some utilities that make the plumping easier (I wrote cyclejs-utils for example) for for starters and learning, just doing it yourself is probably the best

**Comment by zppro** [comment]
> or f

nice , I'll learn it
