### ISSUE TITLE
request mutation in  isolateSink

### ISSUE THREAD

**Issue by ftaiolivista** [cyclejs/cyclejs#919]
Why request mutation in isolateSink? I'm incapped in a bug in wich I base a new request on precedent requests an the added _namespace break the isolation.
```
export function isolateSink(
  request$: Stream<RequestInput | string>,
  scope: string | null
): Stream<RequestInput> {
      ...
      req._namespace = req._namespace || [];
      req._namespace.unshift(scope);
      return req;
}
```
Would not be better to instantiate a new request?
```
export function isolateSink(
  request$: Stream<RequestInput | string>,
  scope: string | null
): Stream<RequestInput> {
      ...
     return {
                ...req,
                _namespace: [scope, ...(req._namespace || [])]
            }
}
```

**Comment by staltz** [comment]
This is very good point. I think we were trying to optimize (have less object allocations in memory) and didn't realize this use case. I'm lifting this issue's priority.
