### ISSUE TITLE
[suggestion] Make reportSnabbdomError configurable

### ISSUE THREAD

**Issue by ryota-ka** [cyclejs/cyclejs#922]
Hi!

Currently (dom: 22.5.0, html: 3.3.0), `reportSnabbdomError` is hardcoded and any errors will be passed to that function.
I wonder if it's nice if we could configure the error reporter function via `DOMDriverOptions` / `HTMLDriverOptions `.
(My use case is to report errors to Sentry.)

**Comment by Widdershin** [comment]
Good idea! Are you willing to make a pull request?

**Comment by ryota-ka** [comment]
Yes, of course! I'll make a PR later.
