### ISSUE TITLE
Unable to add multiple event handlers to the same nonBubbling event

### ISSUE THREAD

**Issue by b123400** [cyclejs/cyclejs#940]
**Code to reproduce the issue:**

```typescript
import xs, { Stream } from 'xstream';
import { VNode, DOMSource } from '@cycle/dom';
import { Sources, Sinks, Reducer } from '../interfaces';

export type State = number;

export function Counter({ DOM, state }: Sources<State>): Sinks<State> {
    const increment$ = Stream.merge(
        DOM.select('.input')
            .events('focus')
            .debug('first')
            .mapTo(null),
        DOM.select('.input')
            .events('focus')
            .debug('second')
            .mapTo(null)
    );

    const state$ = Stream.merge(
        xs.of((_: any) => 0),
        increment$.mapTo((x: State) => x + 1)
    );

    return {
        DOM: view(state.stream),
        state: state$,
    };
}

function view(state$: Stream<State>): Stream<VNode> {
    return state$.map((count) => (
        <div>
            <h2>My Awesome Cycle.js app - Page 1</h2>
            <span>{'Counter: ' + count}</span>
            <input className="input" />
        </div>
    ));
}

```

**Expected behavior:**

The above code adds 2 event handlers to `<input>`. When the input is focused, both stream should fire and the count should be increased by 2.

**Actual behavior:**

Only the first stream created by `DOM.select(...).events(...)` is fired.
The count increase by one.

------
If you change the event from `focus` to `click`, the count increases by 2 correctly.
I guess it is caused by 2f4ebc9e7f466ca7af7cc1f642001b8887dccb36 ?

**Versions of packages used:**

@cycle/dom: 22.6.0
@cycle/run: 5.4.0
create-cycle-app: 5.0.0
xstream: 11.11.0

**Comment by staltz** [comment]
Thanks @b123400, I think your conclusion sounds correct to me. Can you try changing from `focus` to `focusin` (which bubbles) and see if the behavior changes?

By the way, you described two expectations here:

> The above code adds 2 event handlers to <input>. When the input is focused, both stream should fire and the count should be increased by 2.

I think it would be okay to have just 1 event handler attached to `<input>` BUT I expect both streams `'first'` and `'second'` to emit, therefore incrementing by 2.

**Comment by b123400** [comment]
Thanks for the quick reply, I tried changing `focus` to `focusin` and now both the streams emit. Unfortunately the code I am actually writing is listening for the `submit` event and there isn't a similar workaround.

> I think it would be okay to have just 1 event handler attached to <input> (due to xstream being hot-by-default the DOM.select('.input').events('focus') stream should only attach one event listener) BUT I expect both streams 'first' and 'second' to emit, therefore incrementing by 2.

Yes, that works too. I am not familiar with the internals so I was guessing maybe an event listener is missing. It will be fine as long as both streams emit.

I've sent a PR trying to fix it: https://github.com/cyclejs/cyclejs/pull/941
