### ISSUE TITLE
Upgrade @cycle/dom to snabbdom v1

### ISSUE THREAD

**Issue by mightyiam** [cyclejs/cyclejs#944]
Snabbdom v1 [was released](https://github.com/snabbdom/snabbdom/blob/master/CHANGELOG.md#changelog). It includes some performance and bug fixes. And it provides only ES modules.

**Comment by ryota-ka** [comment]
Any progress on this or is there something blocking this?
Or should we wait for Cycle.js Neo?

Snabbdom have reached v3 with built-in JSX support, and it would be beneficial if we could use newer versions.
If help needed, I think I can make a contribution. 🙂 

cc: @staltz @jvanbruegge

**Comment by staltz** [comment]
@jvanbruegge is maintaining snabbdom and Cycle Neo, and I trust him in putting A inside of B when the right time comes. @ryota-ka you could coordinate with jvanbruegge on #929, I'm sure the bulk of work would there appreciate some help! :)

**Comment by jvanbruegge** [comment]
Yes, I released v3 in order to work on the Neo DOM driver. I do not plan to update snabbdom in the current DOM driver, but I would review and merge a PR for this

**Comment by ryota-ka** [comment]
@jvanbruegge Submitted #972!
