### ISSUE TITLE
how to render a component with "if else"

### ISSUE THREAD

**Issue by bgfist** [cyclejs/cyclejs#954]
**Code to reproduce the issue:**

I just don't know how to render a component with  "if else"

```js
function componentA(sources$) {
   return {
      dom$: ...,
      http$: ...
  }
}

function componentB(sources$) {
   return {
      dom$: ...,
      http$: ...
  }
}

function main(sources$) {
    
    sources$.props.pipe(
       switchMap(props=> {
           if (props.showA) {
              const sinksA$ = componentA(sources$);
           } else {
              const sinksB$ = componentB(sources$);
          }
      })
   )

  return {
           // how to make dom$ and htttp$ ?
  }
}

```

So how can I merge two different streams separately ?

**Comment by jvanbruegge** [comment]
You can use flatmap for the streams:
```ts
function main(sources) {
    const child$ = sources.props.pipe(
       switchMap(props=> {
           if (props.showA) {
              return componentA(sources);
           } else {
              return componentB(sources);
          }
      })
   );

  return {
    DOM: child$.pipe(flatMap(sinks => sinks.DOM)),
    HTTP: child$.pipe(flatMap(sinks => sinks.HTTP))
  }
}
```
As this is quite repetitive, you can write a small helper function like this:
```js
function sinks$ToSinks(sinks$, drivers) {
    let result = {};
    for(const name of drivers) {
        result[name] = sinks$.pipe(flatMap(x => x[name]));
    }
    return result;
}
```
and then use it like this:
```js
function main(sources) {
    //...
   return sinks$ToSinks(child$, ['DOM', 'HTTP']);
}

**Comment by bgfist** [comment]
> You can use flatmap for the streams:
> 
> ```ts
> function main(sources) {
>     const child$ = sources.props.pipe(
>        switchMap(props=> {
>            if (props.showA) {
>               return componentA(sources);
>            } else {
>               return componentB(sources);
>           }
>       })
>    );
> 
>   return {
>     DOM: child$.pipe(flatMap(sinks => sinks.DOM)),
>     HTTP: child$.pipe(flatMap(sinks => sinks.HTTP))
>   }
> }
> ```
> 
> As this is quite repetitive, you can write a small helper function like this:
> 
> ```js
> function sinks$ToSinks(sinks$, drivers) {
>     let result = {};
>     for(const name of drivers) {
>         result[name] = sinks$.pipe(flatMap(x => x[name]));
>     }
>     return result;
> }
> ```
> 
> and then use it like this:
> 
> ```js
> function main(sources) {
>     //...
>    return sinks$ToSinks(child$, ['DOM', 'HTTP']);
> }
> ```

Thank you so much ! Still I think the `child$` should be `shared` cause it's piped twice.

```js
function main(sources) {
    const child$ = sources.props.pipe(
       map(props=> {
           if (props.showA) {
              return componentA(sources);
           } else {
              return componentB(sources);
          }
      }),
      share()
   );

  return {
    DOM: child$.pipe(switchMap(sinks => sinks.DOM)),
    HTTP: child$.pipe(switchMap(sinks => sinks.HTTP))
  }
}
```
