### ISSUE TITLE
cycle/run issue with React Native

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cyclejs#955]
**Code to reproduce the issue:**

The issue happens not in all setups so it is not easy to reproduce, even the order of `import`s in a file may matter.

The problem that when this line is executed:
https://github.com/cyclejs/cyclejs/blob/master/run/src/internals.ts#L12
```ts
const scheduleMicrotask = quicktask();
```
RN timers (functions setImmediate, setTimeout) happen to be not initialized yet and it returns undefined, so `scheduleMicrotask` tends to be `undefined`.

Just screen as confirmation:
![image](https://user-images.githubusercontent.com/736697/93524810-8279b100-f94e-11ea-861e-1f8787556b2d.png)

If to place the line inside `replicateMany` (https://github.com/cyclejs/cyclejs/blob/master/run/src/internals.ts#L78) it should fix the issue.

Any objections or considerations against it?

@staltz

**Comment by staltz** [comment]
Good that you found this, and this is a great description of the bug. I think I agree with your solution as well.

@jvanbruegge ?

**Comment by jvanbruegge** [comment]
Yeah, me too
