### ISSUE TITLE
feat: suppout custom event on dom element

### ISSUE THREAD

**Issue by kongxiangyan** [cyclejs/cyclejs#958]
pseudo code below:

**Expected behavior:**

```js
// component
const Component = source => {
  return toStream(div(
    '.custom-component',
    { hook: { 
      insert: () => { 
        let proxyEle = document.querySelector('.custom-component')
        // ...some cases
        proxyEle.dispatchEvent(new CustomEvent('confirm', { detail: { value: 'inner value'} }))
      } 
    }}
  ))
}

// part of component usage
source.DOM.select('.custom-component').events('confirm').pipe(doTheBusiness())
```

**Actual behavior:**

The problem is that cycle can not select custom event (etc. 'confirm' in the code above) in the current version. i have check the code of eventDelegator, it seems that only the preset event type such as 'click' or 'input' can be adopted, so i change my custom event type from 'confirm' to a fake 'submit', it works fine, but not very elegant.

👀 I'm will be so so excited to see you guys update a better solution ! 

**Versions of packages used:**

@cycle/dom v22.7.0

**Comment by jvanbruegge** [comment]
Have you tried the custom event? because that should work for the dom driver

**Comment by kongxiangyan** [comment]
> Have you tried the custom event? because that should work for the dom driver

Thanks for your reply, but... I don't know what you mean exactly about `custom event`, is there any link for it?

**Comment by jvanbruegge** [comment]
I mean what happens if you use `.events(‘confirm') `, ie your CustomEvent

**Comment by kongxiangyan** [comment]
> I mean what happens if you use `.events(‘confirm') `, ie your CustomEvent

Just nothing happened with `source.DOM.select('.custom-component').events('confirm').pipe(doSomeStuff)`, `doSomeStuff` will never triggered when I dispatch the custom event. 

I check the source code, saw:

```ts
// MainDOMSource.d.ts
export declare class MainDOMSource {
  // ...
  events<K extends keyof HTMLElementEventMap>(eventType: K, options?: EventsFnOptions, bubbles?: boolean): Stream<HTMLElementEventMap[K]>;
  // ...
}
// in which HTMLElementEventMap refer to:
interface HTMLElementEventMap extends ElementEventMap, GlobalEventHandlersEventMap, DocumentAndElementEventHandlersEventMap {
}
```

Then I try to change 'confirm' to 'submit', it works fine.

**Comment by jvanbruegge** [comment]
I know why it does not work, custom events by default do not bubble, so either use `new CustomEvent('confirm', { bubbles: true, detail: /* ... */ })` or use `.events('confirm', { bubbles: false })`

**Comment by kongxiangyan** [comment]
> I know why it does not work, custom events by default do not bubble, so either use `new CustomEvent('confirm', { bubbles: true, detail: /* ... */ })` or use `.events('confirm', { bubbles: false })`

Nice! (I should read the source code more carefully🤐) Problem has been solved! `new CustomEvent('confirm', { bubbles: true, detail: /* ... */ })` works fine. 

And 'confirm' event expected to be no bubble, `.events('confirm', { bubbles: false })` doesn't works for me, it should be `.events('confirm', undefined, false)`~

Thanks for your time!
