### ISSUE TITLE
@cycle/time Assert-equals diagram are misleading

### ISSUE THREAD

**Issue by fuunnx** [cyclejs/cyclejs#962]
Hi, I'm using @cycle/time and I've stepped in some misleading error messages :

**Code to reproduce the issue:**

```jsx
Time.assertEqual(
   // a simplified version of my actual tested code
    xs.merge(
        xs.of(undefined),
        xs.of(undefined),
       Time.diagram('1-2-3x')
    ),
    Time.diagram('1-2-3x'),
)
```

**Expected behavior:**

Prints :
```
Expected

1-2-3x

Got

(undefinedundefined1)-2-3x
```

**Actual behavior:**

Prints :
```
Expected

1-2-3x

Got

(213x
```

**Versions of packages used:**

0.20.0

---

Fortunately the fix is straightforward, I'll do a pull request on a few days.

This is due to : 
- `undefined` being converted to `''`. I suggest converting it to the string `undefined`
- and chunks taking too much space on the diagram string

**Comment by jvanbruegge** [comment]
Yeah, thank you. I will review and merge the PR once it's done

**Comment by fuunnx** [comment]
Great, thanks

---

Actually I got a similar problem on the other direction (fromDiagram) with chunks : 

**Code to reproduce the issue:**

```
Time.assertEqual(
  Time.diagram('x-123456').startWith('o'),
  Time.diagram('(ox)-123456'),
)
```

**Expected behavior:**

Test passes

**Actual behavior**

Prints 

```
Expected

(ox)----123456

Got

(ox)-123456
```
