### ISSUE TITLE
Question: why there is not an hydrate function for isomorphic app like react?

### ISSUE THREAD

**Issue by lesar** [cyclejs/cyclejs#966]
> Have a question? Ask us on [StackOverflow](http://stackoverflow.com/questions/tagged/cyclejs).

sorry StackOverflow think my question is not good enough.  
I have a reputation by 600 but cannot ask.  
[me](https://stackoverflow.com/users/2053904/leonardo-saracini)

If you not give answers forgive me and simply close the issue.  

Why there is not an hydrate function for isomorphic app like react?  
How Cycle handle this application type (isomorphic)?  

reading the example is not help me much.  
sorry I'm new to Cycle  

there is some tutorial?  

I know how isomorphic work and I have write one prototype using Fastify, Inferno js and hyperscript  

I need some **hint** to travel from Inferno/react to Cycle Isomorphic app.

I have read all your documentation.  

Best regards,  
Leonardo

**Comment by jvanbruegge** [comment]
The main reason is that noone did the work yet, but in theory it should not not require much work. You would need to serialize the state from `@cycle/state` to a global variable and use and initial reducer to get that state back on the client side. If this initial state reducer is applied before the first render on the client happens (with `@cycle/dom`) the dom driver will automatically pick up the already rendered DOM and continue from there

**Comment by lesar** [comment]
Ok thank you
