### ISSUE TITLE
statecharts, scxml, xstate - similar projects?

### ISSUE THREAD

**Issue by milahu** [cyclejs/cyclejs#974]
at first sight, cyclejs reminds of finite state machines, as declared in statecharts / scxml / xstate

maybe we can connect these projects?
[xstate-viz](https://github.com/statecharts/xstate-viz) is a neat visualizer for state machines

statecharts &rarr; https://statecharts.dev/resources.html

**Comment by staltz** [comment]
There are some minor similarities, but a lot of differences too. Doesn't make sense to "connect" them.
