### ISSUE TITLE
[run] Drop dependency on quicktask?

### ISSUE THREAD

**Issue by ryota-ka** [cyclejs/cyclejs#990]
Internet Explorer will finally reach its end of life in the next month.

Now that [`queueMicrotask()` is widely implemented](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask#browser_compatibility) (including Node.js), can we consider dropping the library from the dependencies?

**Comment by staltz** [comment]
That would be great! In fact, I *think* we use queueMicrotask directly already in Cycle Neo, isn't it @jvanbruegge ?

**Comment by jvanbruegge** [comment]
yes, cycle/run has no dependencies

**Comment by ryota-ka** [comment]
Sounds nice.

Do you think it's still reasonable to remove it from the dependencies before Cycle.js Neo arrives?
(I have no idea on its ETA)

**Comment by staltz** [comment]
Probably not worth evolving current cycle js before neo lands.

**Comment by ryota-ka** [comment]
Okay, I'll close this then.
Can't wait for the Neo! 😆
